### ISSUE TITLE
abstime() and object.lifetime return wrong time

### ISSUE THREAD

**Issue by Arano-kai** [colobot/colobot#1006]
Ver: 0.1.9
OS: Debian (stretch)
in abstime():
```
abstime ( );
Return the time in seconds elapsed since the beginning of the mission.
```
in object:
```
float  object.lifeTime     Lifetime of the object
```
but both timers reset after load.

**Comment by Arano-kai** [comment]
```
extern void object::TimeTest()
{
	message("abstime=" + abstime() + " lifetime=" + this.lifeTime);
}
```
Before save:
![colobot gold edition_001](https://user-images.githubusercontent.com/1828919/28495031-6bb1b32e-6f49-11e7-96be-72c810ee1372.png)
After load:
![colobot gold edition_002](https://user-images.githubusercontent.com/1828919/28495033-7548579e-6f49-11e7-8789-f0839e993f86.png)

**Comment by krzys-h** [comment]
It's always been like that, but you are right, it would be more logical to save these values with the saved game.
