### ISSUE TITLE
switch..case not accept negative values

### ISSUE THREAD

**Issue by Arano-kai** [colobot/colobot#1008]
Ver: 0.1.10 (from sid)
OS: Debian (stretch)
#920 Fixed default args but not `switch..case` statement.
```
extern void object::TestSwitch()
{
	test(-2);
	test(-1,-1);
	test(-1);
}

void test(int a, int b = -2) {
	message("a="+a+" b="+b);
	switch(a){
		case b: message("a=b"); break; // completely ignores, see #998
		//case -1: message("a=-1"); break; // can't find ":" <== fixed by #920... or not (:
		case 0: message("a=0"); break;
		case 1: message("a=1"); break;
		default: message("woops!");
	}
}
```

**Comment by Arano-kai** [comment]
Please note, that is current Linux release is from sid (unstable), so need confirmation on other platforms.

**Comment by tomaszkax86** [comment]
I can confirm that there's a problem on Windows as well. Negative numbers cause compilation error and none of those tests worked right.

However, `switch...case` in most languages doesn't normally accept variables for `case` clauses, only constants, so `case b:` is probably incorrect on the language level. I think we could keep this, but we need to fix the bug first.

**Comment by melex750** [comment]
This compiles with no error:(
```c++
extern void CaseBug()
{
	switch(-1)
	{
		case var   :
		case case  :
		case while :
		case "str" :
		case ?     :
		case int   :
		case point :
		case &&    :
		default:
	}
}
```
The fact that you can use a variable name with```case```is a bug,
in such cases, the equivalent of```case 0:```is compiled.

It would be nice if unary operations **```+  -  ~```**, and other
arithmetic and bitwise operations, could be used with```case```.

I think only numerical constants should be supported, including character constants and enumerators.

**Comment by Arano-kai** [comment]
Then we has to have the way to define const and enum in scripts.
