### ISSUE TITLE
OrgaShooter matter ball sometimes goes really big

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1009]
After you equip OrgaShooter with powercell organic matter sometimes goes crazy. 
![before](https://user-images.githubusercontent.com/4140449/28590494-97718300-7182-11e7-81d3-6c551d3adf91.png)
![after](https://user-images.githubusercontent.com/4140449/28590495-97789258-7182-11e7-99e3-6835f95f1fd7.png)
It doesn't appear everytime, sometimes you need to insert powercell few times.

**Comment by Arano-kai** [comment]
Just... don't... feed that slime... anymore, please...

**Comment by krzys-h** [comment]
Little-known fact about OrgaShooters - the size of this ball in the gun actually represents the state of the energy cell, the less energy in the cell, the smaller the ball. Looks like we broke something when refactoring to new object interface, as there were a few changes to how normal vs nuclear cells are handled

**Comment by Arano-kai** [comment]
That orga-slime always spawn when orga-shooter equipped with cheated power/nuke cell, since their `energyLevel` is 99.

**Comment by tomangelo2** [comment]
Fixed after dab223e6ce27a1df5671476ef63cfce9ae3a9627
