### ISSUE TITLE
Background planets/stars move in opposite direction to view

### ISSUE THREAD

**Issue by immibis** [colobot/colobot#1021]
Latest dev build (commit 0de347d430106ac3bf9df005aedb826076255e44), compiled myself.

When I rotate the view the stars and planets in the sky rotate in the opposite direction. This is particularly noticeable in the moon flying practice missions, but seems to happen in every level (at least every level that has these objects). Clouds are not affected.

**Comment by immibis** [comment]
I'm currently working on this. There will be some maths involved as the planets are treated as 2D sprites, not 3D objects.

**Comment by tomaszkax86** [comment]
I think I can implement something that could simplify this: point sprites. Instead of drawing quads manually rotated towards the camera, we could let OpenGL do the thing for us. Requires OpenGL 2.0 or ARB_point_sprite but I think I can write code for when neither is available.

**Comment by immibis** [comment]
I think we should be drawing quads and using the world matrix to do the transformations. Point sprites won't do because the rotation will be incorrect if the camera has roll (like if you're using the first-person view on a robot that's sitting on a slope).

It'll be quite difficult to keep the planets in the same location they are now, so the cutscenes will probably have to be updated.

**Comment by immibis** [comment]
By the way, what's the reason to even have an OpenGL 1.4 renderer - are 10 year old laptops common in Poland?

**Comment by tomangelo2** [comment]
Because it was written as quick replacement for original DirectX7 API at the beginning of the project and newer engines are still experimental, there are few issues with them.
