### ISSUE TITLE
SIGSEGV when starting a code battle on a non-scoreboard map

### ISSUE THREAD

**Issue by immibis** [colobot/colobot#1023]
Latest dev version, compiled myself.

robotmain.cpp:5868:

    m_codeBattleStarted ? pl->SetName(StrUtils::ToString<int>(m_scoreboard->GetScore(team))) : static_cast<Ui::CEdit*>(pl)->SetText(StrUtils::ToString<int>(m_scoreboard->GetScore(team)));

This line crashes when starting the game if the map does not have a scoreboard, because m_scoreboard is NULL. None of the built-in code battle levels have a scoreboard, so I'm not sure how this ever worked.

I found that I could start a code battle map just by commenting out this line; I'm not sure what other effects this has. (What's a scoreboard?)

**Comment by krzys-h** [comment]
Scoreboard was implemented for a competition that was hosted by Motorola Solutions a few months ago, and it looks like we somehow managed to release it with normal code battles being broken.
