### ISSUE TITLE
After save and load not all ants keep running their scripts

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#1026]
I just built colobot (release build) from a fresh dev (0de347d430106ac3bf9df005aedb826076255e44) on Linux Mint 18.2 / amd64.
It seems that after saving and loading the game, some/most ants stop their script, e.g. not moving, not attacking. I zipped the savegame, and attached it.
[save1708122356Tropica3.zip](https://github.com/colobot/colobot/files/1220116/save1708122356Tropica3.zip)
Update: if I load the game right after starting colobot by Missions -> Load then all the 4 nearby ants are working correcly, but after that if I press Esc and Load to load this saved game again, then 3 or 4 of these ants will not run their scripts (just stand still).

**Comment by Arano-kai** [comment]
Confirm for 0.1.10 (Debian stretch), but can't find reproduce pattern: sometimes this happen on save/load, sometimes - on long play...
Other aliens also affected.

**Comment by attila123** [comment]
@Arano-kai thanks for the confirmation. It's strange that my reproduce pattern did not work for you. It worked for me.

**Comment by tomangelo2** [comment]
I've changed errmode in ants scripts from 0 to 1, after load game they stops with "Illegal object" error on few ants.
