### ISSUE TITLE
Crash with: "GetCharacter: not implemented!"

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#1027]
Yesterday I built colobot (release build) from a then fresh dev (0de347d) on Linux Mint 18.2 / amd64.
On the level "This is time for a sharp exit" (or sg like that) when I clicked for the take off of the spaceship, I got the following crash (I include a bit of log before the crash just to make sure):

[INFO]: Start suspend
[WARN]: Creating non-power-of-2 texture (400x225)!
[INFO]: Stop suspend
[INFO]: Start suspend
[WARN]: Creating non-power-of-2 texture (400x225)!
[INFO]: Stop suspend
[INFO]: Reseting world on phase change...
[INFO]: Simulation speed = 1.00
[INFO]: Loading level: levels/other/win605.txt
[INFO]: Reseting world on phase change...
[INFO]: Simulation speed = 1.00
[INFO]: Reseting world on phase change...
[INFO]: Simulation speed = 1.00
[INFO]: Loading level: levels/missions/chapter006/level006/scene.txt
[WARN]: This level is using deprecated way of defining win scene. Please remove the win= parameter in EndingFile.
[WARN]: This level is using deprecated way of defining lost scene. Please change the lost= parameter in EndingFile from 0 to "levels/other/lost000.txt".

Unhandled exception occurred!
==============================
Type: std::logic_error
Message: GetCharacter: not implemented!
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version git-dev~r0de347d, but please verify that.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=6 rank=6
==============================

Sorry for inconvenience!

**Comment by krzys-h** [comment]
I couldn't reproduce this. Do you have any more details on what were you doing when this happened? Perhaps a savegame at the moment of the crash?

**Comment by attila123** [comment]
It happened only once. Sorry, I don't have any more clues, so maybe it's best to close it. Closing...
