### ISSUE TITLE
Add 'Open Mods Directory' and 'Open Workshop for search Mods' Buttons

### ISSUE THREAD

**Issue by muzscaly** [colobot/colobot#1033]
I already working on this. See #1005 .

**Comment by tomangelo2** [comment]
What's the point of creating issue for feature that you already work on?

**Comment by DavivaD** [comment]
To not do this "secrectly"...?

**Comment by krzys-h** [comment]
@tomangelo2 And because CONTRIBUTING.md clearly says that you should do so?

**Comment by hexagonrecursion** [comment]
* This appears to have been implemented https://github.com/colobot/colobot/pull/1336
