### ISSUE TITLE
SIGSEGV, segmentation fault

### ISSUE THREAD

**Issue by dotalex** [colobot/colobot#1036]
I have this fault:

SIGSEGV, segmentation fault

You are running official 0.1.9-alpha build.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=9 rank=4

What should I do?

Can I export my Player's data (saved games etc), reinstall Colobot, and import Player? If so how?

Or is it Ubuntu that's at fault?

**Comment by tomangelo2** [comment]
0.1.9 is quite outdated release, current up-to-date one is 0.1.10, it might contain fix for this one (there was some fixes for such crashes). If there is no such version in your repositories then you should check this PPA https://launchpad.net/~odyx/+archive/ubuntu/colobot
Your profile should be saved in ~/.local/share/colobot, so you can just copy and paste this directory if you want to export/import it.
If it won't help, then we'll look further.
