### ISSUE TITLE
Saved game loading dialog breaks if you click open without selecting a file

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#1051]
This happens:
![image](https://user-images.githubusercontent.com/1517255/32990417-6d3acde6-cd29-11e7-8733-2eb6b74bda97.png)

**Comment by RaptorParkowsky** [comment]
Confirm. I guess this button should be grayed out when any save slot isn't selected. The same should happen with "Delete" button, but fortunately this button isn't causing the bug. All other inactive buttons in UI are properly grayed out.

**Comment by B-CE** [comment]
Hello & also confirmed, 
likewise, the shortcut "CTRL+Enter" that closes the editor box must be disabled when the open/save dialog box is active.

No crash then, this dialog box remains open; and the workaround is to redo "CTRL+enter" and "CTRL+o" that reinitialize the open dialog box.

**Comment by hexagonrecursion** [comment]
Fixed by 86dff7396e950df8efd1f2a98888822dd16be7fc (colobot-gold-0.2.0-alpha)
