### ISSUE TITLE
Bumping game speed too high causes SIGABRT, bogus values can be set with the cheat command

### ISSUE THREAD

**Issue by DoMiNeLa10** [colobot/colobot#1057]
Trying to speed up the game (in 0.1.11-alpha) too many times causes it to crash, possibly because of an overflow bug.

The cheat command to set speed can take floating point values such as `NaN` and positive and negative `Infinity`, which can cause the game to hang.

**Comment by krzys-h** [comment]
Yeah, the max speed that can be set with the keys should probably be limited as it used to be, the game gets really unstable with large values.

I don't think the cheat accepting strange values is a huge problem though, it's intended to be a feature mostly for developers overall.

**Comment by immibis** [comment]
I have a patch so that at high game speeds the game runs more physics ticks instead of doing more physics per tick. I was using it to test code battles quickly - would this patch be worth submitting?

**Comment by krzys-h** [comment]
@immibis If it works stable enough than please do. I tried to do it along time ago but it was always either too unstable or running even 3x was overloading the CPU way to much

**Comment by krzys-h** [comment]
#1164
