### ISSUE TITLE
SIGFPE, arithmetic exception while playing chapter 6 mission 2

### ISSUE THREAD

**Issue by bryansee** [colobot/colobot#1060]
I am running on an official 0.11.1-alpha build, and starting chapter 6 and mission 2.

The last started level was: category=missions chapter=6 rank=2, and the game was in phase PHASE_SIMUL (ID=7).

Then, a SIGFPE, arithmetic exception occured when I used two grabber bots grab an energy cell and a titanium at the same time.

**Comment by tomangelo2** [comment]
Does it happen every time, or is it random?
What OS do you have? Do you have 64-bit or 32-bit version of OS and game?

**Comment by krzys-h** [comment]
Unable to reproduce this - please reopen if you manage to cause it again.

**Comment by bryansee** [comment]
On random.
