### ISSUE TITLE
space() function doesn't work properly when within SpaceShip.

### ISSUE THREAD

**Issue by gloowa** [colobot/colobot#1063]
Preamble: i am using newest dev build i could find on compiled.colobot.info (downloaded ~24 hours prior to posting this issue).

Hi, this was my number 1 pet-peeve back when colobot released, originally, and it appears to be there still - `space()` function seems to work pretty well when used on the ground. However, within range of `SpaceShip`, it fails miserably.

Consider following (pseudo)code, for 1st moon mission:

```
repeat 4 times: {
    ore = radar(TitaniumOre, 0, 360, 50, 500);
    goto(ore.position);
    grab();

    goto(space(spaceShip.position, 0, 15, 4));
    drop();
}
```

As i understand, `space()` in above example should return position of empty location that is no more than 15m away from the spaceShip.position and is of minimum radius of 4m. What actually happens is that within each repeat, `space()` returns same location. Worse, that location appears to be exactly the same as spaceShip.position. The program above will fail at 2nd loop repeat with "Space occupied" (or something) messege when the bot tries to `drop()` `TitaniumOre`, because its in the exact same location as 1st time, and tries to drop ontop of 1st `TitaniumOre`.

My guess is that `space()` looks at the ground, not at the actually drivable surfaces, and is unaware of existence of `SpaceShip` and it's ramps and platform.

You can test that by doing for instance:
`goto(space(spaceShip.position, 0, 15, 5));`

and comparing with:
`goto(spaceShip.position);`

In my experiments, both of the above result in bot moving into same spot.

This results in inability to automate even such a simple mission as the 1st one on the moon, without painful and hacky workarounds, that are prone to randomly failing.

There is another issue, somewhat conenct with that:

In my experience, `goto()` is super-unreliable for Winged bots when issued to a bot that is on the `SpaceShip`. It sometimes works, but somethimes:

1) (most often) crashes with "unreachable location" (or equivalent) message
2) (rare) drives the bot into central pillar for few seconds than crashes
3) (legendary-super-rare) blasts off with all the force, to then smash the bot into the `SpaceShip` roof/nose section, bot taking significant hp damage.

I think both of the issues stem from same problem - both ` space()` and `goto()` are not *fully* aware of `SpaceShip` and it's geometry.

Simplest fix would be to "flatten" the `SpaceShip` by changing it's 3d model to something that has the main platform on the ground level (or close to) after it unfolds/opens (which would also fix #818) and also doesn't have the overhanging nose section but that's not gonna happen.

**Comment by gloowa** [comment]
I looked through the code, and it might be worth investigating if using `SearchNearestObject(CObjectManager* objMan, Math::Vector center, CObject* exclu)` from `/src/level/robotmain.cpp` is the best choice for `space()` implementation. As i understand it (and i barely understand C/C++) it makes a 3d search for nearest object, so in effect, an item on the `SpaceShip` platform is "invisible" to it when the distance is small enough - if the radius of desired space is, say, 5m, it's smaller than the height from ground to the item.

Since `SpaceShip` origin is 0,0,0 and platform is ~8m above that, any invocation of `space(SpaceShip.position, rmin, rmax, dist)` will fail to detect anything on `SpaceShip` platform if `dist` is smaller than that ~8m height.

Perhaps a replacement function that only finds nearest object in x,y space, akin to distance2d would help here?

**Comment by gloowa** [comment]
Hi.

4 years later and I think i found a reason and solution.

`CRobotMain::FreeSpace` ( [robotmain.cpp:4122](https://github.com/colobot/colobot/blob/master/src/level/robotmain.cpp#L4122) )
uses `SearchNearestObject` ( [robotmain.cpp:4072](https://github.com/colobot/colobot/blob/master/src/level/robotmain.cpp#L4072) )
to check distances to objects nearby.

This has two problems:

1) In range of `SpaceShip` platform, the distance given by `Math::Distance` will be correct in terms of 3d space but not really correct for the purpose of finding empty space. As i understand the code, the `SearchNearestObject` iterates over all objects and calculates 3d distance to them. This works for all purposes when the drivable surface is the same as terrain surface. But this is not the case within range of `SpaceShip` platforms. `SearchNearestObject` will use terrain height as the y coordinate while the objects on `SpaceShip` platforms will be offset by the platform height. This leads to objects being ignored when searched for empty space is less than platform height.

2) In `SearchNearestObject` there is a special case for `SpaceShip` ( [robotmain.cpp:4090](https://github.com/colobot/colobot/blob/master/src/level/robotmain.cpp#L4090]) ) :
`float dist = Math::Distance(center, oPos) - 80.0f;`
The `- 80.0f` makes it so that any distance closer than `80.0f / g_unit`  will be reported as zero (and therefore NOT free space)
This results in `space()` not being able to find any location to drop objects closer than that distance.

I tested some stuff locally, and to tackle both of the problems, I made following changes.

- created `Math::Distance2d` that ignores the y distance between points, effectively calculates distance between projections of two points onto xz plane.
- created `SearchNearestObject2d` that uses Distance2d
- removed `-80.0f` as a special case for `SpaceShip`
- created `FreeSpace2d` that uses `SearchNearestObject2d`
- made `CScriptFunctions::rSpace` use `FreeSpace2d` instead of current implementation

I've tested some levels and it looks like the solution works. Changing the object search to search and measure distance on xz projection of level allows me to find empty space around `SpaceShip` and drop stuff there, without `space()` returning actual `SpaceShip` position (This is another problem - space() fails silently by retiurning origin position when there is no free space found. I think this should be changed so that the instruction fails with error, like `goto()`, and can be suppressed with `errmode`)

However, this also creates small problem. After this, positions that were ignored previously (near `SpaceShip`) will now be valid. In Bot scripts that earch for build space using `space()` rather than `flatspace()` the found location can now be on the `SpaceShip` platform, which is not suitable build space. But this can be fixed by using `flatspace()` (which is unchanged and still uses 3d space for calculations).

Question to whoever is in charge here:

*Is this even desirable / acceptable?*

If so, i can make a pull request for review.

**Comment by melex750** [comment]
Has anyone tested PR #1507, btw?

**Comment by gloowa** [comment]
Huh. I didn't think to check active pull requests.

From the description. it's the same approach as mine.
If i have some time this week I can check that out.

Question - I can see that their changes are branched from dev, shouldn't they be based on master?

**Comment by gloowa** [comment]
space() finds "free space" in that central column because of the 3rd problem with it - since it returns point, it cannot return null when it finds nothing. And by default it returns origin of search in such case, failing silently. so if you search space(radar(SpaceShip).position)) it will return space ship position.

https://github.com/colobot/colobot/blob/master/src/script/scriptfunc.cpp#L1829
https://github.com/colobot/colobot/blob/master/src/level/robotmain.cpp#L4215

This is also something that should be resolved imo.

**Comment by MarcosMD09** [comment]
See #1529. It's solved by @tomangelo2 .

**Comment by tomangelo2** [comment]
Actually it's fixed by @tomaszkax86, I've only fixed compilation for the compiler I use.

**Comment by MarcosMD09** [comment]
> Actually it's fixed by @tomaszkax86, I've only fixed compilation for the compiler I use.

Ok

**Comment by MarcosMD09** [comment]
Please close this Issue
