### ISSUE TITLE
Discharged power cells get their energy level -1 instead of 0 after reloading saved game

### ISSUE THREAD

**Issue by rbcat** [colobot/colobot#1068]
When a power cell (PowerCell or NuclearCell) in a level has it's energyLevel being 0.0 (no energy absolutely) and you save your game, then after reloading that save it becomes charged to -1. It appeared in Colobot Gold Edition, because it was not present in original Colobot aka Colobot Classic.

**Comment by tomangelo2** [comment]
Confirmed, also it only happen for cells laying on ground, cells in robots doesn't behave in such way.

**Comment by Droog71** [comment]
This doesn't seem to be happening after this https://github.com/colobot/colobot/pull/1332 change because a power cell with a value of -1 is now corrected to zero when the object is created.
