### ISSUE TITLE
PowerStation and ResearchCenter drop energy levels of overcharged power cells

### ISSUE THREAD

**Issue by rbcat** [colobot/colobot#1072]
When power cells with too great energy level values contact with PowerStation or ResearchCenter (due to automatic recharging or activated researching respectively), they instantly drop their energy level to 1 even if it was like 999 before.

Power cells with energy levels below 0, however, still have to go all the way from -1 to 1 during recharging, including -1 to 0 diapason.

Note: it is really possible to create energy cells with such energy levels in scene.txt with power=999 or with something like "produce(PowerCell,999)" in the game itself

**Comment by krzys-h** [comment]
I wouldn't consider that a bug, we should instead just block you from creating overcharged cells...

**Comment by krzys-h** [comment]
Overcharged power cells should really not ever exist, so closing this. See #1163.
