### ISSUE TITLE
Mine and TNT do not explode when flying objects are trying to land on them

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#1074]
Mine as well as TNT will not react and explode when you will try to land a flying bot or AlienWasp onto it _strictly_ vertically.

**Comment by ixPost** [comment]
The same sort of thing happens when you quickly descend on a building -- you and the building don't get hurt.

**Comment by hexagonrecursion** [comment]
I tested this with mines and with target bots. Sometimes the explosion happens and sometimes nothing happens.

**Comment by hexagonrecursion** [comment]
Found the problem:

https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/physics/physics.cpp#L2583

The collision force that we use to decide whether the mine should explode is calculated based on the forward/backward linear velocity (m_linMotion.realSpeed.x). If this is zero, no explosion. This does not take into account the up/down component of linear velocity (m_linMotion.realSpeed.y).
