### ISSUE TITLE
Worm's virus does not do anything

### ISSUE THREAD

**Issue by rbcat** [colobot/colobot#1080]
Infected bots are still able to operate and even both start or continue executing their programs as if nothing happened!

**Comment by AbigailBuccaneer** [comment]
Viruses affect the source code of a program by making [these substitutions](https://github.com/colobot/colobot/blob/master/src/script/script.cpp#L776-L786).

You can test it for yourself: with the program `while(true){}`, eventually the program will terminate, and its contents will be replaced with `while(false){}`.

**Comment by rbcat** [comment]
Honestly speaking, this is too weak. I'd mess up a lot more of stuff than just that.
