### ISSUE TITLE
Increased time speed messes up execution of motor() and wait() instructions within cycle

### ISSUE THREAD

**Issue by rbcat** [colobot/colobot#1086]
Situation as follows:
1. For example, an object (bot or insect) at x=0,y=0 wants to face object "p" at x=0,y=-10 as it looks opposite direction.
2. It uses motor(a,b) to face position of p with a and b depending on direction(p.position), so that it will slow down as necessary.
3. There is tolerance for very small direction(p.position) value, whether positive or negative, i.e. object will stop turning if it became really small.
4. Program works in cycle (like while(true){stuff}) and there is delay at the end of cycle, like wait(0.5).

It should work normally when your game time speed is average or less. But when you set speed of game time to greater values, for one, 8.0 or more, said object executing this program will not stop spinning around desperately trying to face position of p.

P.S. Probably related to #970?

**Comment by krzys-h** [comment]
#1164
