### ISSUE TITLE
Defense tower misses past moving enemies

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#1088]
Defense tower misses past moving enemies. These might be wasps or even ants and spiders moving down the steep slope. Sometimes it becomes very dangerous.

Defense tower takes position of enemy, plays animation throughout 1 second and shoot at that position. But enemy, which is actively moving, changes it's position during that 1 second and position taken by defense tower becomes somewhat obsolete.

There can be two different solutions implemented, one is better than another:
1. Perfect. Make defense tower correct it's aim according to targeted enemy's current position throughout all the process until shooting is done or enemy is dead. This solution will leave no chances to enemy.
2. Fine too. Make defense tower take velocity and direction of movement of targeted enemy into account when choosing where to shoot. With this solution there still can be probability of DefenseTower missing, because enemy also can change direction of it's movement.

Was such imperfection supposed to be? I think not. In satcom it's clearly stated:

> The tower constitutes the best defense against enemy attacks, whether they originate on the ground or from the skies.

But it doesn't appears to be the best. Often I rely on some wheeled shooter rather than defense tower, knowing that, unlike defense tower, properly programmed shooter will hit enemy with 100% probability. 

Plus, I can program a shooter to shoot in advance, **before** enemy comes within shooting range, while defense tower only **begins** to react when enemy is within shooting range, which gives some ant time to strike once before death.

**Comment by tomangelo2** [comment]
There was some leftovers in code IIRC about researchable improvement for DefenseTowers in terms of aiming, probably DefenseTowers was actually meant to be imperfect at first, then after some time they could be upgraded by research program.
Maybe we'll return to this idea at some point in redesigning levels.

**Comment by rbcat** [comment]
> Maybe we'll return to this idea at some point in redesigning levels.
I see no real purpose behind this idea and, as I believe, neither did Epsitec devs, so they scrapped it. For now, at least, I personally think that it'll be better to made the tower perfect at aiming by default.

**Comment by tomangelo2** [comment]
They also scrapped perfect aiming. We'll check different options while redesigning these levels.
