### ISSUE TITLE
Make flying objects able to fly regardless of status of research on jet engines

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#1093]
1. If you control a wasp manually and jet engines are not researched in current level, you are not able to make it fly. If it's in the air when you take control over it it drops down instantly.
2. If you find a winged bot you're unable to make it fly as well, even though it was created before you and by logic should already be supplied with necessary technologies.

I propose to make all the objects that are supposed to fly able to fly regardless of status of research on jet engines. Only Me (astronaut) should be in exceptions, because he always has visible jet engine as a part of it's suit. With that, only astronaut's jet engine and your ability to construct new bots supplied with jet engines will depend on this research.

**Comment by hexagonrecursion** [comment]
Amusingly: scripts can make flying objects and wasps fly regardless of research
