### ISSUE TITLE
What if to make sparks of organic balls dropped by wasps corrosive?

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#1097]
Sometimes AlienWasp misses when it tries to bombard an object with organic ball. In that case there are lots of particles, and they look much like AlienAnt's spit. But unlike those of AlienAnt's spit these particles deal no damage, even though in level "Analysis" it is stated that organic matter is produced by ants, which means that it has the very same chemical compound that damages bots and buildings, but in **concentrated** form, which should mean even **more** damage than that of a single AlienAnt's spit.

I propose to do these things:
1. When dropped organic ball explodes it should make it's particles damage all what they fall on and even more destructively, although, perhaps, not as much as particles of AlienSpider's explosion.
2. Make organic ball explode and create these particles even when it's being dropped on an object like a building, a bot or another insect. Because, seriously, where do all that stuff goes in that case? It can't just disappear just because it fell on an object instead of ground.
3. Also, why only ants, spiders and worms are affected by dropped organic ball while other wasps are not? I think wasps themselves should be vulnerable to it too.

**Comment by ixPost** [comment]
Actually the ants don't have to be by the nest for organic matter to form.
