### ISSUE TITLE
Astronaut should be damaged differently than it currently is

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#1099]
Not only when being damaged by enemy's projectile, but also when running into an obstacle on high speed or when it falls on the ground due to it's jet engine being overheated, Me (astronaut) spills blood, a lot of it. No limbs are broken and nothing else happens, just blood spilling like fountain out of blue and shield bar that restores even after astronaut was damaged to a state near death. It all looks absolutely weird and odd for me, in all my honesty.

I propose to remake it like that:
1. Instead of blood there should be black smoke and instead of "ouch!" there should be "bam!", just like when a bot or a building is being damaged, because it is his space suit being damaged and not he himself.
2. No restoration. Astronaut has large enough amount of shield level to survive throughout any of missions even without it and even if you play poorly. It is not necessary AND it makes no sense in neither of these two cases, whether it is astronaut himself being damaged or his suit takes the damage.
3. When a bot runs into an astronaut or especially another astronaut runs into an astronaut no "oumch!" sound should play.

**Comment by B-CE** [comment]
my opinion:
Why not for 1 &3.
I disagree for second point, or it could be just a bit slower; but it's not the goal of disgusting the youngest...

**Comment by RaptorParkowsky** [comment]
Blood in this game is only symbolic representation of the damage. It looks and works "somewhat magic", but well. All old games had such odd solutions and in my opinion there's nothing wrong with it.

This game possibly never going to be more realistic than like it is right now. At least as far as aesthetics of the game won't collide with other aspects.

**Comment by rbcat** [comment]
Well, even then, I would at least add it as an option, I mean 1st and 3rd points, because they are aesthetical.

**Comment by SirElismyer** [comment]
Why couldn't you, if you were going to go with point 2, make the Astronaut repair in a repair center, just like bot? You could even explain it in the level where you introduce the repair center (I don't recall where that happens specifically)- "Ouch, that landing was a little rough. Make sure you build a repair center as soon as possible to repair your suit and any bots that might be damaged." The level would start with him at 10% health.

**Comment by ixPost** [comment]
I think the astronaut make a "bam!" & "ouch!" sound.
