### ISSUE TITLE
Make exterminated AlienSpider explode with red igniting particles?

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#1103]
Let's make spiders explode with red particles that ignite all what they fall on and with that loud "bwooeem!" sound instead of exploding with regular green particles and instead of burning and running around, whether these spiders were exterminated by a defense tower, a fireball shooter, an orga shooter, a thumper, a mine or even lava. Implementing that will make spider's death look more sensible and it will make spiders a little bit more dangerous.

**Comment by ixPost** [comment]
Yes and have spiders make webs.
