### ISSUE TITLE
A lot of text in editor cause FPS drop

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1104]
Noticed when investigating issue #1065 
![lorem_pusto](https://user-images.githubusercontent.com/4140449/35767970-7dc42858-08f5-11e8-8419-358d64fb652f.png)
![lorem_pelno](https://user-images.githubusercontent.com/4140449/35768060-a13347fa-08f6-11e8-987b-e276c40964b4.png)

Resizing editor window helps a bit, it looks like rendering text is heavier than rendering 3D world in the background. It occurs on all graphic engines.

**Comment by RaptorParkowsky** [comment]
It works well on my computer until I minimize the font to the smallest size possible. From stable 60 fps it drops to 30fps or lower.

**Comment by tomangelo2** [comment]
Do you have enabled VSync, or another FPS limiter?

**Comment by RaptorParkowsky** [comment]
I don't think so. My GeForce GTX 750 Ti just doesn't render more than 60fps in any game. My monitors doesn't support any VSync technologies I guess.

**Comment by tomangelo2** [comment]
I think you have enabled VSync globally in Nvidia Control Panel. GTX 750Ti isn't fastest card in the world, but it shouldn't be slow enough to display >60 fps in Colobot. And basic VSync should work on all displays.
Of course you don't need to disable it globally, there are reasons why GPU don't need to work on 100% power all the time, pointing it just in case.

**Comment by RaptorParkowsky** [comment]
It's just default auto settings depends of 3D application. When I switched it off, GOLD rendered ~150-300 or ~700fps in menu. But I can't see those frames on my monitors, because they're all 60-75Hz. This is overkill and I doubt it have anything to do with this issue. Framedrops are the same with or without this feature.

![schowek01](https://user-images.githubusercontent.com/4019345/37297897-2a82cea0-261f-11e8-87f3-7564292bcb45.png)

**Comment by tomaszkax86** [comment]
OpenGL devices have DrawPrimitives() methods which use glMultiDrawArrays(). With DrawPrimitives() you can render multiple characters as triangle fans with a single draw call, as long as they are all in one texture. This is almost the same as using quads, except that quads are not supported in OpenGL 3.3. I added it to speed things up but I never got to rewriting text renderer.
