### ISSUE TITLE
Crystallium had TWO different atmospheres in Classic; Gold Edition have lost it

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#1106]
Those who played Colobot Classic might still remember that atmospheres in levels 4-1 and 4-2 and in levels 4-3 and 4-4 were quite different. Information about atmosphere was contained in each level's scene.txt and when in Colobot Gold Edition it was all moved to planet.txt common for all the level's within each chapter, levels 4-3 and 4-4 have lost their "foggy" atmosphere (color is different, sky is all foggy and no stars) and took standart atmosphere of Crystallium instead.

That's not very good. I liked these levels aesthetically more when they were foggy. It was naturally their "shtick", creating quite anxious atmosphere and symbolizing just how dangerous missions on the very same planet can get. Please, revert it back.

I found few pictures in the internet, that's one of them, which was obviously taken from the old Colobot:
![thelostvalley.jpg](https://user-images.githubusercontent.com/36084544/35770584-e52a7886-093f-11e8-88cd-c24f621e315f.jpg)

<h5>Also, a word about music.</h5>

In Colobot Classic there was no music at all and thus, nothing to talk about. Now we do have music, but it feels like "music004.ogg" is too peaceful and doesn't fit into anxious atmosphere of levels 4-3 and 4-4 too fine. Maybe there should be a different version of ambient soundtrack, based on "music004.ogg", but made specifically for foggy levels like 4-3 and 4-4?

For example, I myself made one, by mixing "music004.ogg" with "music007.ogg", when I wanted such ambient soundtrack for foggy Crystallium levels in my usermod, and it seemed to be fine...

**Comment by tomangelo2** [comment]
In Colobot Classic there was music, you needed an original CD with game to make it works, otherwise there was no music (including editions from game magazines). I'm not sure, but most of in-game music comes from original game, you just don't need game disc for that.

**Comment by rbcat** [comment]
That's some strange case, my CD with game was sure bought in the store. Maybe it was removed by the company that localized the game... I believe, you're right, giving that the author of it was a part of Epsitec team.
