### ISSUE TITLE
Make titanium ore not destructible by ants balls

### ISSUE THREAD

**Issue by rbcat** [colobot/colobot#1112]
Pretty please.

**Comment by krzys-h** [comment]
In original Colobot, TitaniumOre and UraniumOre are not destroyable but Titanium, PowerCell and NuclearCell are and I believe it was intended to be that way.

**Comment by rbcat** [comment]
@krzys-h, your message makes not much sense in the current context. I mean, yes, it is intended to be that way, but it is not anymore since one of Colobot Gold updates. Object damaging system is really messed up.

In later Colobot Gold versions titanium ore can be actually destroyed by a fire ball or an acidic ball which was not happening in Colobot Classic and older Colobot Gold versions, because the only way to do that was to hit it with a bot.

Now everything will destroy titanium ore.

In case of fireball shooter, it removes necessity to work with a grabber in level 6-1 "Transport" of original storyline, in order to clean the way of titanium ore, which means less work to do, but it is not too critical.
When you try to steal some titanium ore from ants or spiders and they shoot at you, they always destroy all or almost all titanium ore that you are looking for. And this is what I find to be truly bad.

Maybe it is a good idea to prevent ants, spiders, wasps, poisonous mushrooms and orga shooters from destroying titanium ore chunks?

Another little thing is that when poisonous mushrooms shoot their acidic balls these balls hit uranium ore. It is not being destroyed, but there is sound and black smoke, which seems a little bit awkward.

**Comment by krzys-h** [comment]
@rbcat oh, I misread your issue as Titanium instead of TitaniumOre. In that case, it was fixed recently in 1d09ee9b3c3497b03a78c2e4b32bb13b5ad32b33 and already released in 0.1.11.1.

**Comment by rbcat** [comment]
Oh, that's good. I'll wait for when it will appear in debian stretch backports repo.
