### ISSUE TITLE
Fast forwarding makes the instructions execute poorly

### ISSUE THREAD

**Issue by Bearsomez** [colobot/colobot#1119]
It seems that instructions which work well in x1 time mode produce random results on multipliers higher than x2, and there's a higher chance that they'll won't work properly the higher the time multiplier is.

**Comment by B-CE** [comment]
true,  like if some tests and checks are strapped in "high speed"...

**Comment by immibis** [comment]
I think it's about the physics engine rather than the instructions. It executes the same amount of physics ticks but it moves things twice as far in each tick, so it gets less accurate (e.g. higher chance of shooting past your destination in one tick).

**Comment by B-CE** [comment]
May "turn" and "goto" function have to be improve :
often, in x8 or more, the bot seams locked (continuously turning till it's battery empty or calculating the way)
The workaround consist to  decrease the speed to 2 or 1 for "unlocking".

In battle mode, it's critic also for "move" function: most of the existing program miss their goal and wait indefinitely for a material impossible transformation.
The flights are nightmare too, crashing on own buildings, on derrick or more often into water.

( tip to tweak your program: if the enemy has its flying robots annoying you: just increase the speed, and they will certainly explode in the water quickly - Its landing may also auto-lock ... up to you not being like them .... Watchdog :1st_place_medal: being the first step for resiliency. ^^  )

**Comment by B-CE** [comment]
maybe related to #1086 , #970, #939, ...
( mad wheels, half and full wheels disappearing also confirmed with 1.11)

**Comment by krzys-h** [comment]
#1164
