### ISSUE TITLE
Some dependencies are wrongly treated by CMake as optional instead of required

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#1132]
Instead of emitting missing library errors like all the others do, they fail with an error like this:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLEW_INCLUDE_PATH
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
GLEW_LIBRARY
    linked by target "colobot" in directory /home/krzys_h/colobot/src
PHYSFS_INCLUDE_PATH
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
   used as include directory in directory /home/krzys_h/colobot/src
PHYSFS_LIBRARY
    linked by target "colobot" in directory /home/krzys_h/colobot/src
```

**Comment by hexagonrecursion** [comment]
I have managed to reproduce this on colobot-gold-0.1.11-alpha.

We did have `find_package(GLEW REQUIRED)`, but we were using our own `FindGLEW.cmake`

https://github.com/colobot/colobot/blob/b5cc7689d1a8f9e6396454c70e819e10536a154a/CMakeLists.txt#L261

It turns out that it is the responsibility of the find module to "[issue a FATAL_ERROR if the package cannot be found](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules)"

Our find module was not doing that. 

https://github.com/colobot/colobot/commit/7d7d88cbb136cab9d12e8ee14559b49d90e328bc removed FindGLEW.cmake fixing half of the issue

**Comment by hexagonrecursion** [comment]
It looks like the command that is usually responsible for issuing the FATAL_ERROR is find_package_handle_standard_args

The following files have the command and are *probably* fine:

* cmake/FindFLAC.cmake
* cmake/FindOgg.cmake
* cmake/FindOpus.cmake
* cmake/FindSDL2.cmake
* cmake/FindSDL2_image.cmake
* cmake/FindSDL2_ttf.cmake
* cmake/FindSndFile.cmake
* cmake/FindVorbis.cmake
* cmake/FindVorbisEnc.cmake

The following file still has the bug:

* cmake/FindPhysFS.cmake

**Comment by hexagonrecursion** [comment]
> The following files have the command and are _probably_ fine:
> 
>     * cmake/FindFLAC.cmake
> 
>     * cmake/FindOgg.cmake
> 
>     * cmake/FindOpus.cmake
> 
>     * cmake/FindSDL2.cmake
> 
>     * cmake/FindSDL2_image.cmake
> 
>     * cmake/FindSDL2_ttf.cmake
> 
>     * cmake/FindSndFile.cmake
> 
>     * cmake/FindVorbis.cmake
> 
>     * cmake/FindVorbisEnc.cmake

confirmed: they are indeed fine

**Comment by hexagonrecursion** [comment]
For posterity: the error message caused by the bug is now different from the one in the original post:
```
CMake Error at colobot-base/CMakeLists.txt:16 (target_link_libraries):
  Target "Colobot-Base" links to:

    PhysFS::PhysFS

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
