### ISSUE TITLE
Story consistency: why many spaceship relicts?

### ISSUE THREAD

**Issue by TronFortyTwo** [colobot/colobot#1133]
In many levels, following the path of the previous expedition, you find relicts and traces of it, this is a wonderful idea! Sometimes you even find a starship relict, but this makes no sense to me. Since the two missions are similar or even almost identical(Similar equipment, similar starship,...) I suppose that the other mission too had just one spaceship. If I find the spaceship relict somewhere then, I suppose that is the end of the previous mission, but that's not true, since you'll find heavily damaged spaceships in later missions. I suggest or to explain better the situation, or to replace the spaceship wreckages with other ruins.

**Comment by rbcat** [comment]
I've always used to think that there were many of those expeditions. Sending just one robotic expedition makes no sense to me, especially given that there are always some errors and failures occuring with automatized systems of such complexity.

In general, pouring wheeze into the original game story in any way is most certainly _not_ going to happen when it comes to Colobot, IMO.

**Comment by TronFortyTwo** [comment]
The first mission Houston Mission Control states: "Eight months ago an expedition composed entirely of robots was sent[...]" This mean there was only one expedition, only one spaceship. Maybe yes, it was a bad idea (in fact they lost communication), but this is what happened.

**Comment by RaptorParkowsky** [comment]
I've always assumed that First Expedition just splitted into several automated teams on the Moon and they just tried to conquer the Space in diffused way by building another SpaceShip and send some bots further.

Anyway, that's rather good topic for potential prequel of the game. But GitHub isn't a good tool for development of the story and lore about this franchise. That's why there's no other opened issues like that - GitHub should stay technical-only.

**Comment by TronFortyTwo** [comment]
Oh i see. Thanks for your answers :)

**Comment by ixPost** [comment]
> I've always assumed that First Expedition just splitted into several automated teams on the Moon and they just tried to conquer the Space in diffused way by building another SpaceShip and send some bots further.
> 
> Anyway, that's rather good topic for potential prequel of the game. But GitHub isn't a good tool for development of the story and lore about this franchise. That's why there's no other opened issues like that - GitHub should stay technical-only.

Where should we talk about it then?
