### ISSUE TITLE
Mac OS X - Problems with override

### ISSUE THREAD

**Issue by ptiza-v-nebe** [colobot/colobot#1135]
The latest master has an issue with compiling on mac os 10.12.6 with XCode Command Line Tools version: 9.0.1.0.1.1506734476

If you try to build you get this error:
`/Users/xxx/Downloads/colobot/src/object/old_object.h:240:17: error: 
      'SetDamaging' overrides a member function but is not marked 'override'
      [-Werror,-Winconsistent-missing-override]
    void        SetDamaging(bool damaging);
                ^
`

A little bit googling:
`You need to turn off the -Winconsistent-missing-override flag which automatically gets added with -Wall on recent versions of clang. You can do this by passing the -Wno-inconsistent-missing-override flag. See.` [Source](https://stackoverflow.com/questions/32626171/xcode-7-how-to-suppress-warning-overrides-a-member-function-but-is-not-marked/32627021)

Resolved with this:

Go to CMakeLists.txt in main folder.

After `elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")` find `set(NORMAL_CXX_FLAGS "-std=c++11 -Wall -Werror -Wold-style-cast -pedantic-errors")` in Clang area.

And add after `-Wall` the flag `-Wno-inconsistent-missing-override`

So it results in:
`set(NORMAL_CXX_FLAGS "-std=c++11 -Wall -Wno-inconsistent-missing-override -Werror -Wold-style-cast -pedantic-errors")`

**Comment by Erihel** [comment]
It just misses one **override** keyword. There's a PR for this #1114
