### ISSUE TITLE
Generated CBot VS-project doesn't have path to Boost headers in its properties

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#1157]
I've generated the projects to be built with VS2017, and encountered several compile-time issues with them.
`
...\colobot\src\cbot\cbotdebug.cpp(29): fatal error C1083: Cannot open include file: 'boost/algorithm/string/replace.hpp': No such file or directory
`
There is no path to `boost` in `Additional Include Directories`...
See also #1158 

---
Adding a line `include_directories(SYSTEM ${Boost_INCLUDE_DIRS})` into `...\colobot\src\CBot\CMakeLists.txt` right after `include_directories(${LOCAL_INCLUDES})` solves the problem :)

**Comment by MrSimbax** [comment]
I think it should be fixed in abb7d54ef5d88818030f18b9e187a1067f6c5a52 . Could you confirm?

**Comment by pwallrich** [comment]
I'm also having the same problem on mac, trying to build the master branch

**Comment by LZaruba** [comment]
Same issue here on mac with latest master
`.......colobot/src/CBot/CBotDebug.cpp:29:10: fatal error: 'boost/algorithm/string/replace.hpp' file not found
#include <boost/algorithm/string/replace.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CBot/CMakeFiles/CBot.dir/CBotDebug.cpp.o] Error 1
make[1]: *** [src/CBot/CMakeFiles/CBot.dir/all] Error 2
make: *** [all] Error 2`

**Comment by MrSimbax** [comment]
Try `dev` branch.

**Comment by LZaruba** [comment]
Hi, dev branch works fine. Thanks
