### ISSUE TITLE
SDL2main cannot be found by CMake in some cases

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#1159]
The custom CMake module `FindSDL2.cmake` in some environments (Windows, `SDL2-2.0.5`) cannot find `SDL2main.lib`, so you get link-time errors (about missing entry point `main`).
Here is the fragment from `FindSDL2.cmake`:
```
		FIND_LIBRARY(SDL2MAIN_LIBRARY
			NAMES SDL2main
			HINTS
			$ENV{SDL2DIR}
			PATH_SUFFIXES lib64 lib
			PATHS ${SDL2_SEARCH_PATHS}
		)
```
The specified path suffixes are "incompatible" with standard layout for `SDL2-2.0.5` which stores libraries in `lib\x86` and `lib\x64`.

---
It makes sense to introduce an extra variable `${SDL2LIB_PATH_SUFFIX}` in CMake to hold platform-specific suffixes:
```
# Lookup the 64 bit libs on x64
IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(SDL2LIB_PATH_SUFFIX lib64 lib/x64)
# On 32bit build find the 32bit libs
ELSE(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(SDL2LIB_PATH_SUFFIX lib lib/x86)
ENDIF(CMAKE_SIZEOF_VOID_P EQUAL 8)
```
With such improvement detection of `SDL2` can be simplifies a bit:
```
FIND_LIBRARY(SDL2_LIBRARY_TEMP
	NAMES SDL2
	HINTS
	$ENV{SDL2DIR}
	# HACK: search SDL2 also in lib even for 64-bit?
	PATH_SUFFIXES ${SDL2LIB_PATH_SUFFIX} lib
	PATHS ${SDL2_SEARCH_PATHS}
)
```
I'm not sure why `lib` was used in the old code for 64-bit build, so I would keep it as is...
And detection of `SDL2main` is done in a similar way:
```
		FIND_LIBRARY(SDL2MAIN_LIBRARY
			NAMES SDL2main
			HINTS
			$ENV{SDL2DIR}
			PATH_SUFFIXES ${SDL2LIB_PATH_SUFFIX}
			PATHS ${SDL2_SEARCH_PATHS}
		)
		IF(SDL2MAIN_LIBRARY)
			MESSAGE(STATUS "Found SDL2main: ${SDL2MAIN_LIBRARY}")
		ENDIF (SDL2MAIN_LIBRARY)
```
The changed file `FindSDL2.cmake` is attached (as ZIP-archive).
[FindSDL2.cmake.zip](https://github.com/colobot/colobot/files/1976649/FindSDL2.cmake.zip)

**Comment by Anton-V-K** [comment]
This issue is still not fixed, thus making it hard to build colobot on Windows with cmake :(

**Comment by hexagonrecursion** [comment]
> This issue seems to be partially resolved on the dev branch

The warning about find_package_handle_standard_args is unrelated to the original bug. Closing this as fixed
