### ISSUE TITLE
Prevent creation of overcharged PowerCells

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#1163]
in produce() and scene files

**Comment by rbcat** [comment]
You're just sweeping it under the rug rather than fixing some actual bugs, aren't ya? OK, OK, I'm not commissioned to tell you what to do...

**Comment by krzys-h** [comment]
If it's not supposed to ever happen, it's not a bug. Having an overcharged PowerCell is like having a string variable "abcd" with a length of 6 - that breaks the invariants that the code assumes to be met. You shouldn't be suprised if the function `get_half_of_string(s)` returns "abc", the bug is not in that function, the bug is that such a weird string is allowed to exist.

**Comment by rbcat** [comment]
Your example with a string is an example of absolute heresy while our case is a mere code imperfection.
> that breaks the invariants that the code assumes to be met
Nowadays you should write functions with as less assumptions as it is possible, and, having such concern on the background, these three functions with their childish imperfections look especially rough and silly, don't they? Colobot, however, is an old enough game coming from the times when a lot of stuff was different, if not polar opposite, thus I will agree with your point nevertheless.

Somebody might want to eventually make a refactoring on them, though....

**Comment by krzys-h** [comment]
If you want to make a power cell that has more charge, we'd have to change the capacity parameter (yes there is such a thing in the code, just not externally accessible), NOT overcharge it. Letting the battery have >100% charge in any form is a bug.
