### ISSUE TITLE
Unhandled exception occured! Linux Mint

### ISSUE THREAD

**Issue by LeonardGC** [colobot/colobot#1170]
I had just installed the game, changed some settings and finished the first mission.

When I started the 2nd mission I had to press F1 to see the instructions. Then the crass happened.

Message:
Unhandled exception occured!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version 0.1.6-alpha, but please verify that.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=1 rank=2
==============================

Sorry for inconvenience!

**Comment by tomangelo2** [comment]
0.1.6 is very old version, it was released 2 years ago. 
You may want to install current up-to-date 0.1.11.1 release from https://launchpad.net/ubuntu/+source/colobot

**Comment by LeonardGC** [comment]
Thanks

**Comment by krzys-h** [comment]
@le

**Comment by krzys-h** [comment]
@LeonardGC did that fix your issue?

**Comment by LeonardGC** [comment]
Yes it did fix the issue.
Thanks for the help!

Op zo 5 aug. 2018 23:05 schreef krzys_h <notifications@github.com>:
