### ISSUE TITLE
dbus[3859]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362

### ISSUE THREAD

**Issue by timblack1** [colobot/colobot#1178]
I'm getting the following error on Ubuntu 18.04 32 bit:

---------

$ colobot
[INFO]: Colobot: Gold Edition 0.1.11-alpha starting
[INFO]: Creating CApplication
[INFO]: Data path: /usr/share/games/colobot
[INFO]: Save path: /home/tim/.local/share/colobot
[ERROR]: Error on parsing config file: failed to open file
[WARN]: Config could not be loaded. Default values will be used!
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
dbus[3859]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace

Unhandled exception occurred!
==============================
SIGABRT, abort
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You are running official 0.1.11-alpha build.

CRobotMain instance does not seem to exist
==============================

Sorry for inconvenience!
Gtk-Message: 17:04:48.441: GtkDialog mapped without a transient parent. This is discouraged.
AL lib: (EE) alc_cleanup: 1 device not closed

---------

Any idea how to fix this?

**Comment by krzys-h** [comment]
This seens to be a bug in Ubuntu 18.04 build of SDL library rather than Colobot. Please see https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1775067

**Comment by krzys-h** [comment]
@timblack1

>>> Can you please try with libsdl2 in -proposed pocket? and update
https://bugs.launchpad.net/bugs/1772471 if you still have this issue

(from https://bugs.launchpad.net/bugs/1775067)
