### ISSUE TITLE
How am I supposed to get a charged PowerCell from PowerPlant?

### ISSUE THREAD

**Issue by Nakilon** [colobot/colobot#1187]
```
object load_titanium(int c) {
	object o;
	while (null == (o = radar(Titanium))) wait(1);
	goto(o.position);
	grab();
	o = radar(c);
	goto(o.position);
	drop();
	return o;
}

object load_powercell(int c) {
	load_titanium(PowerPlant);
	object o;
	while (null == (o = radar(PowerCell))) wait(1);
	grab();
	o = radar(c);
	goto(o.position);
	drop();
	return o;
}
```
After I call `load_powercell()` it brings Titanium to PowerPlant but hangs in `while(null == (o = radar(PowerCell))) wait(1);` even after the message that it's complete. Like it can't `radar()` the PowerCell that is inside the PowerPlant. Am I supposed to ask PowerPlant somehow if it's loaded with fully charged PowerCell instead?

**Comment by Nakilon** [comment]
Seems like `radar(PowerPlant).energyCell.category` changes to `"PowerCell"` when it's done. Is it the way to go and is it covered by some tutorial that I missed?

**Comment by melex750** [comment]
The radar(); function doesn't find objects that are mounted in battery slot or grabbed.
```c++
object powerPlant = radar(PowerPlant);
while(powerPlant.busy()) wait(1);    <--- wait until PowerPlant is finished

object cell = powerPlant.energyCell;    <--- get pointer for the cell or null

if (cell != null)
{
    goto(powerPlant.position);
    grab();
}
```
