### ISSUE TITLE
Add Travis

### ISSUE THREAD

**Issue by Saibamen** [colobot/colobot#1209]
Please add Travis build

**Comment by Erihel** [comment]
Travis was removed https://github.com/colobot/colobot/commit/736f90955d5da770386f0df30a42a6f32a737c26 not sure why. Maybe because there's jenkins available (or was).

**Comment by MrSimbax** [comment]
We already have Jenkins https://compiled.colobot.info/

**Comment by krzys-h** [comment]
We moved to Jenkins because we kept hitting timeout limits on Travis - Windows builds through MXE were quite slow. Not sure if the limits were raised since.
