### ISSUE TITLE
Unknown error of PhysFS on Windows OS.

### ISSUE THREAD

**Issue by buddookan** [colobot/colobot#1210]
I download : colobot-gold-0.1.11.1-alpha-win64
from:
https://colobot.info/pl/download-colobot-gold/

And when start the game I have this error:
https://uploads.disquscdn.com/images/88a9a734d6d2e9f59480d034f30b61e4ec1930b05b1f04427f1a1c0a73b17e93.jpg

Log:
`[INFO]: Colobot: Gold Edition 0.1.11.1-alpha starting
[ERROR]: Error while initializing physfs: (null)
`

**Comment by Ombrelin** [comment]
Hello, I think this error is related to the fact that PhysFS had issues with windows 1809 (https://icculus.org/pipermail/physfs/2018-October/001273.html).
Since the library was updated to fix this, maybe updating PhysFS's DLL in Colobot would fix this issu.

**Comment by RARM** [comment]
I am having the same issue. How can I update the PhysFs's DLL?

**Comment by krzys-h** [comment]
While the physfs people have prepared a fix, they have not made a stable release since so the only option is compiling physfs from source. We'll probably have to provide our own version soon.

**Comment by Ombrelin** [comment]
Actually somebody on the Colobot discord provided a hotfix which worked in my case. It's just a zip to extract in Colobot's installation directory. 
Thank to this fix I can now run Colobot on my Windows 10 1809

**Comment by tomangelo2** [comment]
https://cdn.discordapp.com/attachments/474693809197023243/544505620984889364/Colobot_Win10_fix.7z
This is compiled from `dev` branch, it contains changes prepared for upcoming release, so it's more than just hotfix.

**Comment by tomangelo2** [comment]
New version is now live, both release and dev builds are patched against this error, so IMHO this issue might be closed.
