### ISSUE TITLE
Black screen on macOS Mojave

### ISSUE THREAD

**Issue by LZaruba** [colobot/colobot#1214]
Hi!
I've compiled from dev branch successfully and ran the game couple of time on macOS 10.13.x with no issues. After upgrading to macOS Mojave 10.14.1 (18B75) when game launches I get only black screen. I am able to use ESC key and click to exit the game and I get sound effects during the black screen.
Is there anything I can do to run the game?
Thanks!
LZ

**Comment by melex750** [comment]
Maybe try ```Fullscreen=0``` in ```colobot.ini```.
You can rename or delete ```colobot.ini``` and the game should re-create it with default settings.
Maybe try to re-compile the game since after upgrading the OS.

A quick web search shows other black screen issues with that version of mac OS.

**Comment by LZaruba** [comment]
Hi, thanks for the tip.
I've tried to re-compile the game on current OS with no success.
I have possibly a stupid question - where should this colobot.ini be located? I can find one in the /desktop folder, but there is none in the compiled .app bundle.
Thank you, LZ

**Comment by melex750** [comment]
I think it might be in ```~/Library/colobot/``` but I can't say for sure because I don't have a mac.

The user Library folder is hidden by default, open it with:
Finder > Go
Select 'Go to Folder...'
Type ```~/Library```
Click the 'Go' button

**Comment by LZaruba** [comment]
Hi, I am happy to confirm that same dmg generate in Dec 2018 now works fine on the same Mac. I assume that issue was fixed by MacOS updates and we can close this bug. Thanks for your support.
