### ISSUE TITLE
Colobot Crash

### ISSUE THREAD

**Issue by YankeeITC** [colobot/colobot#1232]
Unhandled exception occurred!
==============================
Type: CLevelParserException
Message: Command not found: Title
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
Hello,

I keep getting this error when I try to load a previous session.  Any suggestions?  Thanks

==============================
You are running official 0.1.11-alpha build.

The game was in phase PHASE_READ (ID=19)
Last started level was: category=missions chap=0 rank=0
==============================

Sorry for inconvenience!

**Comment by Anton-V-K** [comment]
Seems to be related/similar to #1207
