### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [colobot/colobot#1246]
https://colobot.info/download-colobot-gold/ has an AppImage but it is contained inside an archive.

Please __DO NOT__ put an AppImage into another archive like a `.zip` or `.tar.gz`. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

Reference:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by MrSimbax** [comment]
We didn't do that because the AppImage requires `data` and `lang` folders to work. We have yet to figure out how to embed them inside the AppImage. We'll probably update our download page once we do that.

I personally didn't see any problems with putting it inside archive but I'm more used to Windows way of distributing software and treat AppImage more like a static executable than a container. Thanks for admonishing us though.

**Comment by probonopd** [comment]
Are the data and lang folders changing or do they contain static (non-changing) data?

* If the data is not changing, then you can simply put them inside the AppImage.
* If the data is changing, then it should be copied from the AppImage to somewhere into `$HOME` upon the first launch of the application, and then used from there.

**Comment by MrSimbax** [comment]
They contain static data. We tried putting them inside AppImage but Colobot refuses to load them. I don't know the details as I haven't tried it myself so I'll ping @tomangelo2 here.

**Comment by MrSimbax** [comment]
By the way, should AppImage by default create user-specific save files in the directory it's in or in other directory? Currently they reside in `$XDG_DATA_HOME`. Is there a way to create a directory like `Colobot-x86_64.AppImage.data` for `$XDG_DATA_HOME` like it is possible for `$HOME` (`Colobot-x86_64.AppImage.home`)?

**Comment by probonopd** [comment]
`$XDG_DATA_HOME` is correct. No need to change.

**Comment by tomangelo2** [comment]
I've already created an issue about that https://github.com/colobot/colobot/issues/1245.
The problem is that engine does looks for data and lang directories in folder where AppImage is stored, not inside of directories mounted by AppImage. That's why we couldn't make it to work in proper way. I've made some research, turns out SDL2 might come handy here, if not then there is `binreloc` library to help https://github.com/limbahq/binreloc.

**Comment by probonopd** [comment]
> The problem is that engine does looks for data and lang directories in folder where AppImage is stored, not inside of directories mounted by AppImage.

How are you looking for the relative path?

**Comment by tomangelo2** [comment]
During compilation there is defined constant `COLOBOT_DEFAULT_DATADIR`, which is either full path or `./data`, depends on flag `PORTABLE` in CMake.

**Comment by probonopd** [comment]
https://github.com/limbahq/binreloc is indeed the way to go then.

**Comment by MrSimbax** [comment]
There seems to be another problem with this AppImage. When running `appimaged`:
```
-> REGISTER /home/mattp/bin/Colobot-x86_64.AppImage
squashfs based type 2 AppImage
Got root desktop: colobot.desktop
TODO: Implement inode.base.inode_type 3
Desktop file has no Exec key
```
However, the desktop file has Exec entry. We created the AppImage using [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy) and I noticed the exact same message for `linuxdeploy-x86_64.AppImage`. What's at fault here?

**Comment by MrSimbax** [comment]
I regenerated the AppImage with changes from branch `dev-basedirs`. Please tell if it complies with the standards now. I suspect the issue with the Exec key I mentioned above is not our fault, correct me if I'm wrong.

**Comment by probonopd** [comment]
I suspect it has to do with `TODO: Implement inode.base.inode_type 3`.

What does `appimaged --version` say?

**Comment by MrSimbax** [comment]
`Version: 9~pre.1495805837.d05eac1`

**Comment by probonopd** [comment]
Please use a more recent one. This is working properly for me using

```
me@host:~$ appimaged --version
appimaged, continuous build (commit 3b794f3), build 86 built on 2019-01-18 04:35:47 UTC
```

**Comment by probonopd** [comment]
Unrelated, a couple of minor issues with the desktop file prevent it from passing the test at the moment:

- colobot.desktop: **hint**: value "Education;Robotics;Game;AdventureGame;StrategyGame;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
- **error**: value "robots;3d;space;astronaut;java;c++" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character
- **error**: value "robots;3d;espace;astronaute;cosmonaute;java;c++" for locale string list key "Keywords[fr]" in group "Desktop Entry" does not have a semicolon (';') as trailing character

**Comment by krzys-h** [comment]
They are generated from translation files
https://github.com/colobot/colobot/blob/master/desktop/create_desktop_file.sh
https://github.com/colobot/colobot/blob/master/desktop/po/colobot-desktop.pot
https://github.com/colobot/colobot/blob/master/desktop/po/fr.po

**Comment by probonopd** [comment]
Thanks; can you please add a semicolon (';') as trailing character for `Keywords=` and `Keywords[fr]`?

**Comment by MrSimbax** [comment]
I updated the AppImage with changes from branch `dev-fix-desktop` which should fix the issue with the semicolons.

**Comment by probonopd** [comment]
Can you compile on the oldest still-supported Ubuntu LTS release please, which at this point is trusty? Thanks.

**Comment by MrSimbax** [comment]
Unfortunately, physfs seems to be buggy in this version and returns working directory path instead of base directory path. So I'll have to create another patch.

**Comment by MrSimbax** [comment]
Please try it now.

**Comment by probonopd** [comment]
Thank you. It is working for me now.
