### ISSUE TITLE
SIGSEVV,segmentation fault

### ISSUE THREAD

**Issue by crumblebar** [colobot/colobot#1269]
Left grabber building on crysalis to make coffee and came back so unsure of leadup events.
![30-08-2019 4-53-55 PM](https://user-images.githubusercontent.com/35923985/63999592-2d9ea900-cb47-11e9-9adb-df1bf9b37173.jpg)

**Comment by immibis** [comment]
Unfortunately there is not enough information here to diagnose the problem.

**Comment by MrSimbax** [comment]
I agree. Since we can't reproduce the bug, I'm closing this.
