### ISSUE TITLE
Request: Pls add Fedora to your "has it in it's repo section"

### ISSUE THREAD

**Issue by Cyborgscode** [colobot/colobot#1277]
Fedora offers build versions of colobot over all supported release versions atm : F29-32.

It would be nice, if someone can change the read.me to reflect this. 

Reference: 

https://koji.fedoraproject.org/koji/packageinfo?packageID=27777

**Comment by MrSimbax** [comment]
We didn't know about its existence. I wonder why the package maintainer hasn't contacted us about this. If they did, sorry, we somehow missed it.
