### ISSUE TITLE
Errors in the log file when C:GE is starting.

### ISSUE THREAD

**Issue by CozmoCyke** [colobot/colobot#1282]
Hello ,

System tested : Windows 7

What is the meaning of this Error on parsing in the config file ?

[INFO]: Colobot: Gold Edition 0.1.12-alpha starting
[INFO]: Creating CApplication
[INFO]: Data path: ./data
[INFO]: Save path: ./saves
[INFO]: Mod autoload dirs:
[INFO]:   * ./data/mods
[INFO]:   * ./saves/mods
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
**[INFO]: Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO]: Error on parsing config file: No such node (Experimental.MSAA)
[INFO]: Using Vsync: false
[INFO]: No joysticks detected
[INFO]: Error on parsing config file: No such node (Experimental.GraphicsDevice)**

[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 3.2.9704 Compatibility Profile Context
[INFO]: ATI Mobility Radeon HD 5650
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 16
[INFO]: Multisampling supported, max samples: 8
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 8
[INFO]: Maximum texture size: 16384
[INFO]: Framebuffer supported (ARB)
[INFO]: Maximum renderbuffer size: 16384
[INFO]: CDevice created successfully
[WARN]: Error on parsing fonts config file: failed to open file
[INFO]: Closing joystick
[WARN]: Failed to update locale, possibly incorect system configuration. Will fa
llback to classic locale.
[INFO]: Created shadow map texture: 1024x1024, depth 32

What does it means :  
I have no problem with French version : why does it mention a locale problem ? What is the meaning of "classic locale" ?

**Comment by tomangelo2** [comment]
These *errors* only indicates you haven't set optional config lines. They aren't really important, default values are set instead, this is why they're marked as [INFO] instead of {ERROR].
I'm not sure about local warning, but since it does set French version, it probably mean that game used another mechanism to set language.
