### ISSUE TITLE
PHYSFS errors when a level is charging.

### ISSUE THREAD

**Issue by CozmoCyke** [colobot/colobot#1283]
What is the meaning of all these PHYSFS errors ?

System tested : Windows 7

[INFO]: Loading level: levels/exercises/chapter011/level001/scene.txt
**[ERROR]: Error opening file with PHYSFS: "textures/shadow00.png"
[ERROR]: Couldn't load texture 'textures/shadow00.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow01.png"
[ERROR]: Couldn't load texture 'textures/shadow01.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow02.png"
[ERROR]: Couldn't load texture 'textures/shadow02.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow03.png"
[ERROR]: Couldn't load texture 'textures/shadow03.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow04.png"
[ERROR]: Couldn't load texture 'textures/shadow04.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow05.png"
[ERROR]: Couldn't load texture 'textures/shadow05.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow06.png"
[ERROR]: Couldn't load texture 'textures/shadow06.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow07.png"
[ERROR]: Couldn't load texture 'textures/shadow07.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow08.png"
[ERROR]: Couldn't load texture 'textures/shadow08.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow09.png"
[ERROR]: Couldn't load texture 'textures/shadow09.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow10.png"
[ERROR]: Couldn't load texture 'textures/shadow10.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow11.png"
[ERROR]: Couldn't load texture 'textures/shadow11.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow12.png"
[ERROR]: Couldn't load texture 'textures/shadow12.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow13.png"
[ERROR]: Couldn't load texture 'textures/shadow13.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow14.png"
[ERROR]: Couldn't load texture 'textures/shadow14.png': Unable to open file, bla
cklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow15.png"
[ERROR]: Couldn't load texture 'textures/shadow15.png': Unable to open file, bla
cklisting**

**Comment by tomangelo2** [comment]
These files doesn't exist in data files. They aren't even meant to be there. I don't remember how exactly does it work, but it doesn't mean anything wrong.
