### ISSUE TITLE
Missing SatCom page for Techs

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1294]
Following page links to Techs, but its SatCom page is missing. http://colobot.info/SatComOnline/master/cbot/build

**Comment by X64E** [comment]
@tomangelo2 What is the mistake?

Build page is exist in instructions list:
![изображение](https://user-images.githubusercontent.com/95232774/146530383-66692cd5-820f-4159-a7b1-91d16aeb9e97.png)
And all links on build page works fine. Or is the problem something else?

**Comment by hexagonrecursion** [comment]
Fixed in 0.2.0 - page no longer links to https://colobot.info/SatComOnline/object/tech
