### ISSUE TITLE
Game crashes when running extern script with parameters

### ISSUE THREAD

**Issue by Damjan94** [colobot/colobot#1296]
when I execute this program the game crashes.

`extern void object::New(float CRASH)
{
	message("hello buggy world");//pun intended
}`

**Comment by tomangelo2** [comment]
I have no idea how CBot works, so I'll just leave a line where code fails in case someone else would try to watch over it. It's right at this assert(): https://github.com/colobot/colobot/blob/master/src/CBot/CBotDefParam.cpp#L154

**Comment by Damjan94** [comment]
cool. I noticed that if I assign a value to the parameter
`extern void object::New(float NO_CRASH = 0) {...}`
it works fine.
