### ISSUE TITLE
Passing object[] array as a category parameter to radar() is accepted by compiler, but crashes the game

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1298]
How to reproduce:

1. Start any level with any robot and items on ground.
2. Run this program on robot
```cpp
extern void object::crash()
{
	object item = radar(radarall(Titanium)); //you might change the category of radarall() to any other object you have
}
```
3. Assertion fails in CBotVar::GetValInt https://github.com/colobot/colobot/blob/master/src/CBot/CBotVar/CBotVar.cpp#L551

Happens both on dev and master builds.

Both radar() and radarall() expects category, which is `int`eger number. But radarall() returns `object[]`, so compiler should notice something fishy is going on. radar() doesn't compile either with 
```cpp
object test = radar(Titanium);
object item = radar(test);
``` 
nor
```cpp
object item = radar(radar(Titanium));
```
returning "Missing number" error. But if we feed it with
```cpp
object test[2];
test[0] = radar(Titanium);
test[1] = radar(PowerCell);
object item = radar(test);
```
it compiles OK, then proceed to crash the game.
I guess `object[]` array is either accepted as a third type of argument, along with `int` and `int[]` but isn't properly handled, or compiler doesn't properly recognize `object[]` type and accepts is as `int[]`, or `object[]` is actually an `int` and it confuses compiler.

**Comment by melex750** [comment]
[The problem code is here](https://github.com/colobot/colobot/blob/master/src/script/scriptfunc.cpp#L860-L865), it should be like [this other code](https://github.com/colobot/colobot/blob/master/src/script/scriptfunc.cpp#L695-L699) from compileSearch().
