### ISSUE TITLE
Incorrect space searching

### ISSUE THREAD

**Issue by isti03** [colobot/colobot#1301]
It seems like `space()` and `flatspace()` functions determine distance from other buildings incorrectly. When a building contains a platform in front of it (like the power station) the program does not seem to be noticing it. This can result in "Not enough space available" messages, when using these to find a building spot.

**Comment by Casteele72** [comment]
In addition, space() seems to fail completely when trying to find space on the SpaceShip platform: It repeatedly returns the same--occupied--space. In Moon mission 1, I had to make it radar(Me) and then move around and use my position to find free space to drop the TitaniumOre.

**Comment by MarcosMD09** [comment]
See #

**Comment by MarcosMD09** [comment]
Please close this Issue
