### ISSUE TITLE
Extremely vulnerable Jenkins server on your infrastructure

### ISSUE THREAD

**Issue by Roottrader** [colobot/colobot#1303]
Hello,
While searching for unsecured servers I have found one which belongs to your organization.
URL:  https://51.255.51.49/
I am able to see all the logs without any authentication. Being in data storage, Gaming services, provide game software development bot services, security services, e-commerce services this issue is very severe. I hope you take your security very seriously. Also, I am able to see your builds, build logs, console output, source code logs, on your Jenkins server. I hope you will patch the server soon and award me a good bounty for this responsible disclosure.

Many Thanks,
Roottrader

**Comment by MrSimbax** [comment]
What is wrong with public logs?

**Comment by Roottrader** [comment]
Hey MrSimbax, 

Thank you for your reply. I am glad if the Jenkins server is meant to be open and logs should be public.

**Comment by MrSimbax** [comment]
So there's no issue then? As far as I'm aware, open source projects generally don't hide logs from their CI servers, so I don't understand what's the issue is about.

**Comment by Roottrader** [comment]
Yes, you are correct. There is no issue. Thank you for your valuable time

**Comment by krzys-h** [comment]
The server is left public on purpose. It doesn't contain any sensitive information, only build logs of a open-source game, which are useful for our developers and people sending pull requests to see what went wrong. I've never seen any open-source project that hides the build log, what would even be the point of that?

Also, your idea of "responsible disclosure" on a public issue tracker is very wrong, the entire idea of responsible issue is to NOT disclose it publicly until it's fixed :joy:

> In computer security or elsewhere, responsible disclosure is a vulnerability disclosure model in which a vulnerability or an issue is disclosed only after a period of time that allows for the vulnerability or issue to be patched or mended.
