### ISSUE TITLE
Audio mute doesn't work after refocusing game window when mute sound in background is on

### ISSUE THREAD

**Issue by MrJohn10** [colobot/colobot#1315]
steps to reproduce:
initial state: 
- sound set to normal
- mute sounds in background **on**
1) click mute
3) disactivate game window (click on another window)
3) go back to the game window
sound will be unmuted and sound settings will be set to 0
when opening settings next time, the values will be correct

coused by: https://github.com/colobot/colobot/pull/1309
branch: dev

**Comment by Erihel** [comment]
Can you check if #1318 fixes your problem?

**Comment by MrSimbax** [comment]
Looks fixed to me, but I'll wait for OP answer before merging.

**Comment by MrJohn10** [comment]
Yes, it works. I still would change the name of the setting. It's similar to "background sound"  setting that is on the same page. maybe: "Mute when in background".

**Comment by MrSimbax** [comment]
That's a separate issue, yes? #1316

**Comment by Erihel** [comment]
@MrJohn10 reacted with thumbs up which is less visible the a comment. I guess this issue can be closed as there is a separate one for translation.
