### ISSUE TITLE
Segfault when starting on Debian

### ISSUE THREAD

**Issue by freedomlives** [colobot/colobot#1319]
I installed and ran the appimage. Starting animations were shown, sound played, but before the main menu comes up, crashes.
`
Unhandled exception occurred!

SIGSEGV, segmentation fault

You are running official 0.1.12-alpha build.

The game was in phase PHASE_PLAYER_SELECT (ID=3)
Last started level was: category=exercises chap=0 rank=0
`

**Comment by MrSimbax** [comment]
Can you run the game from the terminal with `-loglevel trace` command line argument and paste the logs?

**Comment by freedomlives** [comment]
Yes, here is the output from the terminal:

Dad plea

[INFO]: Colobot: Gold Edition 0.1.12-alpha starting
[*****] Log level changed to trace
[INFO]: Creating CApplication
[INFO]: Data path: /tmp/.mount_ColoboIws8Qc/usr/bin/../share/games/colobot
[INFO]: Save path: /home/john/.local/share/colobot
[INFO]: Mod autoload dirs:
[INFO]:   * /tmp/.mount_ColoboIws8Qc/usr/bin/../share/games/colobot/mods
[INFO]:   * /home/john/.local/share/colobot/mods
[TRACE]: Searching for mods in '/tmp/.mount_ColoboIws8Qc/usr/bin/../share/games/colobot/mods'...
[TRACE]: Searching for mods in '/home/john/.local/share/colobot/mods'...
[DEBUG]: Finished initalizing data paths
[DEBUG]: PHYSFS search path is:
[DEBUG]:   * /home/john/.local/share/colobot
[DEBUG]:   * /tmp/.mount_ColoboIws8Qc/usr/bin/../share/games/colobot
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO]: Error on parsing config file: No such node (Experimental.MSAA)
[INFO]: Using Vsync: false
[INFO]: No joysticks detected
[INFO]: Error on parsing config file: No such node (Experimental.GraphicsDevice)
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 3.0 Mesa 20.1.2
[INFO]: Mesa DRI Intel(R) HD Graphics (BYT)
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 16
[INFO]: Multisampling supported, max samples: 8
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 8
[INFO]: Maximum texture size: 16384
[DEBUG]: Using quality shadows
[INFO]: Framebuffer supported (ARB)
[INFO]: Maximum renderbuffer size: 16384
[INFO]: CDevice created successfully
[WARN]: Error on parsing fonts config file: failed to open file
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans.ttf (font size = 12.0)
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans_mono.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans_mono.ttf (font size = 12.0)
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans.ttf (font size = 12.0)
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans_bold.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans_bold.ttf (font size = 12.0)
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans_mono_bold.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans_mono_bold.ttf (font size = 12.0)
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans_bold.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans_bold.ttf (font size = 12.0)
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans_italic.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans_italic.ttf (font size = 12.0)
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans_mono.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans_mono.ttf (font size = 12.0)
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans_italic.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans_italic.ttf (font size = 12.0)
[INFO]: Closing joystick
[TRACE]: gl_locale_name: 'en_US:en'
[TRACE]: SetLanguage: Set LANGUAGE=en_US.utf8 in environment
[DEBUG]: Default system locale: en_US.UTF-8
[DEBUG]: Setting locale: LC_CTYPE=en_US.utf8;LC_NUMERIC=C;LC_TIME=en_US.utf8;LC_COLLATE=en_US.utf8;LC_MONETARY=en_US.utf8;LC_MESSAGES=en_US.utf8;LC_PAPER=en_US.utf8;LC_NAME=en_US.utf8;LC_ADDRESS=en_US.utf8;LC_TELEPHONE=en_US.utf8;LC_MEASUREMENT=en_US.utf8;LC_IDENTIFICATION=en_US.utf8
[DEBUG]: SetLanguage: Test gettext translation: 'Colobot rules!'
[DEBUG]: Cache sounds...
[DEBUG]: Loading audio file: sounds/sound000.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 1524
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound001.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 7195
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound002.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 52078
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound003.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 58510
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound004.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 87915
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound005.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 19500
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound006.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 27058
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound007.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 15642
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound008.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 20848
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound009.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 22718
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound010.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 23987
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound011.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 24206
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound012.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 36649
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound013.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 6861
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound014.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 5166
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound015.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 43170
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound016.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 13197
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound017.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 11020
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound018.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 81744
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound019.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 75476
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound020.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 22212
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound021.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 220263
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound022.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 37762
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound023.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 5385
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound024.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 10135
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound025.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 24422
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound026.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 90499
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound027.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 19500
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound028.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 16441
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound029.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 71680
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound030.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 13284
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound031.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 5511
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound032.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 22139
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound033.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 48986
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound034.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 22046
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound035.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 13779
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound036.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 22224
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound037.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 47490
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound038.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 43550
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound039.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 29247
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound040.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 881
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound041.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 4476
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound042.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 53696
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound043.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 23891
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound044.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 81174
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound045.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 18752
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound046.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 17720
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound047.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 67244
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound048.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 26397
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound049.wav
[DEBUG]: Music music/Intro1.ogg was not cached!
[DEBUG]: Loading audio file: music/Intro1.ogg
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 130375
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound050.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 2691
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound051.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 29247
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound052.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 1105
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound053.wav
[TRACE]:   channels 2
[TRACE]:   format 2097248
[TRACE]:   frames 1059502
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 12498
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound054.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 18786
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound055.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 14376
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound056.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 110969
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound057.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 55483
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound058.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 96555
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound059.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 14246
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound060.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 4966
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound061.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 70135
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound062.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 70510
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound063.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 24175
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound064.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 27561
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound065.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 2691
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound066.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 85069
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound067.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 26131
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound068.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 64894
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound069.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 12115
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound070.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 83910
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound071.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 4880
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound072.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 23996
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound073.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 27561
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound074.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 54951
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound075.wav
[TRACE]:   channels 1
[TRACE]:   format 65541
[TRACE]:   frames 5346
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound076.wav
[TRACE]:   channels 2
[TRACE]:   format 65538
[TRACE]:   frames 451631
[TRACE]:   samplerate 44100
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound077.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 30305
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound078.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 39909
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound079.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 12602
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound080.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 5357
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound081.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 8859
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Loading audio file: sounds/sound082.wav
[TRACE]:   channels 1
[TRACE]:   format 65538
[TRACE]:   frames 6707
[TRACE]:   samplerate 22050
[TRACE]:   sections 1
[DEBUG]: Sound loading took 391.70 ms
[INFO]: Created shadow map texture: 1024x1024, depth 32
[TRACE]: Opening SDL memory wrapper for file '/fonts/dvu_sans.ttf'
[DEBUG]: Loaded font file /fonts/dvu_sans.ttf (font size = 15.0)
[TRACE]: Window focused
[DEBUG]: Loading audio file: music/Intro2.ogg
[TRACE]:   channels 2
[TRACE]:   format 2097248
[TRACE]:   frames 5503680
[TRACE]:   samplerate 44100
[TRACE]:   sections 1

Unhandled exception occurred!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You are running official 0.1.12-alpha build.

The game was in phase PHASE_PLAYER_SELECT (ID=3)
Last started level was: category=exercises chap=0 rank=0
==============================

Sorry for inconvenience!
AL lib: ReleaseALC: 1 device not closed

**Comment by freedomlives** [comment]
I tried now running it with gdb (I also tried compiling from source, both stable and development versions, same problem in both)

`[New Thread 0x7fffd10f5700 (LWP 6851)]
[Thread 0x7fffd10f5700 (LWP 6851) exited]

Thread 1 "colobot" received signal SIGSEGV, Segmentation fault.
0x00007fffd34b596b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
(gdb) backtrace
#0  0x00007fffd34b596b in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#1  0x00007fffd3220810 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#2  0x00007fffd33af426 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#3  0x0000555555787574 in Gfx::CGL14Device::DrawPrimitives(Gfx::PrimitiveType, Gfx::Vertex const*, int*, int*, int, Gfx::Color) ()
#4  0x00005555556a05d8 in Gfx::CText::DrawString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Gfx::FontType, float, Math::IntPoint, int, int, Gfx::Color) ()
#5  0x00005555556a07eb in Gfx::CText::DrawText(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Gfx::FontType, float, Math::Point, float, Gfx::TextAlign, int, Gfx::Color) ()
#6  0x000055555573d1df in Ui::CWindow::Draw() ()
#7  0x000055555572dd09 in Ui::CInterface::Draw() ()
#8  0x000055555566cdc7 in Gfx::CEngine::DrawInterface() ()
#9  0x00005555556730e3 in Gfx::CEngine::Render() ()
#10 0x0000555555626aa7 in CApplication::Render() ()
#11 0x0000555555629688 in CApplication::Run() ()
#12 0x00005555556221d2 in main ()
(gdb) `

**Comment by MrSimbax** [comment]
Weird. It looks like a video card driver issue to me. Maybe try updating the drivers?

**Comment by Erihel** [comment]
What language do you use? Also you can try running Colobot with different OpenGL version. Try adding -graphics gl21 or gl33.

**Comment by freedomlives** [comment]
Yes, trying to figure that out now. It is my kids computer, which has Debian, which I'm not so familiar with (I use Gentoo, out of some masochistic tendencies I guess).
I was able to upgrade to the latest kernel, tried several other things. Quitting for tonight. Going to try a different distro later.

Video card is built in graphics: Dell Z36XXX/Z37XXX Intel Atom, which uses i915 kernel driver.

Different OpenGL versions didn't help.

Native language: English
I'm fluent in Slovak (well, I understand it, and can speak and write with various grammatical mistakes...)

**Comment by Erihel** [comment]
When I asked about language I meant in game (forgot it's printed in log). There are some open issues about some characters causing problems. I was wondering if that was it.

**Comment by freedomlives** [comment]
I was wondering why you were asking. :-D As the log shows, it is US English.
Though, I wonder about the line in the log file "[WARN]: Error on parsing fonts config file: failed to open file" since the segfault is occurring when the program is drawing text, if I understand the gdb output correctly.

**Comment by tomangelo2** [comment]
That one line means that there is no file configuring custom fonts filenames, it shouldn't be a part of the problem, as it takes default files in that case, at least it should work like that.
That's my fault, I should've make that sound more like a hint than actual error. I'll fix that tomorrow.

**Comment by freedomlives** [comment]
Now I tried with an Ubuntu 20.4 LiveUSB, and Colobot runs fine. I would try to downgrade Debian to the kernel version and X version Ubuntu is using, but immediately my son pushed me away from the computer and is busy playing... 
In any event, seems indeed to be an issue with the drivers on the latest Debian.
