### ISSUE TITLE
Cloning dev branch seems broken

### ISSUE THREAD

**Issue by melex750** [colobot/colobot#1324]
Using directions from ```INSTALL.md``` I tried the following twice:

In a new empty folder in terminal this command works:
```
git clone -b dev https://github.com/colobot/colobot.git ./
```

Then the next command hangs in the terminal and doesn't download data folder:
```
git submodule update --init
```

**The above usually works, the following is just me trying to figure what is broken.**

Then I copied the data folder from another clone I already had, and tried to compile.

Then the next command gives an error in the terminal:
```
melex750@dell-computer:~/colobot-dev-clone$ git submodule update

fatal: not a git repository: /home/melex750/colobot-dev-clone/data/../.git/modules/data
Unable to find current revision in submodule path 'data'
```
I compared the folder with the other clone and found a missing folder.
```
.git/modules/data
```
Every seems to work again when I copied the missing folder from the old clone.

**Comment by krzys-h** [comment]
When you use submodules, `./data/.git` is just a pointer to `./.git/modules/data`. You can't just copy the data directory from another copy and expect it to work. This is just how submodules are designed.

**Comment by MrSimbax** [comment]
Maybe the instructions need an update? I usually use
```
git clone -b dev https://github.com/colobot/colobot.git --recursive
```
And it works fine.

**Comment by melex750** [comment]
I only copied data because it didn't download, please try a fresh clone and confirm.

**Comment by krzys-h** [comment]
They do work if you actually follow them - I don't think the install instruction say anything about copying the data submodule from another clone ;)

**Comment by melex750** [comment]
I'm always the first to assume I did something wrong, but I think it's broken.
I copied data because it didn't work, I try again in a little while.
Maybe @anyone would like try it for themselves.

**Comment by MrSimbax** [comment]
Works fine for me.
```
PS C:\Users\Simbax\Documents\test\colobot> git clone -b dev https://github.com/colobot/colobot.git .
Cloning into '.'...
remote: Enumerating objects: 768, done.
remote: Counting objects: 100% (768/768), done.
remote: Compressing objects: 100% (739/739), done.
Receiving objects: 100% (38209/38209), 53.56 MiB | 1.29 MiB/s, done.7441Receiving objects: 100% (38209/38209), 52.09 MiB | 2.13 MiB/s

Resolving deltas: 100% (30113/30113), done.
PS C:\Users\Simbax\Documents\test\colobot> git submodule update --init
Submodule 'data' (git://github.com/colobot/colobot-data.git) registered for path 'data'
Cloning into 'C:/Users/Simbax/Documents/test/colobot/data'...
Submodule path 'data': checked out '611cbfdd079e97a71f97810636f2ab2358cb4eeb'
PS C:\Users\Simbax\Documents\test\colobot>
```
The only "hanging" is on the `Cloning into 'C:/Users/Simbax/Documents/test/colobot/data'...` part. I wonder why it doesn't show progress like `git clone`. But it was always like that.

**Comment by melex750** [comment]
It worked this time, false alarm I guess.
Closing.
