### ISSUE TITLE
Add instructions for compilation and installation using vscode

### ISSUE THREAD

**Issue by MrJohn10** [colobot/colobot#1326]
I will make a pull request in a minute.

**Comment by MrSimbax** [comment]
You don't have to make issue for every pull request, especially if you're just going to do it yourself ;)

**Comment by krzys-h** [comment]
but if you are going to do it, at least mention the issue number in the PR so that they are linked

#1327

**Comment by krzys-h** [comment]
oops, sorry, wrong button :P
