### ISSUE TITLE
Make AlienNest destroyable with a certain code

### ISSUE THREAD

**Issue by PracticeBot13** [colobot/colobot#1343]
As you know, the third mission of the user level "The Jinx Incident" requires the destruction of the AlienNest in order for the mission to complete. However, the second mission on Volcano requires you to keep the Nest intact so you may collect OrganicMatter.

If I may suggest a change in this context, perhaps you can add a certain command for the Nest like for example;
damage=0 (cannot be destroyed)
damage=1 (can be)

**Comment by rbcat** [comment]
Before any changes made to AlienNest it was destroyable, but not easily - it took several rounds from a fireball shooter to destroy it. That way, it was unlikely for you to destroy it accidentally, but if you meant to do it, it was doable. I think that was OK.

**Comment by rbcat** [comment]
Actually as someone pointed out it can be protected simply by putting new magnifyDamage=0 attribute next to it in the scene.txt of Volcano 2 instead of making it indestructible in the entire game.

**Comment by lolbot-iichan** [comment]
Note: AlienNest is currently destroyable, but is can be done only by Thumper, not by any kind of shooter.
