### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by singhamitoj** [colobot/colobot#1362]
It is almost two years and no new Colobot release. Do you know when there will be a new version, and will it add new features? The update with the most content is the code battle update, so maybe you could add a new game mode, for example, multiplayer mode? Also, why is Colobot still in alpha development? I am thinking that we should be at least in the beta stages by now.

**Comment by Erihel** [comment]
There is a discord server where you can ask questions like this https://discord.gg/56Fm9kb Sadly this link is in dev branch and not in master branch yet.

There are mostly bug fixes in dev branch. As for alpha in the name I think it could be dropped.
