### ISSUE TITLE
Bug in jinx

### ISSUE THREAD

**Issue by VeryOldFan** [colobot/colobot#1370]
Hello !
I have installed jinx on colobot 0.1.12 alpha. It works, but I can't  restaure my saved game.
I have an error message:

> 
 Program: C:\Program Files\Colobot Gold Edition\colobot.exe
File: C:/Users/Simbax/Documents/colobot/src/object/implementation/programmable_impl.cpp, Line 158

Expression: op < static_cast<int>(dynamic_cast<CProgramStorageObject*>(m_object)->GetProgramCount())

Unhandled exception occurred!
//==============================
SIGABRT, abort
//==============================
This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
//==============================
You are running official 0.1.12-alpha build.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=custom chap=1 rank=3
//==============================

Sorry for inconvenience!

>

**Comment by Erihel** [comment]
What is jinx?

**Comment by melex750** [comment]
https://www.moddb.com/games/colobot-gold-edition/addons/jinx

This bug is similar to #797 and #765 but only affects insects hatched from 'AlienEgg defined in scene.txt'.
I think I've found the proper fix, I'll open a PR when I can.

@VeryOldFan thanks for reporting.
