### ISSUE TITLE
Infinite loop when setting vsync

### ISSUE THREAD

**Issue by Erihel** [colobot/colobot#1383]
I've setup VM for Fedora 33 and Ubuntu 20.04.

Colobot runs at first time but after I start it for the second time it freezes. Console spams with "Couldn't enable/disable VSync". Trying to enable VSync in options has the same effect.

Related change https://github.com/colobot/colobot/commit/4bfada2ad6c982047da4bdc03fe239b8a2b90f0c

_Originally posted by @Erihel in https://github.com/colobot/colobot/issues/1372#issuecomment-772763299_

**Comment by MrSimbax** [comment]
Please try [dev-fix-vsync](https://github.com/colobot/colobot/tree/dev-fix-vsync) branch.

**Comment by Erihel** [comment]
Works under Ubuntu 20.04 in VM.
