### ISSUE TITLE
Colobot suddencly crashed and no longer opens

### ISSUE THREAD

**Issue by Kreyren** [colobot/colobot#1394]
I wrote a program in game designed to make flybot to carry a battery to me:

```
// Find any powercell and carry it to player's position
public extern bool object::fetchPowercell() {
	object item;
	
	item = radar(PowerCell);
	
	goto(item.position);
	grab();
	
	item = radar(Me);
	goto(item.position);
	drop();
	
	return true;
}
```

After executing that in a level "On the offensive" with no battery available anywhere it crashed the game and now it no longer opens.

LOG: https://gist.githubusercontent.com/Kreyren/9c88bed7ceff8fe6500333f386d59b30/raw/d50f96185b17746e4bd1439d2ec44ab823a2335b/gistfile1.txt

Standard trace: https://gist.githubusercontent.com/Kreyren/c295db5846d87119b82c10a300e81f10/raw/c2986e16d916848aed5f09f4eae185241b7c196a/gistfile1.txt

---

FWIW: This program makes the bot to land on the player if the player is not moving
![image](https://user-images.githubusercontent.com/11302521/109401992-8aed0380-7952-11eb-9523-0dd17a87d9a8.png)

It's possible that the game saved during this time and now is trying to load the save file?

---

### Tried solutions
I tried to move my programs from the ~/.local/colobot path without an effect

**Comment by Kreyren** [comment]
Update: The issue is not present when `DRI_PRIME=1` is in use.

**Comment by tomangelo2** [comment]
Cannot confirm crash, neither on release nor dev build. But if it works as supposed with `DRI_PRIME=1`, then it might be GPU related. I'll try it later on other machine with Ubuntu.

Also confirmed on both builds that robot indeed does try to land on player. I'm not sure if goto() should behave like that.

**Comment by Kreyren** [comment]
> Also confirmed on both builds that robot indeed does try to land on player. I'm not sure if goto() should behave like that.

From a programming point of view it should. Adding something that would avoid player would introduce a weird complexity imho.

> Cannot confirm crash, neither on release nor dev build. But if it works as supposed with DRI_PRIME=1, then it might be GPU related. I'll try it later on other machine with Ubuntu.

Seems to be related to game running on iGPU and the crash in the game may have been caused by https://github.com/colobot/colobot/issues/1395.


I try to do more diagnostics to figure out steps to reproduce.

**Comment by Kreyren** [comment]
Closing for a new tracking
