### ISSUE TITLE
Program designed to look for batteries crashes the game

### ISSUE THREAD

**Issue by Kreyren** [colobot/colobot#1395]
## Program

```
// This program makes the bot to look for batteries and deliver them on specified location
public extern bool object::scavangeBattery(string location) {
	object item;
	
	if(true) {
		point start;
		location = start;
	}
	
	item = radar(PowerCell); 
	goto(item.position);
	
	return true;
}
```

### Steps to reproduce
1. Get in flier
2. Save the code above
3. Try to run it expecting game to crash

---

LOG: https://gist.githubusercontent.com/Kreyren/9654b2ec96b07f42fa922bdfaca19dfb/raw/eea7dff247390cbd9a7f87424701569c92b3c668/gistfile1.txt

**Comment by tomangelo2** [comment]
Confirmed to happen on 0.1.12 release, but doesn't happen in current dev. Can you check if dev build works for you as well? Binaries are available here https://github.com/colobot/colobot/actions/runs/590307298

**Comment by Kreyren** [comment]
Not present on dev branch built from source.
