### ISSUE TITLE
Question: Why can't i parse an object to the if statement?

### ISSUE THREAD

**Issue by Kreyren** [colobot/colobot#1399]
![image](https://user-images.githubusercontent.com/11302521/109430587-6a7c8200-7a02-11eb-8684-bf70f94530a5.png)

```cbot
// Obtain specified item
public bool object::obtain(object item) {
	if(this.load.category != item) {
		message("Attempting to obtain an item" + "'" + item + "'");
		goto(radar(item).position);
		grab();
		return true
	} else if(this.load.category == item) {
		message("Item " + "'" + item + "'" + " has been already obtained");
		return true
	} else {
		message("Unexpected");
		return false
	}
}
```

**Comment by melex750** [comment]
Because ```this.load.category``` is an ```int``` and ```item``` is a pointer to an instance of a class ```object```.
It will work if you change ```this.load.category``` to ```this.load```.

**Comment by Kreyren** [comment]
> this.load.category is an int @melex750

That doesn't seem right on my end, `this.load.category` seems to store an `object` depending on what the grabber is holding:

![image](https://user-images.githubusercontent.com/11302521/109444427-7fc2d200-7a3d-11eb-8744-986c220e0a52.png)

**Comment by melex750** [comment]
```Titanium``` is a predefined constant ```int```.  ```load``` and ```category``` are each members of class ```object```.
```load``` is a pointer to the ```object``` held by the grabber. The value of ```category``` is the *type* of ```object```.
