### ISSUE TITLE
Crash after intro scene if iGPU is used

### ISSUE THREAD

**Issue by Kreyren** [colobot/colobot#1400]
### Steps to reproduce
1. Open colobot using `DRI_PRIME=0 colobot`
2. Expect failure on startup

LOG: https://gist.githubusercontent.com/Kreyren/700cc3759b502d61b4baf65495d3f380/raw/16b5eb97173f9ebad84bce6aef4c6ab1678e1c81/gistfile1.txt
STRACE: https://gist.githubusercontent.com/Kreyren/a0942975c504c07f2e6a20691806a275/raw/c9d4c8d09f87957b071d4fbd19f6ab047db7268f/gistfile1.txt

### System info
```
Host: 20089 Lenovo G770 
Kernel: 5.9.0-5-amd64 
Shell: bash 5.1.0 
Resolution: 1600x900 
DE: Xfce 4.16 
WM: Xfwm4 
CPU: Intel i7-2620M (4) @ 3.400GHz 
GPU: AMD TURKS (DRM 2.50.0 / 5.9.0-5-amd64, LLVM 11.0.1)
GPU: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
Memory: 3820MiB / 15958MiB 
```

### Hypothesis
Broken binding for iGPU renderer.

**Comment by Kreyren** [comment]
From https://github.com/colobot/colobot/issues?q=is%3Aissue+author%3A%40me+sort%3Aupdated-desc+is%3Aclosed

@tomangelo2 Can you elaborate on what might be different on your setup? See system info above.

**Comment by MrSimbax** [comment]
The issue is probably in the GPU driver. Try [workarounds](https://github.com/colobot/colobot/wiki/Common-Issues#the-game-crashes-after-splash-screens-on-linux-and-i-have-an-intel-gpu).

**Comment by krzys-h** [comment]
You are on the broken version of mesa. See https://github.com/colobot/colobot/issues/1372#issuecomment-774754044
