### ISSUE TITLE
Stopping program while executing recycle makes wreck unusable

### ISSUE THREAD

**Issue by pestoffne** [colobot/colobot#1413]
Colobot v0.1.12-alpha

**Steps to reproduce**
1. Run program near the Wreck:
```
extern void object::Recycle() {
    recycle();
    message("code after recycle");
}
```
2. Interrupt the program while recycle command executing.

**Expected behavior**

I think recycle command should be transaction. I mean that the recycle command will continue executing, but the code after the recycle command will not be executed in case of recycle interruption. 

**Incorrect behavior**

Wreck becomes unusable. I mean if you try to recycle this wreck again you will get a "nothing to recycle" error. "Unusable" wreck often looks like a normal wreck, but if you find the exact moment to stop the program, you will see half wreck half titanium complex (see picture).

![cancel-recycle](https://user-images.githubusercontent.com/12718711/117045623-e87a4380-ad39-11eb-84bc-b7041a586d79.png)

**Comment by tomangelo2** [comment]
Pretty sure it's same thing as with build(); #1025 and can be fixed along with it.
Leaving it open as it adds the recycle(); command to the problem.
