### ISSUE TITLE
Any bot or insect can produce anything

### ISSUE THREAD

**Issue by pestoffne** [colobot/colobot#1425]
**Steps to reproduce**
1. Select any bot
2. Run program
```
extern void object::Produce() {
    produce(Houston);
}
```

**Expected behavior**
Only AlienQueen can use produce function and she can produce only insects.

**Incorrect behavior**
Grabber creates Houston.

**Comment by rbcat** [comment]
This command is clearly a cheat and there many more similar commands. Ordinary players are never supposed to know and use them.
It the hidden satcom page it is stated.

> There are hidden commands in CBOT that are not even highlighted in the editor. They are considered cheating, so do not use them for "legal" programs. It should be fine to use them for level creation though if there is no other way.

You can freely execute them with any bot provided that you know about their existence and they indeed are used to make levels work the way they must. They are used by certain bots in official game exercises, alien queen, level controllers and many other objects, and "fixing" them would break everything in those levels completely. Simply put, great many things are wrapped around produce(), not just alien queen producing insects.

**Comment by SmileSick** [comment]
I think that the produce () function should be left for everyone. Some objects in an invisible state can serve as level controllers and give new possibilities and modes in the game, just like in the original parts of Ceebot. For example, I use this function for some research. I think, everyone is free to choose to use it or not.

**Comment by pestoffne** [comment]
It looks like it works as designed.
In my opinion it should be mentioned in code battle rules, that hidden CBOT commands should not be used.
