### ISSUE TITLE
DefenseTower with NuclearCell shows 10 times more energy on panel

### ISSUE THREAD

**Issue by pestoffne** [colobot/colobot#1426]
![10xEnergy](https://user-images.githubusercontent.com/12718711/118672655-9ef22400-b822-11eb-9217-e7ca48faf377.png)

**Comment by pestoffne** [comment]
Same behavior with ResearchCenter.

**Comment by rbcat** [comment]
I just wanted to say that _maybe_ it's not a bug, but a feature, because it allows you to know how many shots DefenseTower still can do with almost dead NuclearCell. But if it's the same with ResearchCenter, then it's really a bug.

**Comment by pestoffne** [comment]
Energy level displays as 6 cells. DefenseTower can shoot 8 times using full PowerCell. It does not show literally shoot count.
Also it is a little surprising that DefenseTower shows energy level another way compared with bots.

**Comment by rbcat** [comment]
> It does not show literally shoot count.
It sure doesn't, it's the same as with regular power cell.
> another way compared with bots.
That's the real point.

And, well, if that was a feature, then it should still show energy the normal way for nuclear cells when they are not almost dead.

**Comment by Z128A** [comment]
>  it's not a bug, but a feature

Seriously?

**Comment by Z128A** [comment]
To @Emxx52 Approved!

![изображение](https://user-images.githubusercontent.com/95349617/145001156-486d991f-9f09-4c8b-a7d4-b1b5f4ea2499.png)
