### ISSUE TITLE
How to enter "Cheat Mode" without F10?

### ISSUE THREAD

**Issue by GithubUser699** [colobot/colobot#1429]
I finished the game and want to experiment a bit now.

There should be a "Cheat Mode" which should be accessable with F10, but my laptop won't allow me to use F# keys at all.
I wanted to change the F10 via settings, but couldn't find it.

**Is there a way to open this mode with a laptop?**

(This mode could be handy in things like spawning objects and teleporting according to the wiki.)

**Comment by DonFlymoor** [comment]
There may be an F-Lock key which toggles function keys, or a fn key that
you need to hold down in order to use F# keys.

**Comment by GithubUser699** [comment]
> There may be an F-Lock key which toggles function keys, or a fn key that you need to hold down in order to use F# keys.
You are totaly right! I always wondered what that fn key is for and just assumed that I cannot use the F# keys at all on a laptop.

Thank you very much!
