### ISSUE TITLE
Problem to load textures on Windows

### ISSUE THREAD

**Issue by LPYTY** [colobot/colobot#1430]
Textures cannot be loaded on Windows 10 20H2.
Maybe that’s because of ‘/‘ in file paths (while on Windows it should be ‘\’
(In the latest stable release on your website)

**Comment by pestoffne** [comment]
**About slashes**

Windows can use both slash '/' and backslash '\\' to separate directories in path. Linux only uses slash '/' for this.
You can check it in cmd (see picture).

![Снимок экрана от 2021-05-29 18-28-11](https://user-images.githubusercontent.com/12718711/120068628-cca15d80-c0ab-11eb-93f7-d6df86677556.png)

Both forward and back slashes can be used in paths in C/C++ code, but backslash '\\' is escape character. For example to print new line you can use `printf("\n")` and to print one backslash you can use `printf("\\")`.

Next two lines of C code opens the same file in Windows:
1.  `FILE *f = fopen("foo\\no.txt", "w");`
2.  `FILE *f = fopen("foo/no.txt", "w");`

**Comment by tomangelo2** [comment]
Dev or Release?
Do you have `log.txt` file next to `colobot.exe` file? If so, can you upload it?

**Comment by LPYTY** [comment]
Release
[log.txt](https://github.com/colobot/colobot/files/6565830/log.txt)

**Comment by LPYTY** [comment]
I found the reason!
I must have lost some files.
Sorry.

**Comment by LPYTY** [comment]
I found the reason!
I must have lost some files.
Sorry.

**Comment by LPYTY** [comment]
Maybe you forgot to provide these files?Or they're no longer needed?

**Comment by melex750** [comment]
Maybe some info in #1361.

**Comment by tomangelo2** [comment]
As mentioned in issue above, these "errors" aren't related, at least they shouldn't. 
Are your GPU drivers up-to-date?
Also try other graphics engines (gl21 or gl33) and/or profile, more informations here -> https://github.com/colobot/colobot/wiki/Common-Issues, maybe newer Intel GPUs doesn't play well with default engine.

**Comment by LPYTY** [comment]
Ah,I’m sorry that I didn’t notice the issue.
