### ISSUE TITLE
colobot dosen't open in kubuntu

### ISSUE THREAD

**Issue by mostafa2113** [colobot/colobot#1443]
i download the app-image form https://colobot.info/ and run it but it close after about 3sec from opening the file
[WARN]: Zenity not available, will fallback to console users dialogs.
[INFO]: Colobot: Gold Edition 0.1.12-alpha starting
[INFO]: Creating CApplication
[INFO]: Data path: /tmp/.mount_Colobo0gyzHS/usr/bin/../share/games/colobot
[INFO]: Save path: /home/myPC/.local/share/colobot
[INFO]: Mod autoload dirs:
[INFO]:   * /tmp/.mount_Colobo0gyzHS/usr/bin/../share/games/colobot/mods
[INFO]:   * /home/myPC/.local/share/colobot/mods
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO]: Error on parsing config file: No such node (Experimental.MSAA)
[INFO]: Using Vsync: false
[INFO]: No joysticks detected
[INFO]: Error on parsing config file: No such node (Experimental.GraphicsDevice)
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 3.0 Mesa 20.2.6
[INFO]: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 16
[INFO]: Multisampling supported, max samples: 8
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 8
[INFO]: Maximum texture size: 16384
[INFO]: Framebuffer supported (ARB)
[INFO]: Maximum renderbuffer size: 16384
[INFO]: CDevice created successfully
[WARN]: Error on parsing fonts config file: failed to open file
[INFO]: Closing joystick
[INFO]: Created shadow map texture: 1024x1024, depth 32

Unhandled exception occurred!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You are running official 0.1.12-alpha build.

The game was in phase PHASE_PLAYER_SELECT (ID=3)
Last started level was: category=exercises chap=0 rank=0
==============================

Sorry for inconvenience!
ERROR: Unhandled exception occurred!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You are running official 0.1.12-alpha build.

The game was in phase PHASE_PLAYER_SELECT (ID=3)
Last started level was: category=exercises chap=0 rank=0
==============================

Sorry for inconvenience!

**Comment by tomangelo2** [comment]
https://github.com/colobot/colobot/wiki/Common-Issues#the-game-crashes-after-splash-screens-on-linux-and-i-have-an-intel-gpu
Try this
