### ISSUE TITLE
SatCom text is offset to background

### ISSUE THREAD

**Issue by nipsufn** [colobot/colobot#1463]
Issue can be observed on Linux and Windows builds of 0.2.0 on high resolution screens (1440p) or when font size slider is set to small.
![image](https://user-images.githubusercontent.com/17983323/135277284-db89b1e8-71b3-45df-a89c-68ff64b16dad.png)

**Comment by X64E** [comment]
![CBOT](https://user-images.githubusercontent.com/95232774/144445441-0c7ff89a-33f0-439d-a1a5-7d9f5ef3e7f5.gif)
