### ISSUE TITLE
Plan B - 6: On Volcano - 2: Reverse Engineering - The Mission is not over, SatCom is not clear about it

### ISSUE THREAD

**Issue by RhFortuna** [colobot/colobot#1465]
Hi,

I don't know if this is a bug or something else. I had built the Autolab, used TNT to make a TargetBot, destroyed the ruined radar and built another RadarStation on this place. The SpaceShip couldn't take off. I killed all Spiders, built a Derrick in BlueFlag and a Converter, returned all bots to the Ship, but the Ship still couldn't take off ("The mission is not accomplished yet" message).

From Mission Control
>  We have determined that the best spot to build a radar on this planet is located on the highest mountain in this region. Unfortunately it is already occupied by a ruined radar.
> 
> Build an autolab and use it to analyze the explosive device you acquired, this will allow your bot factory to replicate the target bot designed by the previous expedition.
> 
> Use the target bot to dispose of the ruin and build a new radar in its place.
> 
>  F1  allows you to review these instructions at all times on your personal SatCom ?.

Colobot 0.2.0 Flatpak stable version
Flatpak 1.6.5
Xubuntu 20.04.3

**Comment by tomangelo2** [comment]
The only winning condition is to build new RadarStation in place of the ruin. I've just tried that and it worked.
I'll look later if it's platform related, or maybe there is small area where it won't detect a Radar.

**Comment by RhFortuna** [comment]
I tried again without any code and it didn't work. Again I took advantage of the titanium inside the ruined radar to build a Radar Station.
I disabled all 3 options and tried again with codes only. And I found that no bot can research for TargetBot in AutoLab with TNT ("Inappropriate object"), but canresearch TargetBot is positive. Oops, I need to specify that the object is AutoLab, so research works. I thought I found the bug.

**Comment by tomangelo2** [comment]
I've looked at it again, this time with Xubuntu on virtual machine, unfortunately no clue what's going on. All buildable area is well within required range.
You can try to run following code on any robot, after you build Radar on the mountain:
```cpp
extern void object::aaaaaa()
{
	point p (-52.5, 147);
	object r = search(RadarStation, p);

	message(distance2d(p, r.position));
}
```
It should return distance between the radar and central point of that hill. Can you post it there?
