### ISSUE TITLE
Can't copy code from SatCom excercises sometimes

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#1471]
I started doing Excercises and noticed that sometimes I can't copy'n'paste sample code from SatCom into the editor.
Here are the results of selective tests:

**5-th chapter "Mover"**
- Mover 1 - OK
- Mover 2 - OK
- Mover 3 - Can't copy
- Flying mover - OK

**6-th chapter "Functions"**
- 1: A function - Can't copy
- 2: Spiral - Can't copy

Probably some excercise pages in SatCom don't support copying?

Colobot: 0.2.0-alpha
OS: Windows 10 21H1 64-bit

**Comment by hexagonrecursion** [comment]
Confirmed. Game version: dev 890333ef972bff5c182c3c93e9087d77368f1f62

**Comment by hexagonrecursion** [comment]
I have managed to reduce this down to the following:
```c++
\c;
\s;this text can be copied
\n;

\image derrick 8 8;

\c;
\s;this text can not be copied
\n;
```
 The image tag somehow breaks copying of text that follows it

**Comment by hexagonrecursion** [comment]
I see what happened

`\image` tag causes m_text to contain nul bytes

https://github.com/colobot/colobot/blob/890333ef972bff5c182c3c93e9087d77368f1f62/colobot-base/src/ui/controls/edit.cpp#L1669

CEdit::GetIndentedText treats a nul byte as the end of the text

https://github.com/colobot/colobot/blob/890333ef972bff5c182c3c93e9087d77368f1f62/colobot-base/src/ui/controls/edit.cpp#L1906
