### ISSUE TITLE
Programming exercises / 4: Motors / 5: Shadow - error "Goto: destination occupied"

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#1491]
The target bot in the programming exercise N4 Motors / N5 Shadow often stops moving with the error "Goto: destination occipied", making it impossible to finish the exercise:
![image](https://user-images.githubusercontent.com/20116984/148697726-9654a758-119d-49bf-97a7-12569577f7b9.png)

The bot should handle such errors and choose another position.

App version: 0.2.0 alpha
OS: Windows 10 21H1

**Comment by Python-Sargent** [comment]
It also sometimes in 4: 5 the TargetBot runs ito you and blows up see: #1513

**Comment by tomangelo2** [comment]
Should be fixed in 0.2.1
