### ISSUE TITLE
Battery cell is not rendered after loading a game

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1505]
After loading a game, bots doesn't seem to have a battery in their slot
![obraz](https://user-images.githubusercontent.com/4140449/156073140-c21cc02e-6ecb-4386-88a1-e833791cbaf8.png)

Battery itself is still there, robots are fully operable, it's just visual glitch.

After taking it out, model is restored

![obraz](https://user-images.githubusercontent.com/4140449/156073265-d10098ce-623d-4931-ba10-ab69e81ee312.png)

~~Commit that introduce this glitch: https://github.com/colobot/colobot/commit/76314f522f7e880d122443b33d70e1cfe1f5ba4f~~ edit: I'm looking for another glitch found while checking this, started with that one as the crash happened later - everything was good until few commits later. Also the crash doesn't happen now. So this one might be related to something with compilation. It needs more tests.
My environment:
Windows 10 Pro 20H2
MSYS2 64-bit with packages up-to-date
GCC 11.2.0 x86_64

According to logs, model is loaded among with other files while loading level.

**Comment by rasmusgo** [comment]
I have seen the same thing compiling and running using ubuntu 20.04 inside wsl.

**Comment by melex750** [comment]
Fixed it with this:
```diff
--- a/src/level/robotmain.cpp
+++ b/src/level/robotmain.cpp
@@ -4930,6 +4930,7 @@ CObject* CRobotMain::IOReadScene(std::string filename, std::string filecbot)
                     assert(slotNum >= 0);
                     assert(slots.find(slotNum) == slots.end());
                     asSlotted->SetSlotContainedObject(slotNum, power);
+                    dynamic_cast<CTransportableObject&>(*power).SetTransporter(obj);
                 }
 
                 for (std::pair<const int, CObject*>& slot : slots)
@@ -4949,14 +4950,6 @@ CObject* CRobotMain::IOReadScene(std::string filename, std::string filecbot)
                 assert(cargo == nullptr);
             }
 
-            if (power != nullptr)
-            {
-                dynamic_cast<CSlottedObject&>(*obj).SetSlotContainedObjectReq(CSlottedObject::Pseudoslot::POWER, power);
-                dynamic_cast<CTransportableObject&>(*power).SetTransporter(obj);
-            }
-            cargo = nullptr;
-            power = nullptr;
-
             objCounter++;
         }
     }```

**Comment by hexagonrecursion** [comment]
You merged the pull request. Did you mean to keep the issue open?

**Comment by tomangelo2** [comment]
No, I've forgot about it.
