### ISSUE TITLE
Error in CEngine::Init() on Linux

### ISSUE THREAD

**Issue by pestoffne** [colobot/colobot#1506]
Reproduces since commit [951db1](https://github.com/colobot/colobot/commit/951db17d530efeda77191540f7ae198370df93c4) (inclusive) in dev on `Ubuntu 20.04` until now ([061ef4](https://github.com/colobot/colobot/commit/061ef44def7d0a64bba68429f9876a8aa9a645de)).
Not reproduces on previous merge commit [3405c03](https://github.com/colobot/colobot/commit/3405c038c9fd0c0cdfc3f322e2b577f9f2f33857) in dev.

**Steps to reproduce**
1. Build dev branch. I build using `mkdir build ; cd build ; cmake .. ; make -j8`.
2. Run colobot executable.

**Incorrect behavior**
Black window appears instead of game. Message box with error appears.
<details>
<summary>Message box error</summary>

```
Error in CEngine::Init()

Please see the console output or log file
to get more information on the source of error
```
</details>

<details>
<summary>Colobot stderr output</summary>

```
[INFO]: Colobot: Gold Edition 0.2.0+alpha-git-err~r951db17d starting
[INFO]: Creating CApplication
[INFO]: Data path: /usr/local/share/games/colobot
[INFO]: Save path: /home/evgeny/.local/share/colobot
[INFO]: Mod search dirs:
[INFO]:   * /usr/local/share/games/colobot/mods
[INFO]:   * /home/evgeny/.local/share/colobot/mods
[INFO]: Found mods:
[INFO]:   * /usr/local/share/games/colobot/mods/AltTextures
[INFO]:   * /home/evgeny/.local/share/colobot/mods/returbot_ge_v1.2b.zip
[INFO]: Additional mod paths:
[WARN]: No manifest file for mod returbot_ge_v1.2b
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO]: Error on parsing config file: No such node (Experimental.MSAA)
[INFO]: Using Vsync: true
[INFO]: No joysticks detected
[INFO]: Error on parsing config file: No such node (Experimental.GraphicsDevice)
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 4.6.0 NVIDIA 470.103.01
[INFO]: NVIDIA GeForce GT 730/PCIe/SSE2
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 16
[INFO]: Multisampling supported, max samples: 32
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 4
[INFO]: Maximum texture size: 16384
[INFO]: Framebuffer supported (ARB)
[INFO]: Maximum renderbuffer size: 16384
[INFO]: CDevice created successfully
[ERROR]: Error creating CText: Error on parsing fonts config file: failed to open file
[INFO]: Didn't run main loop. Exiting with code 6
[INFO]: Unloading files and closing device...
[WARN]: Config file was not properly saved! Saving now...
```
</details>

**Comment by MrSimbax** [comment]
Seems that data submodule wasn't updated. In the mean time you can do that locally easily, cd into data, switch to dev branch and git pull.

**Comment by pestoffne** [comment]
`git submodule update --init --recursive` before `cmake .. ; make -j8` doesn't solve issue for me.

I think the reason is here:
```
bool CFontLoader::Init()
{
    try
    {
        std::unique_ptr<std::istream> stream;
        auto inputStream = MakeUnique<CInputStream>("/fonts/fonts.ini");
        bool good = inputStream->is_open();                     ^ file not found exception here
        stream = std::move(inputStream);

        if (good)
        {
            bp::ini_parser::read_ini(*stream, m_propertyTree);
            GetLogger()->Debug("Fonts config file loaded correctly. \n");
        }
        else
        {
            return false;
        }
    }
    catch (std::exception & e)
    {
        GetLogger()->Error("Error on parsing config file: %s\n", e.what());
        return false;              ^ that error in colobot stderr output
    }
    return true;
}
```

Strace shows that, colobot executable tries to open this files
```
/home/evgeny/.local/share/colobot/fonts/fonts.ini
/usr/local/share/games/colobot/fonts/fonts.ini
/usr/local/share/games/colobot/fonts/fonts.ini
/usr/local/share/games/colobot/fonts/fonts.ini
```
and after that writes error to log.

I try to run game from build folder, but it searches for a fonts.ini file in system folders.

**Comment by MrSimbax** [comment]
> `git submodule update --init --recursive`

That's not what I intended you to do but doesn't matter now. After 73db861cc6e76e1e76797999e154031ed67dab2e it should work out of the box. Your problem seems unrelated to the commit.

```
[INFO]: Data path: /usr/local/share/games/colobot
```

You don't have the compiled `data` installed there or it's outdated (because it doesn't contain `fonts.ini`). You need to run `make install`.

On Linux, the paths are hardcoded to absolute values by default and the paths are based on `CMAKE_INSTALL_PREFIX` which by default is `/usr/local`, that's why it searches in those dirs you mentioned. You can still overwrite the paths with command line arguments or environment variables, see `./colobot --help`. Or, you can configure them during CMake with your preferred defaults.

For development, I personally use `-DCMAKE_INSTALL_PREFIX={path_to_your_build_folder}/install` and `-DRELATIVE_PATHS=ON`. This way the content of the `install` folder is a self-contained game package which can be moved freely. The game can then be run with `./install/games/colobot` (assuming you're in build folder).

You can also use the `PORTABLE` and `PORTABLE_SAVES` flags which will result in a directory structure even more self-contained and similar to Windows. `PORTABLE` is not that useful because it just changes relative paths which doesn't really matter with `RELATIVE_PATHS`, but `PORTABLE_SAVES` can be useful if you want to have separate `saves` for your dev builds (by default `saves` are in your `$HOME`).

**Comment by Anton-V-K** [comment]
> After https://github.com/colobot/colobot/commit/73db861cc6e76e1e76797999e154031ed67dab2e it should work out of the box

The default `fonts.ini` was added recently this year, while the code in `CFontLoader::Init()` which opens this file is there for years (added in 2017). So I'm wondering how it all works on the master branch without `fonts.ini`? :)

**Comment by hexagonrecursion** [comment]
> GetLogger()->Error("Error on parsing config file: %s\n", e.what());
>         return false;              ^ that error in colobot stderr output

Incorrect. The actual lines that produce the error message:

https://github.com/colobot/colobot/blob/951db17d530efeda77191540f7ae198370df93c4/src/graphics/engine/text.cpp#L416
https://github.com/colobot/colobot/blob/951db17d530efeda77191540f7ae198370df93c4/src/graphics/engine/engine.cpp#L340-L341

**Comment by hexagonrecursion** [comment]
@Anton-V-K 

> > After [73db861](https://github.com/colobot/colobot/commit/73db861cc6e76e1e76797999e154031ed67dab2e) it should work out of the box
> 
> The default `fonts.ini` was added recently this year, while the code in `CFontLoader::Init()` which opens this file is there for years (added in 2017). So I'm wondering how it all works on the master branch without `fonts.ini`? :)

Careful examination of https://github.com/colobot/colobot/commit/951db17d530efeda77191540f7ae198370df93c4 reveals that fonts.ini used to be optional - the game would use some hard-coded defaults if the file was missing, but after https://github.com/colobot/colobot/commit/951db17d530efeda77191540f7ae198370df93c4 fonts.ini is required and the game does not start without it

**Comment by hexagonrecursion** [comment]
Fixed by https://github.com/colobot/colobot/commit/73db861cc6e76e1e76797999e154031ed67dab2e
