### ISSUE TITLE
Game crashes on autosave with "Fatal error: got negative system counter difference!" in logs

### ISSUE THREAD

**Issue by Baguettedood** [colobot/colobot#1518]
OS: EndeavourOS (Arch) Linux with kernel 5.17.1-arch
My drive is an NVME SSD with a btrfs filesystem if it matters.
Game version: 0.2.0-alpha

After playing for a while, the game abruptly closes with the following messages at the end of its log:
```
[INFO]: Autosave!
[ERROR]: Fatal error: got negative system counter difference!
[ERROR]: This should never happen. Please report this error.
[INFO]: Exiting with code 0
[INFO]: Unloading files and closing device...
```

When reopening the game I can load the autosave that was just created immediately before the crash, though the screenshot seems to have failed to create properly.

It seems to be more likely to crash (and maybe only crashes at all) when the game speed is increased. I usually play at 2x speed as that has felt comfortable for me for a long time.

Attached log files:
[log_crash_2022-04-09_15_52.txt](https://github.com/colobot/colobot/files/8457403/log_crash_2022-04-09_15_52.txt)
[log_Crash_2022-04-09_22_24.txt](https://github.com/colobot/colobot/files/8457404/log_Crash_2022-04-09_22_24.txt)
[log_Trace_Debug_All_Crash_2022-04-10_02_07.txt](https://github.com/colobot/colobot/files/8457405/log_Trace_Debug_All_Crash_2022-04-10_02_07.txt)
[log_Trace_Crash_2022-04-10_02_14.txt](https://github.com/colobot/colobot/files/8457407/log_Trace_Crash_2022-04-10_02_14.txt)
[log_Trace_Crash_2022-04-10_02_21.txt](https://github.com/colobot/colobot/files/8457409/log_Trace_Crash_2022-04-10_02_21.txt)
[log_Trace_Crash_2022-04-10_02_48.txt](https://github.com/colobot/colobot/files/8457410/log_Trace_Crash_2022-04-10_02_48.txt) - In this last once I left the game idle to autosave a few times at various game speeds. The saves were successful until I increased to 2x speed.

As far as I can tell, manual saves and quicksaves are not affected.

**Comment by Zemogiter** [comment]
I have the same issue. Win10, same game version
[log.txt](https://github.com/colobot/colobot/files/8985495/log.txt)
The only log file I was able to find. I was also playing at a multiplayer of a speed.

**Comment by Bielecki** [comment]
Bumping issue, crashes on 0.2.1-alpha. Windows 10 v19045.4170, nvme ssd with ntfs.
```
[INFO]: Start suspend
[WARN]: Creating non-power-of-2 texture (420x262)!
[INFO]: Stop suspend
[INFO]: Simulation speed = 1.00
[INFO]: Simulation speed = 2.00
[INFO]: Simulation speed = 4.00
[INFO]: Autosave!
[ERROR]: Fatal error: got negative system counter difference!
[ERROR]: This should never happen. Please report this error.
[INFO]: Exiting with code 0
[INFO]: Unloading files and closing device...
```

**Comment by theonlyivanw** [comment]
Im having the same issue Have no idea how to fix.Had this happen in the second level trying to get the black box.

**Comment by hexagonrecursion** [comment]
- Fixed by https://github.com/colobot/colobot/pull/1663#
