### ISSUE TITLE
Moon Mission 1, and possibly others

### ISSUE THREAD

**Issue by Casteele72** [colobot/colobot#1522]
This is a minor issue, but still an issue. When playing Moon Mission 1, I have my bot do a `factory(WingedGrabber,"bot2main()")`, but the bot does not get the bot2main() program at all. It seems the default scenario example code to replace the EnergyCell is the only code that gets loaded in to the new bot.

**Comment by hexagonrecursion** [comment]
It should be "bot2main", not "bot2main()". I will add an example to the documentation (eventually)

**Comment by hexagonrecursion** [comment]
* The documentation improvement has been merged https://github.com/colobot/colobot-data/pull/89

I think this can be closed
