### ISSUE TITLE
radar command doesnt work 

### ISSUE THREAD

**Issue by marcoweise** [colobot/colobot#1525]
The radar command doesn't work for selfmade programms
it says that the object doesn't exist 
but I build it or it lays around.

**Comment by tomaszkax86** [comment]
Could you post a code snippet with the radar() command that doesn't work and/or a specific scenario or level where that happens?

**Comment by marcoweise** [comment]
sure

**Comment by marcoweise** [comment]
![Screenshot_20220626_195102](https://user-images.githubusercontent.com/108234247/175827565-139201a0-e885-4533-9342-00f06bac6607.png)
![Screenshot_20220626_195426](https://user-images.githubusercontent.com/108234247/175827572-a2c010fc-d402-4493-a375-6ef53a352ba0.png)

**Comment by marcoweise** [comment]
im german

**Comment by marcoweise** [comment]
its in every level

**Comment by tomaszkax86** [comment]
You forgot to assign the object found by radar() to `item`. It should be something like this:
```
object item;
item = radar(BotFactory);
goto(item.position);
```

**Comment by marcoweise** [comment]
Could you help me with the programm that troubles me?

![Screenshot_20220627_131833](https://user-images.githubusercontent.com/108234247/175930078-4d359dd6-7ea2-4420-bcf0-e6afdd6584db.png)

**Comment by tomaszkax86** [comment]
You wrote things like:
```
radar(Converter);
```
all of that should be more like:
```
item = radar(Converter);
```

**Comment by marcoweise** [comment]
ok I'll try that

**Comment by marcoweise** [comment]
thanks it works until now

**Comment by marcoweise** [comment]
it works now
but when i was testing bevor i opened this issue colobot closed and there was a message that said something about that its propably a bug
