### ISSUE TITLE
Boring

### ISSUE THREAD

**Issue by ixPost** [colobot/colobot#1540]
Most of the missions are too easy.

**Comment by melex750** [comment]
https://www.moddb.com/games/colobot-gold-edition/addons

https://www.moddb.com/mods/returbot/addons/returbot

https://github.com/colobot/colobot/files/7993711/MazesOnMarsV02.zip

**Comment by ixPost** [comment]
> https://www.moddb.com/games/colobot-gold-edition/addons
> 
> https://www.moddb.com/mods/returbot/addons/returbot
> 
> https://github.com/colobot/colobot/files/7993711/MazesOnMarsV02.zip

Where should I put the files?

**Comment by tomangelo2** [comment]
Usually you just need to unpack or leave zip files inside "mods" directory.

**Comment by ixPost** [comment]
All the files under levels/other got deleted after I downloaded Returnbot.

**Comment by lolbot-iichan** [comment]
>Also we need to make explosive islands on Amnesia cracking bridge like stuff exetra.
To my surprise, current physical engine seems to lack support of any bridges, even non-cracking.
Currently all the walking surfaces are either a pure landscape, or a truncated cone just above the flat ground, like in space ship and various charging/repairing pads. No floating platforms, no bridges, no walkable roofs, etc.

**Comment by ixPost** [comment]
I know🙄.

**Comment by X64E** [comment]
Most of the missions are too uninteresting. For example, drive ants to mines. There is nothing to look for and nothing to explore, pure routine.

**Comment by X64E** [comment]
Also, the control is not very convenient, you don’t always want to write code, sometimes you want to give a command with the mouse to go there, take it, put it here ...

**Comment by X64E** [comment]
However, the graphics and different planets create a pleasant impression.

**Comment by ixPost** [comment]
@Emxx52 is something wrong with you? Who would play colobot if it's boring what'd be the use of Colobot?
