### ISSUE TITLE
Wasps can burn underwater

### ISSUE THREAD

**Issue by ixPost** [colobot/colobot#1546]

**Comment by tomangelo2** [comment]
As they don't get extinguished after being shot, or that you can shot them while underwater?

**Comment by ixPost** [comment]
Don't get extinguished.

**Comment by tomangelo2** [comment]
Wasps (and other insects as well) are dead at this point, there is no mechanic to cancel death after entering water. This is how this game was designed to be.

**Comment by lolbot-iichan** [comment]
Maybe the death should not be canceled, but death animathing should be switched on contacting water?

**Comment by ixPost** [comment]
In fact maybe we should have them be programed to run around in stead of having them animated runing around. This could be useful for avoiding obstacles.

**Comment by ixPost** [comment]
Also I think insects should purposefully go into the water too extinguish the fire (and live on but with lower health).
