### ISSUE TITLE
[PROPOSAL]Shouldn't flags be limited?

### ISSUE THREAD

**Issue by ixPost** [colobot/colobot#1549]
To make new flags you'd have to make a new sort of building called a Asset Printer and drop in a titanium cube this will make five flags(each in a different color by default).

**Comment by lolbot-iichan** [comment]
Producing plantable flags would require adding some game mechanics of pickable objects (handling inventory, etc) - currently there is no such thing (except for "Find the jetpack" part, which is a hack). It may be an interesting extention, but isn't this too much work to implement for planting flags only?

PS Flags are already limited - there is currently a limit of maximum 5 flags of each color existing on the map. Planting 6th flag of the same color should fail.

**Comment by X64E** [comment]
No, I don't think touch the flags is bad idea. The flag is conditionally like a beacon on the map. For example, you have found resources, set a flag and this allows you to easily find them in the future.

https://github.com/colobot/colobot/issues/1475

Here's an idea on how to make the game mechanics more interesting. Add fuel, water, maybe some kind of plant manipulation.

**Comment by X64E** [comment]
There is something to change here.
