### ISSUE TITLE
Distance of visibility aren't working correctly

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#160]
Always, when I go to the settings menu when playing (even if I don't change anything), the distance of visibility are changes to maximum as possible in the game.

![duzo](https://f.cloud.github.com/assets/4019345/356385/fe40fc6c-a104-11e2-9423-ccd6a596c90b.jpg)

That is correct, before I went to the settings menu:
![malo](https://f.cloud.github.com/assets/4019345/356389/523ab01a-a105-11e2-844e-aed74314dd81.jpg)

**Comment by krzys-h** [comment]
Could you check again? Appears to work fine for me

**Comment by CoLoRaptor** [comment]
Nope, that still occures. Tested on OpenGL 1.4 and Windows last dev builds. You have to set for max details in Graphics menu (everything on 200%) and after restart the game to reproduce that you must move around the Settings menu bookmarks (but don't change any values).

**Comment by tomangelo2** [comment]
Tested on all graphics engines and it occur on all of them.

**Comment by tomangelo2** [comment]
Looks like it's fixed after last @tomaszkax86 commits, so if nobody have this problem anymore then it may be (finally) closed.

**Comment by krzys-h** [comment]
15c5e6919905455567482e41b1cdbae9bd936bf1
a924cf6a75ed8e38a78b1c74625a7895602a07ab
91f897057e107f9af93ea9a65f6cdd2b2615647c
Please reference issues in commits, or at least mention the exact SHA when closing them - it has saved me from digging through tens of pages of commit log a few times.
