### ISSUE TITLE
Crash after starting a level

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#1601]
[Screenshot of crash message](https://media.discordapp.net/attachments/1138571018483544196/1138572493414748250/colobot.png?ex=6643cc44&is=66427ac4&hm=85def46c82b3bccdf6c8d0299dd6c71cc46f55cce3c7d860d83dff3fda273e56&)

Crash is happening right after loading a level.

OS is Windows 10 22H2, 64-bit
CPU: AMD A8-3870 APU
Colobot version: 0.2.1-alpha

**Comment by muzscaly** [comment]
Maybe give debug log? Use this tool [WinDbg Preview (Microsoft Link)](https://www.bing.com/search?q=WinDbg+Preview&cvid=291e50cd3cad4c28903b8e50a5632fbf&aqs=edge..69i57j0l8.866j0j9&FORM=ANAB01&PC=U531)

**Comment by hexagonrecursion** [comment]
@tomangelo2 This bug report unfortunately contains very little information. Should it be closed?
