### ISSUE TITLE
Unable to build due to invalid link CMake

### ISSUE THREAD

**Issue by Python-Sargent** [colobot/colobot#1615]
When running `sudo cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/share ..` CMake throws this error.

```
CMake Error at colobot-base/CMakeLists.txt:490 (target_link_libraries):
  Target "Colobot-Base" links to:

    PhysFS::PhysFS

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

`CMake Generate step failed.  Build files cannot be regenerated correctly.`

PhysFS is installed and CMake is up to date and all dependency packages have been installed.

**Comment by melex750** [comment]
I'm not sure about that specific error, but I never use ```sudo``` when I run cmake, maybe try without it.

**Comment by Python-Sargent** [comment]
``CMake Error: : System Error: Permission denied
``

**Comment by tomangelo2** [comment]
You probably cloned repository somewhere outside of your home directory, so you might have no permissions to write files there.

Aside of that, what distro do you have? You do have `libphysfs-dev` installed?

**Comment by Python-Sargent** [comment]
I have installed `physfs` but trying to install `libphysfs` throws: `error: target not found: libphysfs-dev
`, I checked and I haven't misspelled it.

Also, the `colobot` directory is in my home `~` directory.

**Comment by tomangelo2** [comment]
In Arch it's `physfs` package. It should contain both library and development files. Is it installed?

If `colobot` directory is in your `~` directory, then the only thing I can think off is that you cloned repository with sudo, making this directory owned by root, hence forbidding access to anyone else. Not quite sure if this really matters in this case, cmake running as root should still be able to locate PhysFS library.

**Comment by tomaszkax86** [comment]
I suspect that [FindPhysFS.cmake](https://github.com/colobot/colobot/blob/dev/cmake/FindPhysFS.cmake) needs to be updated or removed. CMake ships with the module for PhysFS now so it's probably unnecessary for us to provide it and it might conflict with the default module. I'll add that to the list of things for [dev-modernize-build-system](https://github.com/colobot/colobot/tree/dev-modernize-build-system) branch.

**Comment by Python-Sargent** [comment]
OK, thank you for the continued support and maintenance of Colobot.
