### ISSUE TITLE
/usr/bin/ld: final link failed: bad value

### ISSUE THREAD

**Issue by Python-Sargent** [colobot/colobot#1630]
When running make cmake throws this error:

```shell
/usr/bin/ld: ../colobot-common/libColobot-Common.a(stringutils_generic.cpp.o): warning: relocation against `_ZTISt12out_of_range@@GLIBCXX_3.4' in read-only section `.text'
/usr/bin/ld: ../colobot-common/libColobot-Common.a(stringutils_generic.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt16invalid_argument@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CBot/CMakeFiles/CBot.dir/build.make:1250: CBot/libCBot.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:706: CBot/CMakeFiles/CBot.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

I think it may have something to do with the `in read-only section` part.

**Comment by tomangelo2** [comment]
Pass `-DCBOT_STATIC=1` to cmake flags.

**Comment by Python-Sargent** [comment]
compiled and got this error when running 'colobot' in the base colobot/ directory :

```
[INFO]: Segmentation fault (core dumped)
```

**Comment by hexagonrecursion** [comment]
> compiled and got this error when running `./colobot` :
> 
> ```
> [INFO]: Segmentation fault (core dumped)
> ```

This is likely caused by the same bug I tried to fix in https://github.com/colobot/colobot/pull/1618. The branch https://github.com/colobot/colobot/compare/dev-modernize-build-system contains an alternative fix. So far neither fix is merged to dev.

**Comment by Python-Sargent** [comment]
ok, thanks

**Comment by hexagonrecursion** [comment]
It looks like you are trying to figure out how to build the game. There are a couple more sharp corners you will stumble into. The same sharp corners I stumbled into when I tried to produce a working build of the game a couple weeks ago. [See this branch for hints](https://github.com/colobot/colobot/compare/dev...hexagonrecursion:colobot:patch-1). I think the next one for you is probably missing shaders (if you are building from the dev branch - did I guess correctly?)

**Comment by Python-Sargent** [comment]
> It looks like you are trying to figure out how to build the game. There are a couple more sharp corners you will stumble into. The same sharp corners I stumbled into when I tried to produce a working build of the game a couple weeks ago. [See this branch for hints](https://github.com/colobot/colobot/compare/dev...hexagonrecursion:colobot:patch-1). I think the next one for you is probably the missing symbolic link to shaders (if you are building from the dev branch - did I guess correctly?)

I've built the game by now, but I am getting an error when running, as you have suggested before this is probably already fixed.

**Comment by Python-Sargent** [comment]
Yes I'm in the dev branch (git automatically defaults there when cloning)
