### ISSUE TITLE
grab PowerCell instead of Titanium

### ISSUE THREAD

**Issue by AndreiCherniaev** [colobot/colobot#1644]
Why bot grab PowerCell instead of Titanium? Is it a bug?

```
extern void object::FindTit()
{
	goto(radar(Titanium).position);
	grab();
}
```

My level is "1: Plan B". My version is 0.2.0-alpha (apt install colobot)

![BatteryInsteadOfTitanium](https://github.com/colobot/colobot/assets/27889022/697ef332-a1a4-49d4-ad37-5ebd10d5f651)
[saveBattInsteadOfTitaniumEarth1.zip](https://github.com/colobot/colobot/files/14151972/saveBattInsteadOfTitaniumEarth1.zip)

**Comment by hexagonrecursion** [comment]
* Thank you. It appears this issue has already been reported. See #345
