### ISSUE TITLE
Add a -shaderdir argument

### ISSUE THREAD

**Issue by hexagonrecursion** [colobot/colobot#1773]
### Describe the feature

When I run colobot from the build directory, it can't find the shaders. This is because the shaders are in colobot-base/src/graphics/opengl33/shaders/ rather than in data/ . My workaround was to add a symbolic link from data/shaders/ to colobot-base/src/graphics/opengl33/shaders/

I propose we add a -shaderdir argument. This would allow to run colobot from the build directory like this:
```sh
./colobot -datadir ../data -shaderdir ../colobot-base/src/graphics/opengl33/shaders

```

**Comment by tomaszkax86** [comment]
Shaders are copied to the build directory when project is configured as long as `COLOBOT_DEVELOPMENT_MODE` is set:

```
if(COLOBOT_DEVELOPMENT_MODE)
    file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/shaders/gl33
        DESTINATION ${PROJECT_BINARY_DIR}/data/shaders
    )
endif()
```

This is done on config so if you modify shaders you have to run CMake config again to have them updated in the build directory. We could improve this so the build system automatically copies to build directory whenever you update the source files and build the project.

**Comment by hexagonrecursion** [comment]
Ooh. I see. Thanks. Sorry.
