### ISSUE TITLE
Can't create a file with CBOT.

### ISSUE THREAD

**Issue by xiendev** [colobot/colobot#192]
I use this code form help page:

```
file handle();
handle.open("filename.txt", "w");
handle.writeln("abc");
handle.close();
```

and get this
![can t create a file](https://f.cloud.github.com/assets/2929789/434579/373ec13c-af53-11e2-9835-45ae202e4528.png)

**Comment by Anton-V-K** [comment]
The documentation still states:

> Files can only be created and opened in the files/ folder which is located in the folder where Colobot has been installed. You cannot not create or open files that are located elsewhere than in the files/ folder.

Checked in 0.1.9 (Windows 7) and SatComOnline for `dev`.
