### ISSUE TITLE
Program state isn't saved

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#199]
When you save a mission and load it, program is started from beginning.

**Comment by SandJ** [comment]
I am playing 0.1.5-alpha and see this effect of running programs restarting when saved games are loaded.  A custom flat-battery-replacement program I wrote that has particular startup conditions, fails on loading a saved game where it was running.  A program to sniff an area using embedded `for` loops will start the search again when loading a game in which it is running.

**Comment by krzys-h** [comment]
Like I mentioned in the commit message - appears to work fine now, but please verify and tell me if we can close this

**Comment by krzys-h** [comment]
I did some more testing, everything seems to work fine. I'm closing this issue now, if you find anything that doesn't work please open a new one.
