### ISSUE TITLE
Images in SatCom

### ISSUE THREAD

**Issue by Altaire13** [colobot/colobot#232]
There are no images (nor icons) in SatCom. After a place, where should be icon, there is invisible text (selectable). After an image's place there is no text at all.

There is a console message:
"[ERROR]: Couldn't load texture 'diagram\huston.png': Couldn't open ./data/textures/diagram\huston.png, blacklisting".

Actually these images are in folder "data\icons". But moving and changing name of a folder only removes a message, but not a problem.

Folder name 'diagram' is not used in colobot-data. But it is used in file src/ui/edit.cpp (functions Draw~, Free~ and LoadImage). 

Images - help on Huston.
1. Before.
![a](https://f.cloud.github.com/assets/5173163/916279/ee5bfadc-fe87-11e2-9a82-0c2e0d7e71e4.png)
2. Removed '\button 176' from 'huston.txt'.
![b](https://f.cloud.github.com/assets/5173163/916281/ee6dd6ee-fe87-11e2-99d8-71ba00f35005.png)
3. Removed '\button 176' and '\image huston 8 8;'.
![c](https://f.cloud.github.com/assets/5173163/916280/ee65c21a-fe87-11e2-9958-375e3e6502cb.png)

**Comment by krzys-h** [comment]
Finally fixed!
