### ISSUE TITLE
Huge demand for RAM for the game

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#233]
After finish mission (4.2): http://i.imgur.com/1iOnaWW.png
After one of exercises: http://img802.imageshack.us/img802/453/6ar2.png
After exiting game: http://img407.imageshack.us/img407/2595/a4ar.png
Console: http://i.imgur.com/DyvVb2K.png
The increase memory usage is probably associated with SatCom. The long shutdown game may be caused by unloading game from the paging file.
OS: Windows XP

**Comment by krzys-h** [comment]
This should not be a problem anymore since we are now using std::unique_ptr. Could you do your experiments again to make sure?

**Comment by tomangelo2** [comment]
http://pastebin.com/xyksvAwK
This problem is not as heavy like it was before, there were some serious memory leaks while reading SatCom. Still, there are some little leaks.

**Comment by piotrdz** [comment]
@tomangelo2: are you still experiencing crashes in SatCom?

**Comment by tomangelo2** [comment]
For now I've only experienced that in mission 2.1, but I've created an issue with that. I'll test more.

**Comment by krzys-h** [comment]
Could it be that it's not a memory leak, but rather intentionally leaving models, textures and music in cache so that they don't have to be reloaded later?

**Comment by tomangelo2** [comment]
It's possible. I'll try to run one scene multiple times.

**Comment by krzys-h** [comment]
Can anybody confirm is this issue still exists?
