### ISSUE TITLE
Cannot create destructor for class

### ISSUE THREAD

**Issue by arturcz** [colobot/colobot#257]
According to the documentation, one can create a destructor for his custom class. However, following code does not compile:

``` cbot
public class A {
        float f;
        void A() {
                message("A ctor");
                f=0;
        }
        void A(float param) {
                message("A ctor with param");
                f=param;
        }
        void ~A() {
                message("A dtor");
        }
}
```

The error is at ~ character, status message says: Function name missing.

**Comment by krzys-h** [comment]
I've decided that for now it's better to have working destructors and make the parser sometimes accept a tilde where it shouldn't. That commit was merged into main repository.
I'm leaving this issue open so that we remember to fix that tilde issue at some point.

**Comment by krzys-h** [comment]
I have no idea at what point this was fixed but it was so closing this issue
