### ISSUE TITLE
The new music in data has no useable source

### ISSUE THREAD

**Issue by OdyX** [colobot/colobot#267]
[As I commented on the culprit commit](https://github.com/colobot/colobot-data/commit/b40048ad6a5a3257ee9390ff15e1addcaec733ab#commitcomment-4926053), the music files newly pushed to colobot-data don't have their real source available, thereby making these .ogg files unreleaeseable under the GPL-3.

Namely:

  * [Constructive.ogg](https://github.com/colobot/colobot-data/blob/dev/music/Constructive.ogg)
  * [Humanitarian.ogg](https://github.com/colobot/colobot-data/blob/dev/music/Humanitarian.ogg)
  * [Hv2.ogg](https://github.com/colobot/colobot-data/blob/dev/music/Hv2.ogg)
  * [Infinite.ogg](https://github.com/colobot/colobot-data/blob/dev/music/Infinite.ogg)
  * [Prototype.ogg](https://github.com/colobot/colobot-data/blob/dev/music/Prototype.ogg)
  * [Quite.ogg](https://github.com/colobot/colobot-data/blob/dev/music/Quite.ogg)

If this music is to be released with the next version of Colobot, then the source for these music files need to be made available?

The GPL-3 under which Colobot is released imposes the availability of the “source code” for a work, which means "the preferred form of the work for making modifications to it."

I'd be very surprised if @Emxx52 was working on the compressed .ogg files directly.

Now, there are two ways to solve this, in order of preference:
  * Ship the original files as saved in the composition software used by @Emxx52 in the source repository, make sure lossless (.wav, .flac) and/or lossy (.ogg) versions are built out of them in the build process. This solution sticks to the letter of GPL-3 and allows everyone to base a new work out of @Emxx52's, including differently-compressed outcomes (.mp3, .ogg in a different quality, …)
  * Ship lossless versions of @Emxx52's work (.flac or .wav) and build lossy versions (.ogg) in the build process. This second solution doesn't stick to the letter of GPL-3 but at least allows everyone "not-Emxx52" to prepare differently-compressed (.mp3, .ogg, whatever) versions. Using this solution implies pretending @Emxx52 worked directly on the lossless files…

I'd highly prefer the first solution as that would be "real open-source" though. It would also be possible to have the source files _and_ the .ogg-files if they are not easily extracted from the source in a build-process (if it needs a manual process from whatever software for example). In this case, the procedure to obtain the "compiled" compressed ogg-files must be documented along the source files.

Cheers, OdyX

**Comment by krzys-h** [comment]
From IRC:
```
23:05 < erihel> issue #267 if there's still no licence for some music/audio files they should be removed
23:05 <+ColoBOT> Issue #267: The new music in data has no useable source
23:05 <+ColoBOT> Issue #267: https://git.io/RA989A
23:07 <+krzys_h> erihel: There is no .flac file for intro music
23:07 <+krzys_h> Emxx52 doesn't want to "Ship the original files as saved in the composition software used by @Emxx52 in the source repository"
23:07 < erihel> intro is form original game or was made later?
23:08 <+krzys_h> intro was made later by PiXeL
23:08 < erihel> then remove all music created by Emxx52
23:08 < erihel> give him some deadline then remove all
23:10 <+krzys_h> erihel: you have a point there, after all not giving the source files makes the music unlicenceable under GPLv3, right?
23:11 < erihel> i'm not exactly sure but OdyX does make a very good point in that issue
23:14 < erihel> or find a licence that can work with gpl game for music
```

1. Waiting on answer from @Emxx52
2. We have to finally contact [PiXeL](https://colobot.info/forum/member.php?action=profile&uid=44) to get the sources
