### ISSUE TITLE
Editor have problems with pasting tabulators

### ISSUE THREAD

**Issue by MrSimbax** [colobot/colobot#274]
When you copy a script with too many tabulators in wrong places and paste it into in-game editor, they disappear. For example, file data/ai/spidict.txt looks like that:
![-colobot-build-yay-share-games-colobot-ai-spidict txt - sublime text 2 unregistered _013](https://f.cloud.github.com/assets/2318282/1816037/bad39370-6f2d-11e3-8a49-0a455401fc2d.png)
But pasted to the editor looks like that:
![colobot_014](https://f.cloud.github.com/assets/2318282/1816035/b2c3c092-6f2d-11e3-823e-afd46aeca4f0.png)
It's issue on both Windows and Linux.

**Comment by B-CE** [comment]
This bug is still present in 1.11 & dev version.
The tabs should be replaced at list by a space.
