### ISSUE TITLE
OSX cmake failure

### ISSUE THREAD

**Issue by berkus** [colobot/colobot#286]
Running `cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/../installed -DGETTEXT_MSGMERGE_EXECUTABLE=/usr/local/opt/gettext/bin/msgmerge -DGETTEXT_MSGFMT_EXECUTABLE=/usr/local/opt/gettext/bin/msgfmt` results in:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLEW_INCLUDE_PATH
   used as include directory in directory /Users/berkus/Hobby/colobot/src
GLEW_LIBRARY
    linked by target "colobot" in directory /Users/berkus/Hobby/colobot/src
LIBINTL_LIBRARY
    linked by target "colobot" in directory /Users/berkus/Hobby/colobot/src
```

The rest of things was properly detected as missing and installed with brew.

**Comment by piotrdz** [comment]
I don't think this issue is valid anymore, since using Homebrew to install all dependencies seems to work fine.

**Comment by piotrdz** [comment]
I'm closing this old issue. I've now got a MacBook Pro that I can use for Colobot development and everything runs smoothly when using Homebrew packages.
