### ISSUE TITLE
Keyboard and mouse control enhancement

### ISSUE THREAD

**Issue by microspace** [colobot/colobot#290]
1) keyboard
Maybe it would be good to improve player control by keyboard. It was quite hard to get used to player control at fist time: short left-key press makes small turn, but if I press a little more, turn angle increases very fast. 
 2) mouse
Maybe it would be good to use mouse wheell click to rotate 3D view. Rotation of 3D scene by moving mouse cursor to edge is good, but imo it is uncommon in nowadays.
Thank you.

**Comment by krzys-h** [comment]
Rotating the scene with mouse was implemented long ago, closing
