### ISSUE TITLE
Cheat  photo2 enhancement

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#293]
Remove all GUI elements when photo2 cheat is active, instead the cheat console, if user activate it. This will be useful for developing clean screenshots of the game. Also the blinking lights of objects like robots or buildings shouldn't switch-off after user activate photo2. Cheat photo1 already hasn't problem with this.
![gui](https://f.cloud.github.com/assets/4019345/2429377/352ebb6c-ac7e-11e3-8b4c-1e23e6b825e7.png)

**Comment by krzys-h** [comment]
We had `invui` that does exactly this for quite some time, closing
