### ISSUE TITLE
CBOT - Method overloading is buggy

### ISSUE THREAD

**Issue by CyborgMaster** [colobot/colobot#31]
Needs more exploration, seems to depend on the order of declaration of the functions

**Comment by MrSimbax** [comment]
Could you give an example of code that is buggy?

**Comment by krzys-h** [comment]
I just got this from someone
![cbot prog1](https://cloud.githubusercontent.com/assets/1517255/9858531/91463f6c-5b21-11e5-91f0-2905c8387063.png)
![cbot prog2](https://cloud.githubusercontent.com/assets/1517255/9858532/915faf42-5b21-11e5-80ca-c19729852ed5.png)

**Comment by tomangelo2** [comment]
For what I know, such overloading does not work even in real programming language, because compiler might don't know if you want first function, or second function with second argument being default. Or maybe I'm wrong?

**Comment by krzys-h** [comment]
This will work if you don't specify default value of a second argument (which you can't do in CBot anyway). If you did, then yes, this becomes ambiguous.

**Comment by MariuszPL55** [comment]
Yeah it's my code. I think I know when this overloading doesn't work, but give me a few minutes to figure it out..

**Comment by MrSimbax** [comment]
@MariuszPL55 So I changed the title of this issue then. I was 99% sure that function overloading works ok, thank you for verifying that.

**Comment by MariuszPL55** [comment]
No problem, I really want to help in that project!

**Comment by krzys-h** [comment]
Fixed in #737
