### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [colobot/colobot#317]
Some parameters (like "[${DOXYGEN_EXECUTABLE}](https://github.com/colobot/colobot/blob/d9fee8b2adad613cf8c10d153cd5cd7b261b7863/CMakeLists.txt#L284)" and "[${CMAKE_BINARY_DIR}/image_test](https://github.com/colobot/colobot/blob/d6eb095f2760eab42e852aceae61289ad7ba36ee/test/unit/common/CMakeLists.txt#L10)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a Wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by piotrdz** [comment]
I think this old issue can be closed as well. People commenting on my CMake bug report have made it clear that at least for now, this is not a bug, but expected behaviour. In any case, this is clearly a CMake issue, and something that cannot be simply fixed on Colobot side.

**Comment by elfring** [comment]
>…, this is not a bug, …

I got the impression that [your report](https://cmake.org/Bug/view.php?id=15076 "CMake does not support source/build trees with ';' in the path") got insufficient software development attention so far. I hope that affected implementation details can still be improved somehow.

**Comment by piotrdz** [comment]
This is not a high priority issue and I suppose that CMake maintainers have more pressing work. Though it would be nice to see some informative warning or error in the case of this issue.
