### ISSUE TITLE
Provide music files as downloadable archives instead of Git repository

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#362]
Git isn't really good for big files. We'll probably just create archives hosted at colobot.info (FLAC and OGG in default quality). If user doesn't disable music in CMake scripts, they'll be automatically downloaded (in OGG) after "make". If he also decides to change the default music quality, the FLAC versions will be downloaded instead and compressed at compile-time.

**Comment by krzys-h** [comment]
> 11:59 < krzys_h> I really have no idea what to do about issue #362 except moving music files out of GitHub into separate zip files
> 12:00 < krzys_h> I mean, that wouldn't be really terrible, they are meant to be optional, and we could have optional "make all download-music" or something
> 12:01 < krzys_h> also maybe "make music" to download .flac files instead of .ogg and convert them to users desired quality (assuming it's diffrent from default value)?

**Comment by krzys-h** [comment]
I've just noticed this on my GitHub's main page. I'm only not sure that monthly bandwidth quota of 1 GB will be enough for our needs.
https://github.com/blog/1986-announcing-git-large-file-storage-lfs

**Comment by tomangelo2** [comment]
Well, maybe not now, but in the future it may be a problematic limit.

**Comment by MrSimbax** [comment]
Doesn't git-lfs let keep files on external server? We have binary files on colobot.info anyway, so why don't we just put textures, music and other binary files there and use GitHub repo with git-lfs? I don't think I understand correctly, but as I understand with this plugin git handles only pointer text files and leaves the actual files alone.

**Comment by krzys-h** [comment]
We'll keep the files on colobot.info server and download them while building, at least until GitHub's large file support will be publicly available.
http://colobot.info/files/music/
