### ISSUE TITLE
Add anisotropic filtering

### ISSUE THREAD

**Issue by CoLoRaptor** [colobot/colobot#368]
Also in colobot.ini new line in "[Setup]" column add command:
AnisotropicFilter=<value>
Values are:
0 - turn off
2x - 2x filter
4x - 4x filter
etc...

**Comment by tomaszkax86** [comment]
Implemented in commit d3b052f19b94d333bbeb6709efb73f180c06c440. Add line below to [Setup] section in colobot.ini.
```
Anisotropy=x
```
1 - no anisotropic filtering, default
2 or higher - anisotropic filtering with specified level; you should typically use 2, 4, 8 or 16
