### ISSUE TITLE
Sometimes game closes without any log information, while navigating in SatCom

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#397]
Especially while changing tab to C-BOT language dictionary or Report from Satellite.

**Comment by krzys-h** [comment]
I still can't really replicate this issue. Could you try to get a few more log files, maybe one of them will be closed correctly? Or, maybe run through gdb if you can figure out how to do that?

**Comment by krzys-h** [comment]
I'm guessing that we still have no clue on what might be causing that?

**Comment by krzys-h** [comment]
Is this still reproducible after SDL2 migration?

**Comment by krzys-h** [comment]
@RaptorParkowsky is this still an issue or can I close this?

**Comment by RaptorParkowsky** [comment]
Well, I didn't have any crash related to navigating in the SatCom's UI so I think I can close this issue. And I hope it will never reopen...
