### ISSUE TITLE
Create CONTRIBUTE.md in main colobot repository

### ISSUE THREAD

**Issue by CoLoRaptor** [colobot/colobot#398]
With description about how people can contributing some stuff, like updated translations, features, textures, etc. There must be highlighted, that all changes we make in dev branch and must be link to actual Colobot: Gold Edition GDD.

**Comment by krzys-h** [comment]
Added in 27e3e061c22c5c40cccf93eb7f4cf90d7b6fceb2. Feel free to suggest any changes!
