### ISSUE TITLE
Add debug-option/cheat to show crashboxes in-game

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#400]
This may be helpful to understand, how physics and crashboxes work in-game in future development with new models and their crashboxes or possibly with new physics engine and animations (if we will implement also this).

Here's an example:
![tpass000](https://cloud.githubusercontent.com/assets/4019345/5038433/a39a487e-6b90-11e4-887f-18056b4c8a59.png)

Violet crashboxes symbolize inactive object. Red is active. Orange is docking.

**Comment by piotrdz** [comment]
You can now display crash spheres by using cheat commands `debugcrashon` and `debugcrashoff`.
