### ISSUE TITLE
Ground flat probe doesn't mark terrain

### ISSUE THREAD

**Issue by piotrwalkusz1** [colobot/colobot#404]
When I probe ground flat, terrain doesn't change. I have to create flag or build some building in order to see green and red mark on ground. I think that this is problem with terrain update.

**Comment by tomangelo2** [comment]
Looks like it's bug that occur only in some configurations. I don't have this problem on Win 7 with GF9800GT, but it occur every time when I run Colobot on Radeon 9200, both on Win XP and Linux

**Comment by krzys-h** [comment]
For me, works on Windows but doesn't on Linux. I'm pretty sure it worked correctly in earlier versions.
