### ISSUE TITLE
%lvl% support in produce()

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#426]

**Comment by tomaszkax86** [comment]
There's a lot of duplicated code that adds support for %something% syntax everywhere. It would be useful to write utility class that can replace various %something% strings with proper values. And if CBot's open() doesn't already support %lvl%, it might be nice to add support for that too, at least for read-only files.

**Comment by krzys-h** [comment]
Support for %something% in CBot might be useful. We should add that.
And it should definetly be read-only.
