### ISSUE TITLE
Make numerical enter act the same as normal enter

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#427]
Some people have problems with enter in code editor - http://colobot.info/forum/showthread.php?tid=452, http://colobot.info/forum/showthread.php?tid=565
Appears to be caused by keyboard sending numerical enter code when normal enter is pressed.

**Comment by tomangelo2** [comment]
File /src/ui/edit.cpp
Change line 454 from 
```C++
if ( event.key.key == KEY(RETURN) && !bControl)
```
to
```C++
if ( event.key.key == (KEY(RETURN) && !bControl) || (KEY(KP_ENTER) && !bControl))
```

**Comment by tomangelo2** [comment]
Well, it's still not fixed. I haven't check this outside an editor, but virtual keyboard from #415 could be useful to seriously fix that.
