### ISSUE TITLE
radar(); parameters not working properly  

### ISSUE THREAD

**Issue by bartekko** [colobot/colobot#430]
finding an object of a specified category works perfectly alright, but when you try to specify desired distance,direction and focus the radar should be working at, they don't. it makes the pathfinding exercises completely undoable as they require looking for a barrier in front, to the left or to the right of the bot.

**Comment by krzys-h** [comment]
I've fixed it already in 61b186343f506a5c702c0004636e0e90c1a60a47. Are you usong the latest version, or is something still broien?

**Comment by bartekko** [comment]
I was using the windows debug version available at 06.01.14. I didn't check for the latest one because I was unable to use a PC when I remembered to add the issue. The current debug version is free of the problem.
