### ISSUE TITLE
Rounding to int issue

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#432]
Run this code a few times:

```C++
extern void object::Test()
{
       for(int i=0; i<4; i++) {
                float r = ((this.orientation-90)/90)%4;
                if(r<0) r=4+r;
                int r2 = r;
                message(this.orientation+" -> "+r+" -> "+r2);
                turn(90);
        }
}
```

After some time, you'll get some weird results like that:
![image](http://i.imgur.com/GAvZb6D.jpg)

**Comment by tomaszkax86** [comment]
It's not really a bug in Colobot but rather precision problem. Float only has 7 decimal points of precision. Colobot for some reason only displays 2 digit after point and rounds the number towards the closest value. For this reason you don't see all the 9s you'd normally see. float->int in Colobot is simple truncation, so if number is very close to 3 but smaller, you'll get 2 after conversion. Example: code below shows messages "3.00" and "2".

```
float value = 2.99999;
int integer = value;

message(value);
message(integer);
```

We can't do much about precision but we can add floor(), ceil(), and round() functions to CBot for proper rounding.

**Comment by tomangelo2** [comment]
These functions were added some time ago, so I think this issue might be closed.
