### ISSUE TITLE
Add atan2() to CBot

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#435]
atan2() is almost like direction(), but in the world space (not relative to the bot).
http://en.wikipedia.org/wiki/Atan2

**Comment by Ghoughpteighbteau** [comment]
Did this get added? I don't see it in [cbottoken.cpp](https://github.com/colobot/colobot/blob/20e41f306024f7bc78e82a774fc0c5308e2f590e/src/script/cbottoken.cpp)

**Comment by piotrdz** [comment]
It has been added but you have to look at [dev branch](https://github.com/colobot/colobot/blob/dev/src/script/cbottoken.cpp).

**Comment by Ghoughpteighbteau** [comment]
Ah IC. If you add "fixes #w/e" or closes (and a few others) then the commit gets linked to the issue and closes it automatically. which is less confusing :P
