### ISSUE TITLE
Copying code from CBot editor to Chrome hangs the browser

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#438]
Tested on Linux. After trying to copy code from Colobot into <textarea> tag the current browser tab just hangs.
I guess it's a bug on our end? I have no idea how copying works internally.

**Comment by Serebriakov** [comment]
Maybe try to copy code into any notepad before copying to browser. Most likely Colobot copies any special characters that hang browser.

**Comment by krzys-h** [comment]
I've already tried that and it works. But that doesn't mean that we shouldn't fix direct copying.

**Comment by MrSimbax** [comment]
It works fine on Windows.

**Comment by krzys-h** [comment]
I know. Clipboard is implemented separately for every platform.

**Comment by Ghoughpteighbteau** [comment]
for the record, I would call that a bug in chrome more than a bug in colobot, what you're actually copying matters of course, but I don't think there should be a circumstance where the browser crashes.

**Comment by MrSimbax** [comment]
Because of that bug (I think) Atom editor hangs too.

**Comment by MrSimbax** [comment]
I know it's Polish website, but maybe it has something to do with this issue? http://niebezpiecznik.pl/post/te-znaki-zabijaja-przegladarke-chrome/

**Comment by krzys-h** [comment]
@MrSimbax I don't think so

**Comment by krzys-h** [comment]
Will be fixed during migration to SDL2

**Comment by krzys-h** [comment]
Unfortunately, it doesn't seem to be fixed in the dev-sdl2 branch that uses SDL2 for clipboard support :(

**Comment by krzys-h** [comment]
Likely an SDL2 bug, as I am able to reproduce it with this simple program:
```C++
#include <SDL2/SDL.h>

int main(int argc, char* argv[])
{
        SDL_Init(SDL_INIT_EVERYTHING);
        SDL_CreateWindow("test", 0, 0, 10, 10, 0);
        SDL_SetClipboardText("test");
        while(1); // do not exit (otherwise clears the clipboard)
        return 0;
}
```
For now, removing from 0.1.7 milestone. Needs to be reported to SDL2 bug tracker later.

**Comment by Erihel** [comment]
If this is a SDL2 bug then close this issue and report a bug in SDL2 bug tracking.

**Comment by AbigailBuccaneer** [comment]
I don't think this is an SDL2 bug. Changing `while(1);` to `while(1) SDL_PumpEvents();` in @krzys-h's simple program above fixes it. The code spinning a `while` loop forever means that SDL never has a chance to handle X events, and the X clipboard API works through an asynchronous protocol (ie. when you paste into Chrome, Chrome goes and asks the application that copied to the clipboard for its contents).

I can't reproduce this bug with colobot under Ubuntu 17.04 (but can with the simple program above). I suspect the cause of the issue would be not properly polling for SDL events (maybe when the app is in the background).

**Comment by krzys-h** [comment]
@AbigailBuccaneer That's a good catch! I never noticed, I think this code worked fine when copying to other apps. Perhaps that's what is causing the issue, though I have no idea why the event loop could stop calling SDL_PumpEvents. I'll look into that later.

**Comment by krzys-h** [comment]
Just tested it and can't reproduce this anymore. I have no idea who fixed it and when but I'm more happy to finally close this issue.
