### ISSUE TITLE
CBOT handle.writeln() crash on 0.1.4

### ISSUE THREAD

**Issue by titanic4** [colobot/colobot#444]
The program:
'''CBOT
extern void object::Nowy()
{
	file plik();
	plik.open("test.txt", "w");
	plik.writeln("This should be in fucking file if the game doesn't crash!");
	plik.close();
	
	
}
'''
Expected result: file being created with written content and closed as nothing happened.
Actual result: game crashes as soon as you try to write something to the file. 
Just compare this program on both original and gold edition. There are specs of my computer: 

CPU: Intel Core i5 4690K @ 3.50GHz
GPU: Nvidia GeForce GTX 970
RAM: 16 GB
OS: Windows 8.1

**Comment by krzys-h** [comment]
Confirmed, I'll take a look at that
Also, for some reason it doesn't create "files" folder by itself (the game throws an error "The file is not open" when writing until you create it manually)

**Comment by krzys-h** [comment]
The main cause of this problem is:
```
[ 12%] Building CXX object src/CMakeFiles/colobotbase.dir/script/scriptfunc.cpp.obj
C:/Users/krzys_h/Desktop/colobot-git/src/script/scriptfunc.cpp: In static member function 'static bool CScriptFunctions::rfconstruct(CBotVar*, CBotVar*, CBotVar*, int&)':
C:/Users/krzys_h/Desktop/colobot-git/src/script/scriptfunc.cpp:3297:53: warning: cast from 'FILE* {aka _iobuf*}' to 'long int' loses precision [-fpermissive]
         pVar->SetValInt(reinterpret_cast<long>(pFile));
                                                     ^
C:/Users/krzys_h/Desktop/colobot-git/src/script/scriptfunc.cpp: In static member function 'static bool CScriptFunctions::rfopen(CBotVar*, CBotVar*, CBotVar*, int&)':
C:/Users/krzys_h/Desktop/colobot-git/src/script/scriptfunc.cpp:3407:49: warning: cast from 'FILE* {aka _iobuf*}' to 'long int' loses precision [-fpermissive]
     pVar->SetValInt(reinterpret_cast<long>(pFile));                                                 ^
```
I'm assuming that this is only an issue in 64-bit compilation of the game.

**Comment by tomaszkax86** [comment]
Can someone check if 1db9d8bdca98989b38fd91efffa00c44daf269dc solved this problem?

**Comment by krzys-h** [comment]
Yes, it did
