### ISSUE TITLE
AlienQueen Problem

### ISSUE THREAD

**Issue by PracticeBot13** [colobot/colobot#447]
The lady02.txt program looks fine to me, but once the Alien Queen's eggs hatch, it's newborn are stationary. I did research on them using the "selectinsect" cheat and I come to find out that their corresponding programs aren't in their program's list and won't activate because of it.

**Comment by krzys-h** [comment]
What version are you using? I think it was ready fixed on dev branch, see issue #418.

**Comment by PracticeBot13** [comment]
I'm currently using the alpha 0.1.4.

**Comment by tomangelo2** [comment]
Do you have stable Release, or dev? In Release it's not fixed yet, but in dev it's (at least it should be) fixed.

**Comment by PracticeBot13** [comment]
I have the Release.

**Comment by tomangelo2** [comment]
In next Release version it will be fixed, as soon as we finish work at 0.1.5

**Comment by PracticeBot13** [comment]
thank you.
