### ISSUE TITLE
.txt Editing for user levels & missions

### ISSUE THREAD

**Issue by PracticeBot13** [colobot/colobot#448]
What program do you use to edit .txt files? Because I'm trying to get my User Planet "Bloodia" to play on gold edition. But every-time I start a mission, it just goes back to the main menu.

Do these .txt files you have stored in the source code have something in the format that goes away when edited in Microsoft Notepad?

**Comment by krzys-h** [comment]
Look in stderr.txt file in your game directory, it should tell you why the level failed to load.
On-screen error messages will be added at some point, probably after UI refactoring.

**Comment by PracticeBot13** [comment]
I don't know where that file is.

**Comment by krzys-h** [comment]
If you installed the game using the official installer in default location, it should be in *C:\Program Files\Colobot\stderr.txt*. If your OS is Windows Vista, 7 or 8 you might have to start the game as administrator for that file to be created.

**Comment by PracticeBot13** [comment]
It still isn't appearing. But I removed a few things and now the level loads, but is corrupt.

**Comment by krzys-h** [comment]
I can't help you more unless you show your level code here

**Comment by PracticeBot13** [comment]
I'll just figure something out.
