### ISSUE TITLE
Find the way to hide solutions in the exercises

### ISSUE THREAD

**Issue by CoLoRaptor** [colobot/colobot#450]
Before the change of program UI, solution programs was "hidden" in the 10 program slot. Now solution is in 1st slot:

![solution](https://cloud.githubusercontent.com/assets/4019345/7009495/f2dbf20e-dc9a-11e4-986a-ed99a6e6cd4e.png)

I think we should somehow hide this lik it was before, because it's too easy for user to use that solution.

**Comment by krzys-h** [comment]
You are correct, but I have no idea how to do that.

**Comment by krzys-h** [comment]
Maybe just make it so you can't actually run the solution unless you copy it into your own program?

**Comment by tomangelo2** [comment]
Or maybe as a program in a solution (like in missions, where you need to mark checkbox)?

**Comment by krzys-h** [comment]
@tomangelo2 I don't really like that, it requires you to go back to main menu to enable it

**Comment by tomangelo2** [comment]
Ok, so maybe in SatCom? Would be available by button on left.

**Comment by CoLoRaptor** [comment]
I was thinking about new cheat code, something like "insertsolution" or "invsolution" like "invradar", but I don't like the idea about completely hiding the solution.

I think that "solution after mark checkbox" could be a good way for now.

**Comment by krzys-h** [comment]
For now, I made it so you can't just run the solution. This may be changed in future when we find another (better?) way to prevent solution misuse.

**Comment by ElonSatoshi** [comment]
This isn't enough. For me, there's still a temptation to copy and paste the example code.

I have an idea: Have the program not show the example code at all, for a period of time: 5 minutes or something. After 5 minutes or so, you get a call from NASA saying they see you're having trouble and they've sent you an example code, and then the example code shows up.
