### ISSUE TITLE
Help tooltips don't display in the menu

### ISSUE THREAD

**Issue by CoLoRaptor** [colobot/colobot#452]
![tooltips](https://cloud.githubusercontent.com/assets/4019345/7009758/cca1c062-dc9c-11e4-8b4e-823075d9ab1c.png)

That happens only in the menu buttons (settings, levels list, main menu). The game's hud are ok.

**Comment by krzys-h** [comment]
Show your colobot.ini, it works fine for me. Maybe something doesn't get saved properly.

**Comment by CoLoRaptor** [comment]
```
[Directory]
savegame=savegame
public=program
files=files
[Setup]
Tooltips=1
InterfaceGlint=1
Soluce4=1
Movies=1
NiceReset=1
HimselfDamage=1
CameraScroll=1
CameraInvertX=0
CameraInvertY=0
InterfaceEffect=1
Blood=1
Autosave=1
AutosaveInterval=6
AutosaveSlots=2
GroundShadow=1
GroundSpot=1
ObjectDirty=1
FogMode=1
LensMode=1
SkyMode=1
PlanetMode=1
LightMode=1
ParticleDensity=2
ClippingDistance=2
ObjectDetail=2
GadgetQuantity=1
TextureQuality=2
TotoMode=1
AudioVolume=25
MusicVolume=25
EditIndentMode=1
EditIndentValue=4
Fullscreen=0
KeyMap=276 97  275 100  273 119  274 115  424 1323  423 1323  32 1323  256 1323  13 101  270 1323  269 1323  9 1323  278 1323  27 1323  282 1323  283 1323  266 1323  284 1323  285 1323  286 1323  287 1323  288 1323  289 1323  280 1323  281 1323  19 112  
DeleteGamer=1
[Edit]
FontSize=19
WindowPosX=0.15
WindowPosY=0.17
WindowDimX=0.7
WindowDimY=0.66
IOPublic=0
IOPosX=0.21875
IOPosY=0.190625
IODimX=0.5
IODimY=0.5520833
[Gamer]
LastName=Gracz

```

**Comment by krzys-h** [comment]
```
Tooltips=1
```
That looks correct. Do you know after which version it broke? Any additional reproduction steps?

**Comment by tomangelo2** [comment]
I can confirm that. In main menu and in missions tooltips are displayed, but in Options they aren't. Turning that option off and on again doesn't solve the problem.
Reproduction: just move the cursor over any checkbox in Options.

**Comment by CoLoRaptor** [comment]
I can confirm @tomangelo2 words. In newest build tooltips are working now in main menu and in level menu, but in the options menu still there's no tooltips.
