### ISSUE TITLE
Contributors link doesn't show on some display resolutions

### ISSUE THREAD

**Issue by CoLoRaptor** [colobot/colobot#465]
![schowek01](https://cloud.githubusercontent.com/assets/4019345/7332710/af226a90-eb4d-11e4-810f-b7764864707a.png)

I think good idea is to make bigger place for text vertically.

**Comment by CoLoRaptor** [comment]
On 640x480 resolution everything is ok.

**Comment by tomangelo2** [comment]
On 1680x1050 I don't have whole line "Contributors on Github" (can't add any screenshot, game instantly exit when pressed any key).

**Comment by tomangelo2** [comment]
Looks like it's fixed for me.

**Comment by CoLoRaptor** [comment]
I also can confirm this. Windows, latest release GOLD build, on every resolution I've got.
