### ISSUE TITLE
How desactive solution vision on exercice ?

### ISSUE THREAD

**Issue by ychoucha** [colobot/colobot#470]
![Uploading Colobot Gold Edition.jpg…]()
Hello,
well on the exercice, i have all solution before start the exercice how desactivated this please ?

**Comment by Emxx52** [comment]
http://colobot.info/forum is a better place for asking questions. As for the functionality you mentioned, well, I guess it hasn't been implemented yet, but I'm quite sure it's form was the subject of a discussion lately, so I suppose it will be added soon enough. See you on the forums.

**Comment by tomangelo2** [comment]
Screen isn't available, but I think that you mean that solution is on the first place. At the moment we don't have any better solution how to hide this. For now we disabled possibility to directly execute solution programs so you need to write a properly program anyway, in future maybe we'll have better idea.

**Comment by CoLoRaptor** [comment]
I think that can be closed after a month of silence.
