### ISSUE TITLE
Dynamic shadows disappearance

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#473]
When yellow frame borders of object under the cursor are animating, shadows disappearing:
![schowek02](https://cloud.githubusercontent.com/assets/4019345/7585693/a8493b62-f8a5-11e4-974e-c63eab9aef07.png)

Moreover, if F12/showstat cheat is on, it's working correctly:
![schowek03](https://cloud.githubusercontent.com/assets/4019345/7585722/e91acc6e-f8a5-11e4-99c4-36bc3d63008d.png)

**Comment by CoLoRaptor** [comment]
Now it looks like it only happen, when ShadowMapping=1. Options 2 and 3 works fine for me.

**Comment by RaptorParkowsky** [comment]
I see that somehow doesn't occur now on ShadowMapping=1 or any other option. I think I can close this issue.
