### ISSUE TITLE
Changing options in Options->Game decrease autosave slots and interval

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#482]
Whenever I do in Options->Game screen, interval between autosaves and autosaves slots are decreasing. Even when I try to increase one of the sliders, second one is decreasing.
Tested on Windows XP, newest pre-Release 0.1.5 build.
edit: This doesn't occur, when the slider is set at max value.

**Comment by krzys-h** [comment]
Works correctly for me. Could you provide any more details?

**Comment by tomaszkax86** [comment]
I'm not entirely sure but I believe autosave interval depends on current game speed. This should be changed to depend on speed-independent timer. Also, autosaving does not pause the engine and when it finishes it makes one bigger step. Autosave should pause simulations during the saving process.

**Comment by tomangelo2** [comment]
Looks like it happen only in Release builds, but not in Dev.

**Comment by CoLoRaptor** [comment]
I can comfirm this. 0.1.5 release needs to be really checked, it have some strange bugs comparing to the recent dev builds.

**Comment by krzys-h** [comment]
Linux build (dev branch) with -DMAKE_BUILD_TYPE=Release, still can't reproduce this issue

**Comment by tomangelo2** [comment]
Same build, but this occur http://pl.tinypic.com/r/29puedl/8

**Comment by Erihel** [comment]
This is UI bug I think. I can't set slider to 16 (still can set it to 15 or 17).

**Comment by tomangelo2** [comment]
Looks like it's fixed.
