### ISSUE TITLE
Navigating in Appearance Customization Menu changes position of models

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#486]
![schowek01](https://cloud.githubusercontent.com/assets/4019345/8391738/f47cca30-1ccc-11e5-8560-44bdcd2964a8.png)
![schowek02](https://cloud.githubusercontent.com/assets/4019345/8391739/f9fb3c6c-1ccc-11e5-920e-d3fecef786d0.png)

**Comment by CoLoRaptor** [comment]
That happens on newest git-HEAD~r78e09c7 Windows builds, on standard OpenGL 1.4 engine.

**Comment by Erihel** [comment]
I can confirm that commit 78e09c757dbe5f8500d9e60d6ba7b7a9938987a7 introduced this bug.

**Comment by krzys-h** [comment]
Caused by #417

**Comment by krzys-h** [comment]
Sorry, I meant #487
