### ISSUE TITLE
Levels start paused

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#487]
Until I hit Pause Break key, levels are completely frozen.
![schowek01](https://cloud.githubusercontent.com/assets/4019345/8391752/b8972bd6-1ccd-11e5-9094-efa33c5bcb9a.png)

**Comment by CoLoRaptor** [comment]
That happens on newest git-HEAD~r78e09c7 Windows builds, on standard OpenGL 1.4 engine.

**Comment by Erihel** [comment]
I can confirm that commit 78e09c757dbe5f8500d9e60d6ba7b7a9938987a7 introduced this bug.
