### ISSUE TITLE
Device Settings doesn't show any resolution

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#488]
When Resolution parameter isn't exist in colobot.ini and in logs shows:
```[INFO]: Error on parsing profile: No such node (Setup.Resolution)```

Then on Device bookmark in Settings Menu the list with resolutions doesn't appear until I click scroll bar:

![schowek01](https://cloud.githubusercontent.com/assets/4019345/8391998/fb0176be-1cd9-11e5-8931-96a5ceeb65fc.png)

I guess we can fix that easily by writing the standard "Resolution=800x600" (or other, depend of device - for some mobile phones there should be lower resolutions) minimum value always when new colobot.ini is created.

**Comment by tomangelo2** [comment]
Maybe instead of 800x600 we could set native desktop resolution, with fullscreen turned on.

**Comment by RaptorParkowsky** [comment]
No, at least not in dev builds.

**Comment by krzys-h** [comment]
I'd recommend against making default resoultion anything that's not 4:3. It REALLY looks terrible with the UI scaling.
