### ISSUE TITLE
Remove spoiler from Settings menu

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#489]
![schowek01](https://cloud.githubusercontent.com/assets/4019345/8398118/7c233390-1de3-11e5-9a10-f61528f8a41f.png)

There's a huge potential spoiler about Alien Queen in the blood setting help baloon. I think it should be replaced as:
```Display blood when the astronaut has been hit```

**Comment by krzys-h** [comment]
I never even noticed this tooltip. How do you find such small details? :P
I'll fix that as soon as I'll have access to a computer, unless anybody else wants to do that quicker.

**Comment by krzys-h** [comment]
Actually... Isn't there also a spoiler in CBot category listing page in SatCom? What are we going to do about that?

**Comment by RaptorParkowsky** [comment]
Well, I could do this by myself, but I totally forgot how to do this kind of stuff with translations of UI, SatCom, etc. Is there any documentation for translations? Maybe we should think about TRANSLATING.md in this repo or place some info about this in CONTRIBUTING.md?

**Comment by tomangelo2** [comment]
CBOT has a lot of spoilers like this, there are categories like AlienQueen, Phaser or Vault. There are even whole pages about them. So I don't find this little line as a spoiler.

**Comment by krzys-h** [comment]
To change this you need to edit text to be translated in src/common/restext.cpp, then "make update-pot", then "make", then probably update Polish translation in po/pl.po (if you don't do this, English text will be used) and "make" again

**Comment by krzys-h** [comment]
Now I see that @tomaszkax86 did it already :)
