### ISSUE TITLE
Robbie's special animations are missing

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#507]
In GOLD alpha 0.1.4 while messages are being displayed, the Robbie (object 301) executes some special animations. The animation depends of what type of the message is displayed and the message box is sparkling:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/8698688/77225874-2b00-11e5-9588-90f26f99cda6.png)
![schowek02](https://cloud.githubusercontent.com/assets/4019345/8698697/827b57ac-2b00-11e5-92d5-220841daad4a.png)
![schowek03](https://cloud.githubusercontent.com/assets/4019345/8698702/88ad44f0-2b00-11e5-9aec-b82d2d9ab666.png)
![schowek04](https://cloud.githubusercontent.com/assets/4019345/8698703/90629010-2b00-11e5-9989-79c722d21a14.png)

The Robbie also is executing some random circles when the player/user doesn't doing any movement.
![schowek05](https://cloud.githubusercontent.com/assets/4019345/8698871/a197e5e6-2b01-11e5-9134-ddadbb1e5056.png)

In the newest version of Colobot: Gold Edition (stable 0.1.5 release nad dev builds) the Robbie doesn't acts like that somehow. She just flying around trying to catch top left place of the background as usual and doesn't react to messages.

**Comment by krzys-h** [comment]
But that was fixed already... 730319ba20fa324ded2319e38be28e2a27f3fbbe

**Comment by RaptorParkowsky** [comment]
Hmm, I doesn't noticed that somehow. Well, I'll test that. Thanks!
