### ISSUE TITLE
L Shift / L Ctrl don't work even though gui buttons allow for flight

### ISSUE THREAD

**Issue by CHmSID** [colobot/colobot#508]
Left shift and ctrl don't work even though I can click the buttons on the gui and the astronaut flies.

I'm using this version of Colobot:
Colobot: Gold Edition 0.1.4+alpha-git-dev~r03bb000

After looking at research.gam, I see it only contains one line:
research=3 build=197197
even though I'm on the third planet now. Could it be it got corrupted?

**Comment by krzys-h** [comment]
That version is really old, looks like it may be from times of refactoring saving/loading. Please update and check again.

**Comment by CHmSID** [comment]
That's weird since I did a git pull on the dev branch some time ago and now just pulled again. Does that mean I need to regularly fetch the branches?
