### ISSUE TITLE
Cancel making a building

### ISSUE THREAD

**Issue by Erihel** [colobot/colobot#509]
If you missclick and astronaut is making steps backward you should be able to stop before he uses his 'gun' to make building.

**Comment by RaptorParkowsky** [comment]
I agree with that. Sometimes that's really irritating. But what key should be used for cancel? Esc already pauses the game with menu. Maybe any control key (arrows, enter, space, etc.)?

**Comment by Erihel** [comment]
I think moving character would be sufficient.
