### ISSUE TITLE
Official code battle level in the game

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#513]
Code battles are now supported (see issue #468). We need an official code battle level (or maybe more than one?) to be created and added to the game data files.

**Comment by RaptorParkowsky** [comment]
But what about the special game mode for it? This is going to be like user level for now?

**Comment by krzys-h** [comment]
We could add another button in the main menu for it.

**Comment by RaptorParkowsky** [comment]
I can help with designing this level to fit with the others in the game, but I prefer to do that when this will be fully implemented and stable.

**Comment by krzys-h** [comment]
The code battles are already fully implemented and stable (at I didn't find any bugs in my testing), except for coloring team objects (#514) which probably isn't going to be implemented in 0.1.6.

**Comment by krzys-h** [comment]
Now that we have team object coloring implemented (#514) it's time to think about the levels. I'm thinking we might want a few:
* WheeledShooter for each of the players. Your goal is to destroy your enemy and avoid his bullets. On this map you have to make a perfect shooting algorithm that takes into account things like e.g. enemy velocity
* The same but with WingedShooters
* WheeledGrabber, some TitaniumOre and basic infrastructure (Converter, BotFactory, PowerPlant). All researches are already done. Your goal is to destroy all enemy objects.
* WheeledGrabber, some TitaniumOre, one Titanium, no infractructure at all. You have to do everything starting with nothing, including having to do researches.
In the future, we might want to implement things like aliens vs bots battles, but that's just an idea for later.

**Comment by RaptorParkowsky** [comment]
I think for now there could be some example levels with examples of solutions. In the future in the Exercise levels we will add a chapter about code battles (how to use research(), how to build with Builders, etc.).

@krzys-h can you send me your final test level with solution? I would like to see how this works and how I can add this to the present version of the game.

**Comment by krzys-h** [comment]
This is my test code battle level, with a very basic solution already loaded:
https://dl.dropboxusercontent.com/u/32866936/Colobot/CODEBATTLE.zip

I know, that program doesn't work perfectly, but my better one is not finished yet :laughing:

**Comment by krzys-h** [comment]
@RaptorParkowsky so... do you have any ideas?

**Comment by RaptorParkowsky** [comment]
@krzys-h Well, I don't know. If we are going to implement that levels into new programming course in Exercises and Challenges game mode, so we probably should wait with official code battle levels. Instead of this we can add already done level as preview of that code battle feature into User levels. I would also add Alludo @MrSimbax level as the temporary user level for testing the objects in the game, etc. I think the Custom levels can be our "proto" levels like EPSITEC did in his time. For level and game mode prototypes.

**Comment by krzys-h** [comment]
Ok, so this is probably the biggest thing left to do until 0.1.6. I don't think putting that in user levels is a bad idea. But for now, I'd rather not mix it with the old challenges - I think we should add a new button in the main menu for that instead, at least for now.

Now, about how the level itself would look like. I'm thinking something like the Diversity level with labirynth - there is a big river in the middle (>40 meters wide, so you can't shoot through it) and you need to research WingedShooters to attack the enemy. On both sides, there is one Titanium to start with and a pre-built Derrick with TitaniumOre. There is energy available in the subsoil everywhere else in the map.
Actually, I'm thinking we should have at least three versions of this level:
* the enemy is just a nest of AlienAnts, they don't attack you actively - good for begginers, or early versions of the algorithm
* the enemy is a simple program built into the game, selectable=0 *(needs something from the code side to make the selectable=0 pass to all created objects for that team)*
* player vs player mode - two controllable bots on both sides, so you can run two programs against each other

**Comment by krzys-h** [comment]
I'm really terrible at making reliefs, could somebody at least take this as a base and make it more fancy, like add mountains or something? (the middle is underwater)
![relief](https://cloud.githubusercontent.com/assets/1517255/9615345/cb58e986-50f7-11e5-938e-c98dd1c419c8.png)
Also, this is the resource file, the green zone is considered the base terrain and should be left flat (I might make it bigger, I didn't actually test how big that is):
![res](https://cloud.githubusercontent.com/assets/1517255/9615376/fca9ec92-50f7-11e5-96e4-099a967a0128.png)

**Comment by RaptorParkowsky** [comment]
Ok, I'm the right person to do that relief and place some decorative objects :zap:

I'll make more natural, but still deep river here and some mountains with lakes as the background.

I don't know how to built another labirynth though.

Tomorrow I'll post the relief here.

**Comment by krzys-h** [comment]
I don't want labirynth here, you are supposed to make winged bots to get through

**Comment by RaptorParkowsky** [comment]
Done. But I almost doesn't test it though. The platforms are in the right size for a bases. The river is enough deep. I recommend:
```
TerrainWater level=8.0 // or level=9.0
```
I don't recommend standard Terranova terrain textures.



![relief](https://cloud.githubusercontent.com/assets/4019345/9633179/c6121288-518b-11e5-8e7c-7a974755d5c2.png)
![resource](https://cloud.githubusercontent.com/assets/4019345/9633186/cc45b8bc-518b-11e5-87b4-3e9595f54ef6.png)

**Comment by krzys-h** [comment]
![image](https://cloud.githubusercontent.com/assets/1517255/9637221/dba93e00-519f-11e5-979e-89bcc7bfa74c.png)
This is too high an unnatural. Couldn't you lower it and - if we really want the player not to go futher (where he can't build anyway because of steep terrain) - surround it with natural mountains?
PS. Yes, I used Terranova textures just because that's what I had set up :P

**Comment by RaptorParkowsky** [comment]
I fixed that a little. The working surface should be the same for every team for equal chances:
![relief](https://cloud.githubusercontent.com/assets/4019345/9638660/2fdc20e8-51a8-11e5-9147-699608137cd1.png)
And optimized resource to have only 2 colors (image file have only 335 bytes! :D ).
![resource](https://cloud.githubusercontent.com/assets/4019345/9638825/f92591fa-51a8-11e5-8eb8-855e4091e0e1.png)

**Comment by krzys-h** [comment]
If I really cared about a few bytes I would just add an option for Derrick to produce given object without checking the resources and then used resae.png :P

**Comment by krzys-h** [comment]
And by the way, I had it restrict the energy zone to be smaller to prevent players from escaping far away from the base spot and building their base there (no energy and no titanium == no base, unless you transport all the resources there and that's not optimal since that takes a long time in which your opponent will kill you already)

**Comment by krzys-h** [comment]
And one more thing - do you understand how scene lighting works? It's a bit dark here
![image](https://cloud.githubusercontent.com/assets/1517255/9639313/c4e0229a-51ab-11e5-9545-f57fe84aed5c.png)
I'm currently using the lights from Terranova free game:
```
CreateLight dir= 0.0;-1.0; 0.0 color= 0.63; 0.63; 0.63 type=Terrain
CreateLight dir= 1.0; 0.0;-1.0 color=-0.70;-0.70;-0.70 type=Terrain
CreateLight dir=-1.0; 0.0; 1.0 color= 1.40; 1.40; 1.40 type=Terrain
CreateLight dir=-1.0;-1.0; 1.0 color= 0.56; 0.56; 0.56 type=Object
CreateLight dir= 1.0;-1.0; 1.0 color= 0.32; 0.32; 0.32 type=Object
CreateLight dir=-1.0;-1.0;-1.0 color= 0.32; 0.32; 0.32 type=Object
CreateLight dir= 1.0;-1.0;-1.0 color= 0.16; 0.16; 0.16 type=Object
```

**Comment by RaptorParkowsky** [comment]
I dunno. Never experimenting with that :). I can always make those mountains smaller or even turn around the whole relief/resource :). It looks like that lights settings are everywhere in the game and I can't find an alternative.

**Comment by krzys-h** [comment]
The edges are still a bit too sharp. It would be nice to prevent robots getting stuck like that:
![zrzut ekranu z 2015-09-06 17 00 23](https://cloud.githubusercontent.com/assets/1517255/9705076/de533e32-54b8-11e5-880a-f4594812fa68.png)

**Comment by krzys-h** [comment]
This is what I have for now:
https://dl.dropboxusercontent.com/u/32866936/Colobot/CodeBattleV2.zip

There is some lighting glitch before the level starts, I have no idea what causes that and how to fix it

**Comment by RaptorParkowsky** [comment]
Ok, I fixed that relief:
![relief](https://cloud.githubusercontent.com/assets/4019345/9722237/a9747356-55a9-11e5-8f04-24e433bd7a1a.png)

**Comment by krzys-h** [comment]
Looks a lot better now, thanks!

**Comment by krzys-h** [comment]
Updated version:
https://dl.dropboxusercontent.com/u/32866936/Colobot/CodeBattleV2-update-2015-09-09_21-00.zip

Still need a basic enemy program (I'll do that), help files (@MrSimbax maybe?) and placing aliens in the first map (@RaptorParkowsky, I've heard you like placing objects at random positions :smiley:)

**Comment by krzys-h** [comment]
Update:
https://dl.dropboxusercontent.com/u/32866936/Colobot/CodeBattleV2-update-2015-09-10_21-00.zip

Added enemy programs and shooter-only levels

**Comment by MrSimbax** [comment]
What would you like to be written in the help files?

**Comment by krzys-h** [comment]
At least a link to the [general instructions](https://github.com/colobot/colobot-data/blob/dev/help/generic/E/battles.txt) you wrote earlier, and some per-level hints like "In this level you need to kill all the ants. They won't attack you unless your robots come too close." or "In this level, the enemy is already preprogrammed. If you want to fight against somebody else's program, start the next level in this chapter"

The general code battle instructions also need to be updated to add instructions on how to control the level, something like "to start the code battle, first run all the programs of the robots and then press the big "start code battle" button above the map" and "after the code battle starts your camera will be put into special mode. You can change objects as you normally would, but you won't see their interface. You can also click somewhere in the air to switch to free camera. Move around by using the numpad keys." (there will be a toggle for that mode added soon, right now the normal mode is unavailable which makes debugging programs a little bit harder)

**Comment by RaptorParkowsky** [comment]
"If you want to fight against somebody else's program, start the next level in this chapter"
Level titles and/or resumes alone should inform what kind of code battle level is that. We have of course 2 options: Player1 vs Player2  and  Player1 vs AI. I don't see any reason to repeating this information in SatCom when this is non-exercise tutorial level, but full & stand-alone Code Battle level prepared for 0.1.6.

I'll prepare some decorations to the level probably at this weekend when I find free time between testing recent GOLD builds and animating outros for our video.

**Comment by krzys-h** [comment]
It is in the level titles already. You may be right, both vs player and vs AI can use the same help file. I'd still want to have a note that the ants in the vs aliens map don't attack actively, they only defend their nest.

**Comment by krzys-h** [comment]
I consider it done, at least for now :)
