### ISSUE TITLE
Team object coloring

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#514]
Team objects should be colored depending on their team, to make it easier to see which ones are whose.

**Comment by tomangelo2** [comment]
Bots/buildings are recolored on planet-specific color (green on Tropica, red on Vulcania), but in team battles it could be replaced by team color. But it mean that bots will have identical colors on each planet, although we can mix planet color and team color before painting bot.

**Comment by krzys-h** [comment]
The problem is that current recoloring system is per texture file, which means I can't eaisly make different robots using the same texture have different colors.

**Comment by RaptorParkowsky** [comment]
Is there any solution for that? Any copying the recolored texture in the game's cache? I hope this doesn't end like that was in CeeBot-4, where robots had duplicated textures in different color?

**Comment by krzys-h** [comment]
It's definetly possible but might require some changes in the graphics engine which I'm not really good at.
