### ISSUE TITLE
Mission 2.1 immediatelly end succesfull after transporting only one TitaniumOre

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#517]

**Comment by krzys-h** [comment]
I must've broken it while refactoring EndMissionTake, I'll look in a moment

**Comment by krzys-h** [comment]
Wait a moment...
```EndMissionTake pos=12.50;-75.00 type=WingedGrabber min=1 immediat=1```
Either this is wrong or I don't understand how is *immediat* supposed to work...

**Comment by krzys-h** [comment]
Fixed in 8ce3a783bb992f52553d6efc7f0cc03b64eb6b75
