### ISSUE TITLE
Terrain is black on OpenGL 2.1 engine

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#520]
As reported to @tomaszkax86 a long time ago, the terrain on OpenGL 2.1 engine is black. It somehow starts working after you open settings in pause menu.
![image](https://cloud.githubusercontent.com/assets/1517255/8773355/f5fbd86a-2ed3-11e5-9856-e96915d540e3.png)
![image](https://cloud.githubusercontent.com/assets/1517255/8773364/0c6d0a6a-2ed4-11e5-8828-834227904121.png)

**Comment by RaptorParkowsky** [comment]
Well, for me that's somehow is working correct even if I don't go to settings menu (but of course it's very slow and easy to crash...)
![schowek01](https://cloud.githubusercontent.com/assets/4019345/8773714/a4554e6c-2ed6-11e5-8908-0514488f67e9.png)

GeForce FX5200 256 MB VRAM

**Comment by krzys-h** [comment]
I know, I'm the only person who had this issue so far, nobody can reproduce it.
It works fine on Windows for me (or at least worked when I last checked), the problem is only on Linux.

**Comment by piotr-szegda** [comment]
I also have this problem on Linux.
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD HAWAII
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.2
OpenGL core profile shading language version string: 3.30

**Comment by tomangelo2** [comment]
This occur on Windows too. Also it didn't happen on OpenGL 3.3 and still doesn't work after entering to Settings. Tried to change graphic options in menu, but nothing happened.
Windows 7 x64, GeForce 9800GT, latest dev-debug binary

**Comment by krzys-h** [comment]
Delaying this for 0.1.7 - we should release 0.1.6 soon and new graphics engines aren't top priority for now

**Comment by krzys-h** [comment]
Fixed!
