### ISSUE TITLE
Crash after victory scene

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#521]
```
Assertion failed: chapter == 0, file /var/lib/jenkins/workspace/colobot-gold-mai
n-dev/src/object/level/parser.cpp, line 114

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
[Inferior 1 (process 1432) exited with code 03]
(gdb) backtrace
No stack.
(gdb)
```
It happen after every mission.

**Comment by krzys-h** [comment]
Which version are you using?
I'm actually getting a different crash in the most recent version:
```colobot: /home/krzys_h/Pulpit/colobot/src/common/restext.cpp:811: const char* GetResourceBase(ResType, unsigned int): Warunek zapewnienia `num < RT_MAX' nie został spełniony.```

**Comment by krzys-h** [comment]
My crash is fixed in 572b8ea5662be1ecb7fd130a843fe9c38dee3c4a, I can't reproduce your one.

**Comment by tomangelo2** [comment]
It was in today release build.

**Comment by RaptorParkowsky** [comment]
I can confirm that on today's debug build.

**Comment by krzys-h** [comment]
Does it really happen after every win scene? I've checked all win scenes in  chapters 1 and 2 and they all work fine for me.

**Comment by krzys-h** [comment]
Also, there were multiple builds today, I need to know if this is before or after 572b8ea5662be1ecb7fd130a843fe9c38dee3c4a

**Comment by RaptorParkowsky** [comment]
Yes, that happens always after win scenes in first missions on Earth and Exercises. That happened on git-HEAD~rlc947f9 (or git-HEAD~r**1**c947f9, I can't just paste it from game menu).

**Comment by krzys-h** [comment]
This is the release build from midnight, that was definetly before the commit I asked about :P
I'm asking about the debug build because you said it happened there. Unless the build bot broke...

**Comment by Erihel** [comment]
Can't reproduce it with newest version.

**Comment by RaptorParkowsky** [comment]
I can confirm that in newest git-HEAD~r72b9738. I think this issue can be closed now.
