### ISSUE TITLE
Colobot sometimes ignores scene file when starting code battle

### ISSUE THREAD

**Issue by CHmSID** [colobot/colobot#534]
I'm talking about scripts specifically. Sometimes when I make a change to the scene file or the script that's used in that scene file, when I start the level no changes have been made. I'm sure I save the files.

For example, I wanted to disable the script of team2 in the code battle example, so in the scene file I changed team2.txt to team4.txt(where no such file exists). The console said it could not load the script from the scene file, but when I loaded the level, the robot had its old code still loaded.

Another one, I made a small change to my own script and after saving the file, reloaded the level. But the changes have not been made there. Furthermore, when I deleted all the code from the in-game editor, every time I started this level, the code was always empty (or simply not on the list if I've deleted it previously).

It all looks like the game is caching the scripts somewhere.

**Comment by krzys-h** [comment]
Yes, it saves the scripts in player's directory. This is the same behaviour that saves the user-created scripts after mission restart. If you remove the file, the game assumes this script was created by the user and loads it. This is the intended behaviour.
Anyway, I think it would be better to never save scripts from scene files.
