### ISSUE TITLE
Adding a string to something unexpected causes a crash

### ISSUE THREAD

**Issue by MrSimbax** [colobot/colobot#535]
```cpp
extern void object::Crash()
{
	point p(1,2,3);
	message(p+"");
}
```

The above code compiles fine, but when run, the game crashes with the following error:

    colobot: /home/simbax/Dokumenty/colobot/src/CBot/CBotVar.cpp:716: virtual void CBotVar::Add(CBotVar*, CBotVar*): Assertion `0' failed.

This code shouldn't compile without errors in the first place. Or maybe `point` variables should be automatically converted to a string when passed to the `message` function (I don't think it would be a good thing though, rather something like `p.str()`)?

**Comment by krzys-h** [comment]
There is a lot of problems like that in the current CBot implementation, especially in implementation of classes (and  "point" is also a builtin class). Will be probably fixed while rewriting CBot.
