### ISSUE TITLE
BlackArrow and RedArrow are swapped

### ISSUE THREAD

**Issue by MrSimbax** [colobot/colobot#536]
![image](https://cloud.githubusercontent.com/assets/2318282/8895113/73dce43c-33ce-11e5-9fd7-91bbb485fa99.png)

BlackArrow draws red arrows, and RedArrow draws black arrows. Animation chooses the correct pencil, though.

**Comment by krzys-h** [comment]
Looks like I also broke the background when making them opaque :/
