### ISSUE TITLE
freemissions.gam created before any level has been loaded

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#541]
In the first run of the game, when I go to Free game menu (and I never run any other levels), menu looks like this:
![schowek02](https://cloud.githubusercontent.com/assets/4019345/8929089/3c5ea6fc-3523-11e5-8011-06a0d51377d5.png)

It looks like freemissions.gam in profile has been created, when I click on Free game menu. Any other game mode doesn't behave like that.

In the freemissions.gam there's only this line:
```CurrentChapter=1 CurrentSel=0```
I don't know, how this is possible to have access to free level on the Moon even if I never go into Missions menu and any other level never has been boot up.

Moreover, I propose rename freemissions.gam into freegames.gam. There should be more universal and tight naming scheme.

**Comment by krzys-h** [comment]
The name is copied from subdirectory name in data/levels/. I'll take a look at this bug later.

**Comment by krzys-h** [comment]
Show the missions.gam file

**Comment by RaptorParkowsky** [comment]
missions.gam file isn't even created, because I never run any level in any game mode on that profile.

**Comment by krzys-h** [comment]
If you finish all the missions on Earth, does it unlock the next free game (Tropica)?

**Comment by krzys-h** [comment]
Fixed.
