### ISSUE TITLE
Autosave interval in game's settings UI doesn't fit with real setting value in colobot.ini file

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#542]
![schowek02](https://cloud.githubusercontent.com/assets/4019345/8929799/45dc5440-3528-11e5-8551-c11aa6444160.png)

I guess that happens with any other value as well.

**Comment by tomangelo2** [comment]
I'll check if this is related to #482

**Comment by RaptorParkowsky** [comment]
#482 is somehow reproductable only on 0.1.5 release Windows builds. Every dev build doesn't have this problem. Strange.

**Comment by tomangelo2** [comment]
#482 sometimes happen on dev-release builds (I've recorded that on this build), but on dev-debug it doesn't at all.

**Comment by krzys-h** [comment]
This could also be fixed in ab6a8eba2b2d5296a122a1ed3617ce02e81db3e5

**Comment by tomangelo2** [comment]
This one still occur on dev-release

**Comment by krzys-h** [comment]
If you close the game, does it get saved then?

**Comment by tomangelo2** [comment]
The file is saved right after clicking Back button.
Also I've noticed, when I've set interval to 15, it was saved as 16. After changing to 16 in game, it was changed to 17 in file. Then in game it could be only increased to 18, then it was saved in file as 18 too. Next: changing in game to 19, in file it's saved as 20.
