### ISSUE TITLE
Sample programs missing

### ISSUE THREAD

**Issue by vieux** [colobot/colobot#543]
Hello, I'm sorry if you already discussed this, but I couldn't find any information about this.

All the sample programs "dispatched by Houston" are missing.

I see they are on @OdyX's repo, for example: https://github.com/OdyX/colobot-data-archive/blob/master/ENG/help/mllune1.txt

Any idea why they are not in the current colobot-data ? License issue ?

If we don't plan to put them back, we should remove the links in game.

**Comment by RaptorParkowsky** [comment]
Well, that's odd why they're missing. Maybe something wrong when levels were rewritten into new file system.

**Comment by krzys-h** [comment]
Looks like the links in SatCom broke when refactoring the level directory structure. The programs are still there and should be available in missions where you first recieve them, but you cannot return to them later.
Are the programs in robots also unavailable or only the help files in SatCom?

**Comment by vieux** [comment]
@krzys-h Yes the programs are available in missions where you first receive them because they are "inlined" there is no link in this case.

The robots are working correctly, only the SatCom is broken.


I'll fix that.
