### ISSUE TITLE
Fix lag on saving level

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#546]
When you playing in big resolution (1920x1080 Full HD or even bigger), the PNG compression takes some time even if computer have good CPU. This may cause big delays when there's autosave enabled.

Moreover, some GPU's have problem with displaying not-power-of-2 resolution images in Load menu, so I think it would be helpful and more stable for older GPUs to convert these screenshots into 512x512 or 256x256 before saving them into PNG files. Lower compression algorythm or even no compression also could be helpful.

**Comment by RaptorParkowsky** [comment]
There's good example of how this is annoying:
https://www.youtube.com/watch?v=od1rQepD5-I#t=09m05s

**Comment by krzys-h** [comment]
This could be either saving the level, copying screen contents to memory or PNG compression. We need to make sure which of them is the main problem.
Also, I wouldn't want to decrease screenshot resolution because I think the current screenshot display is too small and I'd like to make it bigger after CEGUI refactoring. Besides, downscaling also takes time.

**Comment by RaptorParkowsky** [comment]
Well, we don't need super quality of the savegame screenshots. And still, after refactoring the CEGUI, window with screenshot will be still smaller than game's resolution. I think the uncompressed PNG takes a lot less time than any compressed PNG, JPEG etc. and saving that will depend mostly of HDD speed. And downscaling into FullHD into 512x512 by some fast algorythms also takes very less time even on old computers.

**Comment by krzys-h** [comment]
You know that almost every OS in the world caches HDD writes so it doesn't really depend on HDD speed but on RAM speed (and that's REALLY fast in comparation to HDD)? ;)

**Comment by RaptorParkowsky** [comment]
Well, depends... But still the main problem is CPU speed at compression hi-res PNG. How "tight" compression algorhytm do we use now?

**Comment by krzys-h** [comment]
https://github.com/colobot/colobot/blob/dev/src/common/image.cpp#L132-L133

**Comment by krzys-h** [comment]
Looks like you might be right (this is 1920x1080):
```
[INFO]: Game paused - Dialog
[INFO]: Scene write time: 0.043442
[INFO]: CBot state write time: 0.000369
[INFO]: Game resumed
[INFO]: GetFrameBufferPixels time: 0.026485
[INFO]: SetDataPixels time: 0.001397
[INFO]: FlipVertically time: 0.002913
[INFO]: PNG write time: 0.549308
[DEBUG]: Save screenshot saved successfully
```

**Comment by RaptorParkowsky** [comment]
I guess we can try to change this line into:
```
png_set_IHDR(png_ptr, info_ptr, surf->w, surf->h, 1, colortype, PNG_INTERLACE_NONE,
                 PNG_COMPRESSION_TYPE_DEFAULT, PNG_FILTER_TYPE_DEFAULT);
```
This is much faster and less "tight" PNG compression mode.

But this still can't solve the problem with displaying non-power-of-2 textures on some GPUs. For me, on GeForce FX5200 when the game is displaying savegame screenshot, there's huge frame drops, even if the screenshot is in 800x600:

![schowek01](https://cloud.githubusercontent.com/assets/4019345/9046113/bafb6e78-3a28-11e5-9057-ce94b1a1ab04.png)

Well, this is only huge frame drop from 30fps to 10fps, but I think some GPUs can even crash at this point.

**Comment by krzys-h** [comment]
```
[INFO]: Game paused - Dialog
[INFO]: Scene write time: 0.046175
[INFO]: CBot state write time: 0.000321
[INFO]: Game resumed
[INFO]: Construct CImage time: 0.003499
[INFO]: GetFrameBufferPixels time: 0.024262
[INFO]: SetDataPixels time: 0.001370
[INFO]: FlipVertically time: 0.003009
[INFO]: SDL_CreateThread time: 0.000107
[DEBUG]: Save screenshot saved successfully
```

So we are down from 0.580103 seconds (total) to 0.032247 seconds lag on saving image thanks to doing PNG compression in the background. I only need to know if it behaves as well on old CPUs as it does on mine.
We still have about 0.045 seconds of writing just the scene file, for a total of about half a second of lag on writing the game state.

I'll take a look at not power-of-2 textures next

**Comment by krzys-h** [comment]
Wait, what did I just say? Of course I meant 0.075 seconds :P

**Comment by krzys-h** [comment]
Not power-of-2 image display should be fixed now, could you confirm?

**Comment by RaptorParkowsky** [comment]
Yes, It's working without any frame drops:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/9048051/73699036-3a36-11e5-9f54-28b9455a4936.png)
Now I think we can do something with PNG compression. Is that code that I pasted earlier working?

**Comment by krzys-h** [comment]
First tell me if my previous commit (04960035c1a58989d0990555dd9beecc0c32ed5a) works for you or not

**Comment by RaptorParkowsky** [comment]
Well, now I see only one, short lag (probably when the game saves level data). Before that there was 2 lags (one for level data, second for saving image). Is that multithreading? Well, I have Intel Pentium 4 3GHz with Hyper Threading (1 core, 2 threads), so I guess I can't confim is that working on other, slower CPUs with 1 core and 1 thread.

**Comment by krzys-h** [comment]
Yes, that is multithreading. Even if you have CPU without multithreading (that's pretty rare nowadays) the game will keep running instead of completly freezing, through you might notice an FPS drop while it's saving the screenshot.
