### ISSUE TITLE
"this" is broken

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#547]
The following code does not compile:
```C++
point p = this.position;
```
Probably caused by 38c64940a5bf36fe7087c57fd461314c51fcd84b or 7c421b715164cdae89ec4f4a92a017a3d620d3b8

**Comment by krzys-h** [comment]
Confirmed to be caused by 38c64940a5bf36fe7087c57fd461314c51fcd84b

**Comment by vieux** [comment]
@krzys-h my bad.
