### ISSUE TITLE
Moving with a robot interrupt Me building

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#548]

**Comment by vieux** [comment]
This is a duplicate of #509 and it was implemented in https://github.com/colobot/colobot/commit/a18d195cfd6e4d1656e68d5368d3a989b52b26c9 should be included in the next release.

**Comment by MrSimbax** [comment]
It is not a duplicate, it is a bug caused by implementing #509. Only moving an astronaut should cause interruption. And here I thought I haven't made any mistake this one time... Will need to find a way to check if player moves specifically an astronaut.
