### ISSUE TITLE
WayPoints and some parts of RadarStation and ExchangePost are black with quality shadow mapping enabled

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#550]
![image](https://cloud.githubusercontent.com/assets/1517255/9118259/99cab90e-3c6f-11e5-988f-90aa8802883f.png)
![image](https://cloud.githubusercontent.com/assets/1517255/9118267/a762c318-3c6f-11e5-86cc-c75ab6b018de.png)
Could be related to #549

**Comment by tomangelo2** [comment]
Which parts of Exchange Posts and RadarStation are black? You mean this red marked part http://i.imgur.com/8PJeYJe.png ?

**Comment by krzys-h** [comment]
Yes, exactly that part
![image](https://cloud.githubusercontent.com/assets/1517255/9328879/fe60b134-45ac-11e5-8a7f-27b23e8d2b62.png)

**Comment by tomangelo2** [comment]
These parts doesn't have any texture. They're just painted with diffuse parameter. For me it looks like the engine for some reason paint it all black. It don't matter if a face has texture on it, but it comes out for parts without texture.

**Comment by RaptorParkowsky** [comment]
Diffuse color is strange at all even with OpenGL 1.4 lightning. We should:

Replace all diffuse and non-texture polys by textures

or

Do something with lightning to make it more optimal (especially for OpenGL 2.1 and 3.3) and look like in original Colobot or better.

**Comment by krzys-h** [comment]
Somehow it works fine on Windows, the problem is on Linux only

**Comment by tomaszkax86** [comment]
Should be fixed by e6a2fc967149a6bb6096e5208f4d7d52fc0e200c
