### ISSUE TITLE
Game overloads all RAM and SWAP when loading and restarting a level

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#555]
The main process of the game is always small:
![schowek03](https://cloud.githubusercontent.com/assets/4019345/9259287/7d757988-4200-11e5-9d8e-316f0ba80ed1.png)

But when loading any level the game caches a LOT of data that fills all my RAM and SWAP. Even if colobot.exe process still remain very small:

![schowek01](https://cloud.githubusercontent.com/assets/4019345/9259483/bb52d542-4201-11e5-9ccb-f5538814a6ba.png)

After few loads/reboots of the levels the situation is getting worse. Music in menu is stopping, menu screens loads slower, the whole system is unusable slow.

**Comment by krzys-h** [comment]
Does it also increase if you reload the same level again a few times?
You could also try checking the RAM usage with something else than the builtin task manager, chances are you are somehow looking at the wrong value. I have no other explanation for why would it not show colobot.exe using the memory if it really is.

**Comment by krzys-h** [comment]
Unless your graphics card doesn't have dedicated memory and it's shared with the system? It might then fill up your RAM, but the system might be unable to assign it to the colobot.exe process itself.

**Comment by RaptorParkowsky** [comment]
Yes, the same level after reboot takes another huge amount of memory.

In the second screenshot you can see a small app that shows basic infos about memory, but nothing more. Should I use something better?

My GPU is Nvidia GeForce FX5200, with 256 MB VRAM DDR. And I doubt that is graphic issue. If the game would detect no VRAM there and place everything in SWAP and RAM then all 3D visuals probably would work more slower, but now it's still half-playable. I guess it's somehow related with new loading screen unfortunately.

**Comment by krzys-h** [comment]
Do you remember what was the first version when you saw this issue?

I remember that when I was using Windows more often, if the system Task Manager was not enough, I used [Process Explorer](https://technet.microsoft.com/pl-pl/sysinternals/bb896653.aspx?f=255&MSPPError=-2147217396). It can do some cool stuff like showing open file handles etc. You can see, maybe it will show this memory as allocated to system or something.

**Comment by RaptorParkowsky** [comment]
I don't remember what was the first build that start to behave like that. I first noticed that something is wrong about a week ago when there was a bug with very long time loading. Now, after fixing that bug, the game still loads slower than the original, but no more than about 10 seconds.

I'll do the tests with Process Explorer and tell you if something interesting I discover.

**Comment by RaptorParkowsky** [comment]
Process Explorer shows nothing new. After few reloadings of Mission 2.4 (because it's one of the simlest maps):
![schowek01](https://cloud.githubusercontent.com/assets/4019345/9261275/1ad28d2c-420d-11e5-9864-11001e5d4fe8.png)

I guess the game just leaves old cache data ("Private Bytes") to the system instead of simply /dev/nulling them. The "Private Bytes" of the process are in quite good shape, without any memory leaks. There was a refactoring of the SDL implementation here, right? Maybe something wrong with that in only Windows XP and earlier?

**Comment by krzys-h** [comment]
There was no SDL refactoring, at least not yet.

I just checked under Linux. It appears that there is indeed a memory leak somewhere, as the memory for the process is actually rising.

**Comment by krzys-h** [comment]
0258b63d39757abc813ee3d45477b7c516338393
