### ISSUE TITLE
Remove all scene related graphic settings

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#556]
I think the options in graphics settings that are scene related (elements that depends of the level amount of assets) can be removed. They aren't very difficult for rendering and they are more plot-related things. More rasonable will be a option that reloads and converts some textures into lower resolution (for example original 2048x2048 textures into 512x512 or other resolution for planets, lens-flares and skies) instead of completely turning-off them.

![schowek01](https://cloud.githubusercontent.com/assets/4019345/9262211/63917504-4213-11e5-9b81-be9185d80bc9.png)

Another thing is "Dynamic lightning" and "Marks on the ground" settings. How those two works in GOLD? I can't see any difference. Maybe something related with original Colobot? What to do with them?

**Comment by krzys-h** [comment]
"Marks on the ground" is the GroundSpot in scene files + ability to show if the terrain is flat.
I'll have to check what the "Dynamic lighting" does.
I don't think "Num of decorative objects" makes much of a difference but I'd leave it for now.
I'd also leave the option to disable fog because it can be irritating sometimes.
I think Dust might stay for now, this basically enables/disables the second (dirt) textures
I agree on removing all the other settings.

**Comment by RaptorParkowsky** [comment]
So, "Marks on the ground" can be removed as well I think.

Well, in the future I think we could somehow connect fog setting with particles so I thought we could remove it now or later.

Dust textures are related with scene. There's a different for wrecks/ruins and different for working stuff. Well, it's good, when some GPU have only 2 texture units and the user/player to activate dynamic shadows can just disable dust textures, but still, this changes too drastically in the design and feel of the objects in the game. There is only one place, where dust textures doesn't fit - Code Battles. But in this case we can simply don't add SecondTexture parameter into the main level file.

**Comment by krzys-h** [comment]
From the code, it looks like "Dynamic lighting" disables shadows, "effect light" that should be visible on Scribbler and ApolloLEM (whatever that is), CPyro lights (basically in some effects like explosions etc), during building and generated by Shielder shield. So, basically disables all dynamicaly created lights :laughing:
If you want to see more, check out the light debugger @piotrdz implemented long ago. F10 or F11 I believe.

Actually, CEngine has two functions for accessing this value - Get/SetLightMode and Get/SetLightingMode. The second pair seems to be unused.

**Comment by krzys-h** [comment]
For now, I've left Dust (might be useful for debugging at some point), Fog (can be irritating) and Dynamic lighting (because I'm not sure what it does).
