### ISSUE TITLE
Ground texture partially disapear when flying/building

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#558]
Somehow it's reproductible only on the Moon missions:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/9271650/eddd2a38-427b-11e5-873a-4c07da991614.png)
![schowek03](https://cloud.githubusercontent.com/assets/4019345/9271668/fa8dc6de-427b-11e5-93d2-8d0ee0517140.png)

**Comment by krzys-h** [comment]
I've never seen it and can't reproduce. Do you have some more detailed reproduction steps? Exact configuration (especially shadow mapping)?

**Comment by RaptorParkowsky** [comment]
```
MipmapLevel=8
Anisotropy=8
ShadowColor=0.5
ShadowRange=0
MSAA=2
FilterMode=2
ShadowMapping=1
ShadowMappingQuality=0
ShadowMappingResolution=2048
```

Maybe something wrong with 4 multitexture units vs "marks on the ground" setting? I tried to disable that but ground still disappear.

**Comment by RaptorParkowsky** [comment]
I just discovered that on Crystalium levels (4.1, 4.3, 4.4 and Free game level) that also happens all the time, but no in the Mission 4.2. Also some Exercises on Crystalium have the same problem.

**Comment by krzys-h** [comment]
"Marks on the ground" uses the second texture, the same that objects use for dirt, so that's not related.

**Comment by RaptorParkowsky** [comment]
With recent build that doesn't happen, strange...
