### ISSUE TITLE
Can't departure with SpaceShip in other levels than Mission 1.3

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#561]

**Comment by krzys-h** [comment]
Can't reproduce this.

**Comment by RaptorParkowsky** [comment]
That's very strange. Sometimes the departure button simply don't react. For example in 1.3 I must put down the BlackBox on board or grab it back into TrackedGrabber's hand to make this work. It feels completely random.

**Comment by krzys-h** [comment]
8c617badae52fa4ea1f8b20806d59d00f40c2013 *might* have fixed that because it also fixed a problem with AudioChange that I found earlier. Could you check that?
Also, is it that the button doesn't react or it reports the the mission as not complete yet?

**Comment by krzys-h** [comment]
Oh, just reproduced it, it's still there

**Comment by krzys-h** [comment]
Seems to work when executing takeoff from CBot, so this is only a UI bug
```C++
extern void object::TakeOff()
{
    object item = radar(SpaceShip);
    item.takeoff();
}
```

**Comment by krzys-h** [comment]
That's funny. It depends on where you click - top and bottom of the button work fine, the middle does not :D

**Comment by krzys-h** [comment]
The same thing happens in the middle of ResearchCenter interface. Looks like the CAuto progress bar is still there, but invisible?
