### ISSUE TITLE
Try to save game on unhandled exception

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#572]
I know it's generally a bad practice to do anything more in a signal handler than notify the user about the problem, but it might be a good idea to give the player option to attempt creating a savegame at the moment of a crash - both for preventing progress loss and futher investigation of the issue. Of course, there must be a warning that the game is in an inconsistent state and this may fail terribly.

**Comment by tomangelo2** [comment]
Such save could have a prefix like "prefail" (nothing better came to my mind)
