### ISSUE TITLE
Astronaut gets too much damage

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#578]
It looks like with recent changes the astronaut gets too much damage. It's really good luck to pass Mission 3.2 in the AlienAnt's valley now.

Probably also the bots are now too fragile, I'll be testing that.

**Comment by krzys-h** [comment]
Could you check what was the average damage per one hit in 0.1.5?

**Comment by RaptorParkowsky** [comment]
I don't know how. It's hard to get only one AlienAnt's orgaball.

**Comment by RaptorParkowsky** [comment]
Well, comparing with original Colobot it looks like the Astronaut is getting about 2x or 3x more damage. But with robots propably is everything fine.

**Comment by Erihel** [comment]
Maybe this have something to do with fall damange?

**Comment by krzys-h** [comment]
No, it has to do with the new CObject interface, precisely with CDamageableObject::DamageObject refactoring

**Comment by krzys-h** [comment]
Should be good now
