### ISSUE TITLE
AudioChange doesn't work

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#580]
Reproduction: Mission 3.3 after powering up the Shooter.

**Comment by krzys-h** [comment]
I had this issue at some point but when I wanted to test, it was gone... Did you notice anything special that may be related?

**Comment by RaptorParkowsky** [comment]
It's strange, but when I firstly go into PowerStation to recharge Shooter's PowerCell, the music just started. Maybe something bad with PowerCell's detecting?

**Comment by krzys-h** [comment]
Yesterday it was broken and it was reproducible every time, today I want to fix it and the issue is gone :/ Any other hints on conditions under which this occurs?

**Comment by RaptorParkowsky** [comment]
I think we can move that issue to 0.1.7 milestone. It's very minor bug and the most probably AudioChange will be replaced by Level Controller's script.

**Comment by RaptorParkowsky** [comment]
Now AudioChange worked when I used 'fullenergy' cheat at the WingedShooter with completely discharged PowerCell.

**Comment by tomangelo2** [comment]
I've recently noticed that music changed after I killed all AlienAnts in mission 3.3
