### ISSUE TITLE
Autosave strange error

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#584]
Sometimes, when game tries to make autosave, the window with error pops up, but the game is still working. The autosave have no screenshot in load game screen (it's not even saved) and the animation of floppy diskette in top right corner simply can't disappear. The game is still playable though.

By the way, I also propose that would be nice if animation of diskette would appear on screen 5 seconds before autosaving, especially if there's still a little lag while making the autosave.

**Comment by RaptorParkowsky** [comment]
![schowek01](https://cloud.githubusercontent.com/assets/4019345/9363420/9d0c04ec-46a6-11e5-9328-b02af5da1719.png)

**Comment by krzys-h** [comment]
There is really no noticeable lag on my computer, and even if there is, it's definetly smaller than a tenth of a second and doesn't cause any sudden animation jump (it doesn't make one big update after that).
Does clicking "close" actually close the game or not? Looks like the screenshot saving thread is crashing for some reason, but I wouldn't expect the OS to kill only one thread...
Also, why our signal handlers don't work? I was pretty sure they are per-process not per-thread.

**Comment by RaptorParkowsky** [comment]
Well, on my computer there's still little, but noticeable and uncomfortable lag that stops the game's simulation for about half of the second.

If I click on Close in that error window, the game also closes. Even if I close the game in normal way though the menu, that window still is on the desktop until I close it manually.

**Comment by krzys-h** [comment]
Debugging that might be really hard without the gdb stacktrace :/ Could you try to get that?
After you download "gdb" from somewhere, run it from the commandline like that:
```
path\to\gdb.exe colobot.exe
````
after you see the *(gdb)* prompt:
```
run
```
and after it crashes (the game should freeze on crash and you'll see some output in the debugger):
```
backtrace
```

**Comment by krzys-h** [comment]
Actually, try now. I think I fixed it.

**Comment by RaptorParkowsky** [comment]
I can confirm that's fixed now.
