### ISSUE TITLE
%lvl% handling when loading saved games (Friendly spider)

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#586]
Latest dev only.
Install the level and load the savegame at https://github.com/colobot/colobot/issues/585, fly to the spider at N - NE from current position. It does not react. I don't see any warning in the log (e.g. that its script could not be started, etc.). So it's very strange.
Even when you try to aim it, the crosshair disappears and can't shoot it (in 0.1.5 it does not happen, although the spider is also peaceful there).
Its seems to be the case with the ants, too.

**Comment by RaptorParkowsky** [comment]
The second part of that issue is related with already existing #581 

Could you try to check if AlienSpider's script is running by pressing "~" on keyboard and activating "selectinsect" cheat?

**Comment by attila123** [comment]
When I select the spider there is a program in it, but it's empty, copy-pasting it:

extern void object::NewProgram()
{



}

Again, there are no Error or Warning message that its script could not be loaded.

**Comment by krzys-h** [comment]
I think I know what causes that. I'll fix this tomorrow.

**Comment by attila123** [comment]
I think the bug is connected to saving or loading.
In the scene.txt I changed my WheeledGrabber to WingedGrabber (and added 'DoneResearch type=WINGER' so that it can fly) and flied next to the Spider and it exploded correctly destroying the WingedGrabber.
But I also tried to fly to the Spider, but not close to it, save the game and load it, and then the Spider no longer 'worked'.

**Comment by krzys-h** [comment]
The bug is that the %lvl% tag doesn't work when loading saved games

**Comment by attila123** [comment]
Thanks for the fix, works like a charm. :) %chap% also works.
