### ISSUE TITLE
AlienNest is indestructible

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#588]
Earlier that object could be burnt after two shots from Shooters

**Comment by krzys-h** [comment]
After TWO shots? Makes no sense to me, why would it even be shielded?
Anyway, wouldn't it be better if it was actually indestructible? After you destroy it, you can't pass some missions that require you to get OrgaMatter. And it would make the Wasps a bit more challrngibg.

**Comment by RaptorParkowsky** [comment]
In original Colobot in fact that two shots was enough to destroy that object. There was even a bug that this object changed into wreck that could be recycled if I remember correct.

I propose that to make AlienNest destructible again, but now it should be harder to destroy and it souldn't turn into wreckage and also should healing itself like Astronaut, as this is organic entity that produces OrgaMatter.

**Comment by hexagonrecursion** [comment]
`obj->Implements(ObjectInterfaceType::Damageable)` returns false for AlienNest

https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/graphics/engine/particle.cpp#L3570

Probably needs to be fixed here:

https://github.com/colobot/colobot/blob/b2a0deaabb8b6fd256a3cdd54057b03bca388e90/colobot-base/src/object/old_object.cpp#L807-L880

**Comment by hexagonrecursion** [comment]
It also needs to be Destroyable and either Fragile or Shielded.

**Comment by hexagonrecursion** [comment]
Fragile explodes on the first hit. Shielded is (nearly?) indestructible. I need to spend more time staring at COldObject::DamageObject

**Comment by hexagonrecursion** [comment]
Actually. No. Not nearly indestructible. It takes about 9 shots from a regular shooter to kill it.

**Comment by hexagonrecursion** [comment]
I'm not sure why it was 9 yesterday. Today it takes about 25+-2 seconds of continuous fire. For reference: a fully charged standard battery is only good for about 9 seconds of continuous fire.

**Comment by hexagonrecursion** [comment]
PhazerShooter destroys the nest in 4 to 5 seconds of continuous fire (for reference: a fully charged standard battery is good for 5 seconds of continuous fire). Note, however that damage is very dependant on aim: aim a bit off and it becomes 8 seconds.

A regular bot is destroyed in 25+-2 seconds by a shooter and in 3 seconds by a phazer.

It appears that making AlienNest Shielded gave it the same hit points as a bot.

**Comment by hexagonrecursion** [comment]
I see where the number 9 came from. I thought that pressing the "Shoot" button shoots for 1 second. It turns it it shoots for about two seconds. Yesterday tests: kill in about 18 seconds. Today's tests: same code (?) 25+-2 seconds
