### ISSUE TITLE
Unhandled exception handling in various OS-es/platforms

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#590]
For clarity I create a separate issue from the discussion at https://github.com/colobot/colobot/issues/585.
The problem faced in Linux was that from a few days ago getting stack backtrace when colobot crashed was not possible.

Copying the last comment from @piotrdz:

"@krzys-h, @attila123: I tried again to get the previous version of unhandled exception code working under MSVC and I found out two things:

1) The original problem I experienced (std::set_terminate not working under any circumstance) was actually caused by OpenAL (or at least some code in openalwrap.dll). When I recompiled with OpenAL sound disabled, std::set_terminate started working as expected.

2) However, even when I got std::set_terminate to work, the code which gets current exception and re-throws it in CSignalHandlers::HandleUnhandledException(), does not work. Instead of rethrowing the expected exception, it throws std::bad_exception. I will try to investigate it further, but it is really tricky, as running it in debugger changes behavior of the program."

**Comment by attila123** [comment]
Hi, without knowing the code and understanding the details would it be possible to provide some workaround so that colobot's exception handling would work the best possible way on MSVC and Linux, too?
I imaginge some class could detect the OS type, with e.g. #ifdef-s. The OS type could be some enum. Maybe there is even such class, I don't know.
Then the exception handling code could check the OS type and do the best decision based on that.
Maybe provide instructions for MSVC how to get useful crash reports (e.g. colobot built in Debug mode, sound disabled, or whatever is needed).
Again these are just my guesses...

**Comment by piotrdz** [comment]
I see now that the issue from my second point cannot be resolved because of bug in MSVC itself:
https://connect.microsoft.com/VisualStudio/feedback/details/988432/std-current-exception-returns-null-when-called-from-terminate-handler. We can still use the handler function, but it's usefulness is limited, because we cannot tell what exception was thrown :-/

**Comment by attila123** [comment]
@piotrdz, thanks for the research done for MSVC! I understand there are difficulties on Windows, but it would be really good to fix the stack backtrace printing in Linux, otherwise it's not possible to give meaningful bugreports for any possible random crash. Sorry for pushing this... :)

**Comment by krzys-h** [comment]
I've changed the code to use set_terminate (551710646b12753225c721848da0ed8ba9519fa6) and added a note about the MSVC bug to the error dialog (1519145c4c0a7d9199d0a04309fdc05a9b329a51).
@piotrdz Could you check if the bug with the handler not being called can be worked around by calling CSignalHandlers::Init again after OpenAL initialization?

**Comment by piotrdz** [comment]
So finally after another productive hour spent with MSVC, I got everything to work, including OpenAL. The solution as it turns out is not to use the crappy Creative OpenAL implementation, but OpenAL Soft. You have to dowload OpenAL Soft and compile it from source and use the compiled .lib file.
Current Colobot code works without changes - on throwing unexpected exception, generic error message is displayed as expected.

**Comment by attila123** [comment]
@piotrdz thanks for the research for this.
Is this change in build about OpenAL soft .lib file already implemented for the Jenkins build for Windows?

**Comment by krzys-h** [comment]
I didn't change anything in CI Windows builds since they are not compiled with MSVC and the bug does not occur there.
"Failed to create audio source" is a known bug, I don't really know the sound implementation but I guess somehow some sound channels are not being freed after sound is finished

**Comment by piotrdz** [comment]
@attila123: CI Windows builds already use OpenAL Soft. You can reopen #331 or create a new issue, and post steps to reproduce this issue reliably. I will take a look at it.

**Comment by attila123** [comment]
@piotrdz Thx, I created issue #615 .
