### ISSUE TITLE
Compatibility for color handling

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#591]
Hi,
This is just an improvement request, although not sure how important it is. But I propose this issue anyway, because the implementation may not be difficult.
Manually converting custom levels created for the original colobot to colobot gold does not seem to be hard: based on colobot log a lot of things can be figured out and changed easily, except one thing: the values for the colors.
In original colobot the color values range seem to be from 0-255, in colobot gold 0-1.
If you leave the original color values in the scene.txt, you can notice some strange things: e.g. plants with white leaves, minimap not working (but all white), very light, almost white-ish buildings.
It would be nice to have warning messages if any of the component of a color is greater than 1.
In addition to this warning , I think in this case the best to do would be to automatically convert the color to the 0-1 range by dividing all of its component by 255 (and also print a warning message about this conversion).
Then it would be much easier to convert the custom levels back and forth, because one would not have to care about the color values.
Also, some people might prefer to specify colors in the 0-255 range.

**Comment by RaptorParkowsky** [comment]
I also don't like new color system. It's not user friendly and it's hard to get color code in that system from most of the graphic software.

**Comment by krzys-h** [comment]
But in OpenGL, storing the colors in range 0-1 makes sense because it's native to the graphics engine. See https://en.wikibooks.org/wiki/OpenGL_Programming/Basics/Color. I'm not saying we can't add a conversion during loading though - that's also possible.

**Comment by tomaszkax86** [comment]
That's false. Normalized range 0-1 in floats is not truly native to OpenGL, it's just convenient for calculations because you don't have to renormalize values. OpenGL is free to use whatever it can, even fixed-point values on embedded systems without FPU. Normalized integers in range 0-255 are also available and they give the same results, so I don't see the reason why we use floats for storage and waste space in vertex attributes (16 bytes versus 4 bytes, per vertex). As for levels, 0-255 values are preferable because RGB space in most programs uses 0-255 range and that's what most people are familiar with. Besides, we can convert 0-255 integers to 0-1 floats during loading scene files.

One solution would be to implement both ways and introduce scene command to change value specification. How about:

```
SceneConfig values=int             // 0-255 range
SceneConfig values=float           // 0-1 range
```

I think default should be ```int``` to bring back compatibility with original scene files. ```SceneConfig``` can be later extended to add more scene configuration options.

**Comment by tomangelo2** [comment]
@tomaszkax86 Good idea. We could resume compatibility with original scene files (or at least converting will require less work) and maybe it may expand our possibilities in creating Scene commands.

**Comment by MrSimbax** [comment]
It would be great to have also hex values `#rrggbb`. They are convenient and used widely especially by web developers.

**Comment by attila123** [comment]
Thanks for the lot of constructive feedback!
@tomaszkax86: sorry, but I disagree with the SceneConfig settings. I think the best would be if the app would automatically detect if the color is in a 0-1 or 0-255 or #rrggbb format.
#rrggbb is of course easy to distinguish, as it starts with '#'. If not #rrggbb, then if any of the r, g, b component is > 1, then consider it 0-255 range, otherwise 0-1 range.
Why is it good?
Colors, like 0,0,1 have no practical use in the 0-255 range, so for practical purposes the conversion is unambiguous.
Level designers don't have to care/worry about which color format to use. E.g. one could possibly copy-paste things in both formats to a scene file, and it would still work automagically.
What should be done if 'SceneConfig values=float' is specified and still some color component is > 1. Display warnings, errors? Or do the conversion? -> this only compicate things...
So in my opinion these SceneConfig options do not bring real value for level designers, just a bit of rigidness and complication (also for implementation), so they should not be introduced.

**Comment by RaptorParkowsky** [comment]
What about Alpha color? As far as I know, #rrggbb system doesn't support that. It would be helpful for custom level creators if, for example, robots and buildings or aliens would have possibility to have transparent color for "ghost" effect.

**Comment by MrSimbax** [comment]
http://stackoverflow.com/questions/15852122/hex-transparency-in-colors

**Comment by attila123** [comment]
Hi,
Colobot seems to have some alpha support (see e.g. parseparam.cpp, color.h), but I'm not sure whether it is fully functional though (can it be specified in scene.txt).
But let's focus on the most "burning" issue, the 0-255 range handling (for compatibility).

I created the following "patch" for that. Seems to work good (tested with new and old syntax MapColor lines).

Sorry I didn't bother with diffs or pull requests for now, maybe next time.
Original code in parseparam.txt:

```
Gfx::Color CLevelParserParam::AsColor()
{
    if (m_empty)
        throw CLevelParserExceptionMissingParam(this);

    ParseArray();

    if (m_array.size() == 3) //RGB
    {
        return Gfx::Color(m_array[0]->AsFloat(), m_array[1]->AsFloat(), m_array[2]->AsFloat());
    }
    else if (m_array.size() == 4) //RGBA
    {
        return Gfx::Color(m_array[0]->AsFloat(), m_array[1]->AsFloat(), m_array[2]->AsFloat(), m_array[3]->AsFloat());
    }
    else
    {
        throw CLevelParserExceptionBadParam(this, "color");
    }
}
```
New code that I propose:

```
Gfx::Color CLevelParserParam::AsColor()
{
    if (m_empty)
        throw CLevelParserExceptionMissingParam(this);

    ParseArray();
    
    if (m_array.size() !=3 && m_array.size() != 4) {
        throw CLevelParserExceptionBadParam(this, "color");
    }

    float red = m_array[0]->AsFloat();
    float green = m_array[1]->AsFloat();
    float blue = m_array[2]->AsFloat();
    float alpha = (m_array.size() == 4) ? m_array[3]->AsFloat() : 0.0f;
    
    if (red > 1.0f || green > 1.0f || blue > 1.0f) {
        red = red / 255.0f;
        green = green / 255.0f;
        blue = blue / 255.0f;
        alpha = alpha / 255.0f;
    }
    
    return Gfx::Color(red, green, blue, alpha);
}
```

I wondered if it would be better to put this check in Color's constructur (it would be "safer" that way), but one can argue that it's a parsing issue instead.

If you agree with this change, could you please commit it to dev branch?

**Comment by krzys-h** [comment]
We could just put assert()s in the Gfx::Color constructor to make sure nobody tries to create it with values <0 or >1

**Comment by attila123** [comment]
Yes, in addition to my code, those assert()s in Gfx::Color are doable. Uncle Bob probably would not approve that, but... :)
Also, my code is working, but still ugly, would need to refactor the new 'if' code block to a new method, something like 'NormalizeColorComponentsRange'. Based on the asserts in Color constructor, I think this should go here, to this class (did not test this yet), something like this:

```
Gfx::Color CLevelParserParam::AsColor()
{
    if (m_empty)
        throw CLevelParserExceptionMissingParam(this);

    ParseArray();

    if (m_array.size() !=3 && m_array.size() != 4) {
        throw CLevelParserExceptionBadParam(this, "color");
    }

    float red = m_array[0]->AsFloat();
    float green = m_array[1]->AsFloat();
    float blue = m_array[2]->AsFloat();
    float alpha = (m_array.size() == 4) ? m_array[3]->AsFloat() : 0.0f;

    NormalizeColorComponentsRange(red, green, blue, alpha);

    return Gfx::Color(red, green, blue, alpha);
}

/**
 * For compatibility with the 0-255 range for color components used in original Colobot scene files.
 * See https://github.com/colobot/colobot/issues/591.
 **/
void CLevelParserParam::NormalizeColorComponentsRange(float& red, float& green, float& blue, float& alpha)
{
    if (red > 1.0f || green > 1.0f || blue > 1.0f || alpha > 1.0f) {
        red = red / 255.0f;
        green = green / 255.0f;
        blue = blue / 255.0f;
        alpha = alpha / 255.0f;
    }    
}
```

Or maybe use IntColor and IntColorToColor from color.h ??

**Comment by attila123** [comment]
I am not familiar with git and don't want to do all the magic for the pull request just yet (maybe if I propose further changes).
Could somebody submit this code?
I tested it and it works.
So basically you need to replace the CLevelParserParam::AsColor() implementation as shown above, and add new private method NormalizeColorComponentsRange (of course add it to parseparam.h as well).
I understand that this is the bare minimum to support this functionality, so you may of course improve upon this code.
I think for #rrggbb and #aarrggbb support a new issue would be better, so that we can close this one (when the code is comitted).
