### ISSUE TITLE
Shielder's battery don't stop sparking in 9.4

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#601]
After removing a battery it stop sparking, but after inserting a new one, it continue sparking.

**Comment by RaptorParkowsky** [comment]
I couldn't reproduce that in any way. It happen with NuclearCells or PowerCells or both?

**Comment by tomangelo2** [comment]
With both.

**Comment by RaptorParkowsky** [comment]
I still can't reproduce this sparking without stopping. Was the shield activated when NuclearCell was discharging?

**Comment by tomangelo2** [comment]
No. Right after starting mission it start sparking (like always), but it didn't stop.

**Comment by krzys-h** [comment]
Is this actually reproducible or did this happen only once?

**Comment by tomangelo2** [comment]
Reproducible, but looks like it happen only in some configurations. On my second PC it doesn't occur.

**Comment by krzys-h** [comment]
Could you see what ```message(this.energyCell.energyLevel);``` in CBot returns?

**Comment by tomangelo2** [comment]
2.00

**Comment by krzys-h** [comment]
That's clearly wrong, the range of this value should be 0-1...

**Comment by tomangelo2** [comment]
For fresh NuclearCell it's 10

**Comment by krzys-h** [comment]
That value is really 0.2 and it should be fixed already - but this is unrelated to this issue

**Comment by krzys-h** [comment]
I doubt this is going to change anything but please try that

**Comment by tomangelo2** [comment]
Fixed
