### ISSUE TITLE
Add a button in main menu to open CBot documentation in SatCom

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#606]
Could be useful when you just want to quickly check something without loading any level

**Comment by RaptorParkowsky** [comment]
I agree with that proposal. Especially that we don't have any official SatCom Online Viewer at colobot.info yet and GOLD is supposed to be more like learning programming environment, not only just a game.

**Comment by MrSimbax** [comment]
No one seems to be against it, so I replaced `proposal` label with `accepted`.
