### ISSUE TITLE
White sky in the intro and in the first Moon mission

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#607]
Latest dev only. Does not happen in 0.1.5.
Select the first Moon mission "Titanium ore".
The sky is white in the intro (when spaceship flies), and also when the mission begins. Somehow after a while (during playing this level) the sky switched back to normal (at least on Windows, where I played it) - strange...
As you can see on the screenshot, the spaceship is quite bright as well.
(I don't know how to create screnshots (not listed in game Options -> Controls), not sure if it's possible at all, so I used some Linux screenshot program.)

![colobot-moon-1](https://cloud.githubusercontent.com/assets/1728046/9516154/0af5ed32-4ca7-11e5-9fe8-c31c79781531.png)

**Comment by attila123** [comment]
The first Orpheon mission "Logistics" has the same problem.

**Comment by tomangelo2** [comment]
Confirmed. But happen only when Film sequences is on. Fix after pausing the game, but after restart the sky become white again. With Film sequences this doesn't occur.

**Comment by krzys-h** [comment]
@piotrdz You removed some calls to CreateTexture() in that code, maybe thay were actually important?

**Comment by piotrdz** [comment]
@krzys-h: No, I don't think that's it - these calls were redundant, as later CEngine::SetBackground() is called, and there the texture is created.

**Comment by piotrdz** [comment]
Turns out I was wrong - there were pair of CreateTexture() and DeleteTexture() calls. I now removed also DeleteTexture() and it seems to work. This has the side effect of the textures remaining loaded in memory, but we can leave it like that for the present. I am going to refactor the texture code anyway.
