### ISSUE TITLE
Full screen problem with Intel HD 3000 in dev branch

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#608]
Hi,

I just tried the latest dev debug build for Windows (before that, I only tried 0.1.5 on Windows). It works in windowed mode, but when I try to switch to full screen mode, the 2D graphics (buttons, dialogs, sparkles when moving the mouse) are still working, but even the background is not there in the main screen, but instead it's black. When starting a level, again the 2D things are OK, but the 3D it's totally grey.
colobot-gold-alpha-0.1.5-win64-portable.zip works correctly (at least I tried with the Dell driver, see below), so it's something introduced after that.
System details:
Dell Latitude E5420 laptop, which has second generation Intel Core i5 processor (2520m), and Intel HD 3000 integrated graphics card.
Windows 7 SP1 64bit.
I tried with 2 graphics drivers:
- latest available from Intel
https://downloadcenter.intel.com/search?keyword=2nd+Generation+Intel%C2%AE+Core%E2%84%A2+Processors+with+Intel%C2%AE+HD+Graphics+3000%2F2000
Date: 6/23/2015
Version: 15.28.24.64.4229
- Older driver available from Dell:
http://www.dell.com/support/home/us/en/04/Drivers/DriversDetails?driverId=XGPWM
Version 9.17.10.3040, A12
Release date 26 Mar 2014
Last Updated 29 May 2014

On another machine (Win 7 SP1 32 bit, with different (AMD) graphics card), even this dev version works perfectly. So I assume it's something specific with the Intel driver.

Hmm, I just found a workaround: still in full screen I need to change the resolution (from any resolution to any resolution), and it fixes the game graphics, and it stays good even after starting a level. However if I Alt + Tab out and back into the game, the graphics is bad again, so again I have to do the screen resolution change workaround.
Now I remember I also needed to do this resolution change trick in the original colobot game on this laptop to stop the graphics flickering (difficult to describe).

The log (getting to the main screen and change the resolution):
```
[INFO]: Colobot: Gold Edition 0.1.5+alpha-git-HEAD~r934d97a starting
[INFO]: Creating CApplication
[WARN]: Language path './lang' is invalid, assuming translation files not instal
led
[INFO]: Data path: ./data
[INFO]: Save path: ./saves
[INFO]: Error on parsing config file: No such node (Language.Lang)
[DEBUG]: Default system locale: English_United States.1252
[DEBUG]: Setting locale: LC_COLLATE=English_United States.1252;LC_CTYPE=English_
United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=E
nglish_United States.1252
[WARN]: Failed to update locale, possibly incorect system configuration. Will fa
llback to classic locale.
[DEBUG]: SetLanguage: Test gettext translation: 'Colobot rules!'
[INFO]: Opening audio device...
[INFO]: Done.
<loading of audio files>
[INFO]: CApplication created successfully
[INFO]: No joysticks detected
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 3.1
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 16
[INFO]: Multisampling supported, max samples: 4
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 8
[DEBUG]: Framebuffer supported
[INFO]: CDevice created successfully
[INFO]: Closing joystick
[DEBUG]: Music loaded from cache
[INFO]: Created shadow map texture: 2048x2048, depth 32
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 3.1
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 16
[INFO]: Multisampling supported, max samples: 4
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 8
[DEBUG]: Framebuffer supported
[INFO]: CDevice created successfully
[INFO]: Created shadow map texture: 2048x2048, depth 32
[DEBUG]: Music loaded from cache
```

**Comment by krzys-h** [comment]
0.1.5 restarted the whole game in order to apply resolution changes, that's why it worked before. I was pretty sure I've fixed the resolution change already, that's why I removed the old workaround. It works fine for me.
It's probably a Windows-only issue, since SDL's resolution change code on Windows is different and resets the OpenGL context.

Windows 8.1 (64-bit)
Intel HD Graphics 4600

**Comment by RaptorParkowsky** [comment]
For me changing resolutions and fullscreen/windowed mode while displaying 2D and 3D graphics works fine with very old software/hardware.

Windows XP 32-bit
GeForce FX5200

So that's probably indeed Intel problems.

**Comment by attila123** [comment]
Hi @krzys-h, you say that 0.1.5 the game had to be restarted because of the resolution change (so somehow the resolution change was the problem?), but in my case it's the resolution change that helps to correct the problem. So I am not sure if we are talking about the same issue.
If the game was in full screen, it starts with the display problem. 0.1.5 seem to somehow better init the graphics, because it works fine starting up in full screen, no resoulion change is required.

But for me it's not that important, so for me it's OK to close this as "won't fix".
When I started to write the bug report I didn't know that workaround existed and how frequent the problem is regarding graphics hw.

**Comment by attila123** [comment]
Also in 0.1.5 I can alt + tab out of the game and back in without needing to correct the graphics in this laptop. So it's not even just connected to the resolution change.

**Comment by krzys-h** [comment]
Try this and see if it changes anything

**Comment by attila123** [comment]
Tested with latest build 102.
Thanks for your effort, but unfortunately it works the same way as earlier: if switched to full screen or game started in full screen I have to do the resolution change trick to get the graphics fixed. I also have to do this trick after alt + tab-ing out from the game and switching back to it.

**Comment by krzys-h** [comment]
Could you try the latest dev builds after the SDL2 migration and see if this issue still exists?

**Comment by attila123** [comment]
I will try to test in the evening, thanks.

**Comment by attila123** [comment]
Works perfectly! :)
Great work!

**Comment by ivanovmv** [comment]
Have this issue with MSAA set to more than 1
I am ruining latest windows-debug version with 1366x768 full screen resolution on my Windows 10 Pro x64 with@Intel Core i5 2410M laptop.
Issue appears after Alt-Tab and can be fixed by setting MSAA to 1 but.
In other words you can use MSAA only until first Alt-Tab.

**Comment by krzys-h** [comment]
@tomaszkax86 MSAA related, please take a look
