### ISSUE TITLE
Lots of ants now on Terranova 4

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#611]
I noticed that now playing with latest dev there are quite a lot of ants on Terranova 4. See the savegame at bug #610. There seems to be 64 in data.sav (before that there were also a save with 72). Maybe some object creation limit was lifted at some point in time? Earlier there were not so many ants in this level, I believe. Don't know when it has changed. In orginal colobot I surely don't remember that many.
I guess the maxiumum population limit for insects should be configurable per AlienAnt (meaning more AlientAnt on the same user level would allow more).

**Comment by krzys-h** [comment]
ipf() in CBot is broken and that probably speeds up the AlienQueen. There is an issue about that somewhere.

**Comment by attila123** [comment]
Ah OK. The mission is definitely more challenging this way. :) Will need to check if I can beat it or not. :)
I think the corresponding issue is #410 .

**Comment by attila123** [comment]
Can be tested with savefile posted at #617 . Stop the AlienQueen's program and move it a bit further away from the hill, because of her goto() problem. Then start the program again to produce eggs.

**Comment by tomangelo2** [comment]
I think I've found another reason. In [AlienQueen's script](https://github.com/colobot/colobot-data/blob/master/ai/lady02.txt) there is a line 
```
if ( AlienCount() < 10 )
{
[...]
produce([...]);
```
but it seems like AlienCount() always return 0, so AlienQueen is producing AlienAnts endlessly.

**Comment by krzys-h** [comment]
Really? Then I'll look into this before 0.1.6

**Comment by tomangelo2** [comment]
Definitely there is bug in retobject(). I've tested that more, it turns out that this function cannot detect any building, alien or bot.

**Comment by tomangelo2** [comment]
retobject() is now fixed, and AlienQueen doesn't produce so much AlienAnts like previous.
AQ's script still produce AlienAnts, even when there is more than 9 AlienAnts on the map, but it's only 20% chances to produce another AlienAnt (if ( rand() < 0.2 )). This may require more testing, if there will be still too much ants, then maybe there will be added wait() command, otherwise this issue might be closed.

**Comment by krzys-h** [comment]
I'm pretty sure the 20% chance ants are a different kind, those are the ones that attack your base actively, where the others wait for you to come close.
I think the retobject() bug was the main reason of this, so I'm closing this for now.
