### ISSUE TITLE
AlienQueen created insects cause a lot of prog*.txt-s

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#613]
Hi,
This is just some improvement suggestion.
I noticed that on Terranova 4 there are lots of identical prog*.txt-s saved for the Ants created by the AlienQueen.
These are not all identical: for some reason, the ants do not have the same scripts, but there seems to be 3 kinds of scripts for the ants: these are 3028, 3030, and 3300 bytes long, scripts with same sizes are identical (diffed them).
I think it would be better if in the savegame the AlienAnt-s would reference their stock script (from the data/ai directory or from the user level's directory, but don't know how AlientQueen works exactly), or at least there would be only 1 txt file created per script.

**Comment by krzys-h** [comment]
AlienQueen does produce multiple types of ants, see the data/ai/lady.txt script.
I probably just forgot to mark the scripts from produce() as "loaded from data files" which causes them to be always saved

**Comment by attila123** [comment]
Well, I don't know, maybe the other scripts come from somewhere else?
Anyway the different scripts are visible in the savegame I shared for #610 : https://www.dropbox.com/s/3redpfap6yxvbg0/save1508290251Terranova4.zip Just sort the files by size.

**Comment by attila123** [comment]
On this level AlienQueen runs the lady02.txt script, that's the reason for ants with 3 different scripts.

**Comment by attila123** [comment]
Hmm, I tried to reproduce the problem with the savefile posted at #617 . I stopped the AlienQueen's program and moved it a bit further away from the hill, because of her goto() problem. Then started is program again to produce an egg. I tried to save and load in various stages of the egg, but I could always kill the produced ant even after loading.
So it seems it's not easy to reproduce.
So if you can't find the problem in the code, maybe a loading workaround regarding lock and zoom would be sufficient.
