### ISSUE TITLE
After loading a saved game, the first program is shown to be running

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#616]
This is a minor/cosmetic issue. Latest dev.
To reproduce:
- Start e.g. the Terranova 4 level
- Select e.g. the subber and add a simple new program with the code:
```
while (true) {
wait(1);
}
```
- Run this program
- Save the game and load it
- First program is shown to be running (however the new program is running)

**Comment by krzys-h** [comment]
I believe I marked it as TODO in the code and then forgot about it, sorry ;)
