### ISSUE TITLE
AlienQueen is "stuck" climbing a hill

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#617]
Hi,
This problem is probably from the original game. In this savegame here: https://www.dropbox.com/s/lvvmxzy3a03d3v7/save1508291228Terranova4.zip you can see as the AlienQueen is "stuck" climbing a hill. Probably the goto() implementation could be improved to avoid such situations.
The reason she decided to go that way may be that there were some ants around it (which I cleaned up with the orga shooter).
Although I understand it's not a top prio issue.
Got it with current dev.

**Comment by RaptorParkowsky** [comment]
This is probably connected with restarting the program after loading saved game. We'll fix that after refactoring of CBOT code.

**Comment by attila123** [comment]
No, it does not seem to be connected to loading. In fact it is a problem in the AlienQueen's goto() implementation. Just load the game, you can stop her program and start it again, and she tries to go through the hill again and can't.

Also I noticed another interesting problem. If I restarted her program when she was close to her first "waypoint", she just went around and around it. Looks like her turning capability is limited: can only slowly turn while moving.

**Comment by krzys-h** [comment]
That program is not really designed to be stopped and started again, it should just go through the points in order

**Comment by krzys-h** [comment]
Fixed by #199
