### ISSUE TITLE
AlienQueen is not visible on radar

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#618]
AlienQueen is not visible on radar. For example load the savegame I uploaded for #617 :
https://www.dropbox.com/s/lvvmxzy3a03d3v7/save1508291228Terranova4.zip .
Got it with current dev.

**Comment by RaptorParkowsky** [comment]
She was never visible by radar even in original Colobot EPSITEC's release. I think it should stay as it was, because RadarStation don't recognize that type of alien.

**Comment by attila123** [comment]
Well, I understand it worked like that in the orginal version of the game.
The question is: was it by design or was it a defect nobody noticed or did not care to fix?
For me it does not sound logical that this big insect is missed by the radar, unless she has special stealth capabilities. So I think it can be considered as a defect in the original version of the game.
I think if the fix is easy, it would be nice to fix.
Although perhaps it has little practical use to see the AlienQueen in the radar while playing the game.

**Comment by RaptorParkowsky** [comment]
Well, her visible on radar is still related with plot of the game. Missions (and the plot) will be refactored when GOLD will be at beta stage. Then every plot/gameplay detail will be considered to make the game more sedate. For now I would hear the statement from the other developers about AlienQueen's detecting.

**Comment by krzys-h** [comment]
I'm not sure. Maybe it was intentional that you had to find her yourself?
Fix should be really easy, probably just one line somewhere in ui/mainmap.cpp

**Comment by attila123** [comment]
Hmm, with the default script there are quite some ants around her, so not so difficult to find her anyway...
I think if difficult to detect insects would be needed from the plot/story point of view, it should be a separate feature.
Difficult to decide, either way it's good. Maybe better to be visible.
