### ISSUE TITLE
Checking if the ground is flat doesn't work

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#622]
The ground doesn't have green/red colors after clicking on the button:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/9654864/d36ef5ca-522d-11e5-8090-c95b89b90181.png)

**Comment by RaptorParkowsky** [comment]
With simple shadows this also doesn't work.

**Comment by krzys-h** [comment]
There was issue about that already, but I don't have time to find it now to link it here

**Comment by MrSimbax** [comment]
#404
