### ISSUE TITLE
radarall()

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#624]
An enhancement to CBot radar() function. Returns an array of objects matching given criteria, sorted by distance (according to the normal closest/furthest parameter).
```C++
object[] items = radarall(AlienAnt);
// items has all the ants in it
// items[0] is the closest one, items[sizeof(items)-1] is the furthest

assert(items[0] == radar(AlienAnt)); // items[0] is always equal to what a normal radar would return
```

**Comment by krzys-h** [comment]
radarall() has been just implemented. Use it like so:
```Java
object[] item; // CBot doesn't allow assigning to array in definition (:/)
item = radarall(AlienAnt);
for(int i = 0; i < sizeof(item); i++)
{
    message(item[i].id);
}
```
Of course you can also use all normal radar parameters.
I'm not closing this issue until proper documentation is written.

**Comment by MrSimbax** [comment]
042d15d0d32f7f04ff69b9ff36945ebe0e6e4db9
