### ISSUE TITLE
Synchronized methods in programming bots bug

### ISSUE THREAD

**Issue by MariuszPL55** [colobot/colobot#626]
"In Colobot 1.8 apparently anything that causes script execution on a particular bot to halt while it is executing a synchronized function will not reliably release the mutex. Hence all subsequent attempts to call that synchronized function (or any other synchronized function in that class) will block.

Events that can trigger this bug include the user pressing the "stop" button, the bot being destroyed, or execution halting due to an error. One possible workaround is to save, exit and re-load the game." - from Colobot Wiki.

I saw this bug in game, it is true.

**Comment by krzys-h** [comment]
The same happens if you use the mysterious undocumented try..catch syntax. Will be probably addressed after rewriting the CBot engine.

**Comment by krzys-h** [comment]
Fixed in #793
