### ISSUE TITLE
Burning sound is still playing after loading a game

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#631]
Reproduction: destroy a building or kill an Alien with Shooter and while it's burning, load a game. Sound of the fire will still play, even if currently nothing is burning.

**Comment by RaptorParkowsky** [comment]
I never experienced that on GOLD builds. I can remind that bug in several EPSITEC games, especially in BuzzingCars. I'm guessing this depends on sound card drivers/device and sound buffering. OpenAL implementation and sound samples also isn't perfect.

**Comment by krzys-h** [comment]
I remember having this issue at some point, never tried to reproduce it though.

**Comment by tomangelo2** [comment]
Should be fixed
