### ISSUE TITLE
game terminates when copy code

### ISSUE THREAD

**Issue by gorgabal** [colobot/colobot#637]
When you copy code in-game, it seems that the OS (Debian, in this case) interpreters this as an ctrl+c sequence, initiating termination. 
## how to reproduce:
1.  start game using 'startx colobot', (or, just launching the game without desktop-environment, I used awesomewm)
2. load a game
3. try to copy some code in the in-game editor.

**Comment by gorgabal** [comment]
Could be related to #183 ,

**Comment by Erihel** [comment]
Is this happening with recent dev builds? This could be a bug in freeing memory when using clipboard with SDL2 that was fixed in 9679546988ebe727800e5d82bf687438eee7611b

**Comment by krzys-h** [comment]
Unable to reproduce, closing
