### ISSUE TITLE
Custom functions not accepting "nan".

### ISSUE THREAD

**Issue by Mrocza** [colobot/colobot#642]
The folowing program will display "0" instead of "nan":

```
extern void object::Bug(){
message(echo(nan));
}
int object::echo(int i){
return i;
}
```

**Comment by tomaszkax86** [comment]
NaN is technically only defined for floating-point formats. There's no formal way to specify integer NaN, so I don't know how could this work at all. CBot probably handles nan constant specially, just like categories, so doing any operations will likely remove it's meaning from assigned variable.

**Comment by Mrocza** [comment]
For float variables the program I noted returns "0.00" instead of "nan"

**Comment by krzys-h** [comment]
It probably works just the same as the categories, doing anything with them just converts them to a regular int. This will be likely fixed during CBot refactoring.

**Comment by Mrocza** [comment]
One can check the category number by simply doing:

    message(WheeledGrabber+0);

Attempting to apply that trick to "nan" results in an error.
