### ISSUE TITLE
[Joystick] Button 0 is printing ? chars in Controls menu

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#646]
![colobot](https://cloud.githubusercontent.com/assets/4140449/10112449/913a7908-63db-11e5-8ed6-fe666be6d394.png)
Another buttons works well, probably dividing by 0 issue.

**Comment by krzys-h** [comment]
I don't think we're dividing by button number anywhere :P

**Comment by krzys-h** [comment]
Also note that this is on dev-sdl2 only, that's important :>

**Comment by krzys-h** [comment]
Actually, this is button 0 internally but button 1 in the UI it looks like

**Comment by krzys-h** [comment]
Actually, it turns out it's not only a latest dev issue ;)
