### ISSUE TITLE
[dev-sdl2] Entering cheat console put ` character in console

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#648]

**Comment by Erihel** [comment]
I looked at event processing and this is what I think. Console handles 2 events key down and text input. Key down shows console and later text input is processed and it results in ` in console. In **bool CRobotMain::ProcessEvent(Event &event)** I would try changing:

https://github.com/colobot/colobot/blob/dev/src/level/robotmain.cpp#L710-L711
to
`if (event.type == EVENT_TEXT_INPUT &&
event.GetData<TextInputData>()->text[0] == KEY(BACKQUOTE))  // Pause ?
{`

**Comment by tomangelo2** [comment]
Should be fixed
