### ISSUE TITLE
Problem with Hungarian keyboard

### ISSUE THREAD

**Issue by gyeben** [colobot/colobot#650]
I tried playing the game (version 0.1.6) under Windows 7 Ultimate (32 bit), but I can't use the code editor properly, because I can't enter some characters, for example the semicolon. I think this issue is caused by using a Hungarian keyboard.

**Comment by krzys-h** [comment]
We have just finished migration to SDL2, which should improve support for different keyboard layouts. Could you please test the latest dev builds and see if the problem persists?
You can get them from our build server - http://compiled.colobot.info/jenkins/view/colobot-gold-download/ (you could also compile dev branch from sources if you prefer)

**Comment by gyeben** [comment]
http://compiled.colobot.info/jenkins/view/colobot-gold-download/ seems to be down at the moment.

**Comment by krzys-h** [comment]
It was indeed, but it should work noe

**Comment by gyeben** [comment]
The keyboard works perfectly with the latest dev build.
