### ISSUE TITLE
Add alternative way to rotate camera with joystick/keyboard

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#653]
Currently rotating camera is available only by sticking cursor to game window edge. There could be separate buttons to rotate a camera left/right. It could help playing on joysticks.

**Comment by krzys-h** [comment]
I started implementing this already earlier, in some modes you can use numpad keys to rotate the camera. There are no keybindings yet.

**Comment by krzys-h** [comment]
After bd72086704a6b61222a9708b848875585d84ae4e camera navigation with keyboard is mostly finished and joystick should be quite easy to implement
