### ISSUE TITLE
No texture movement/surface waving or other particle and sound effects in water and lava

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#659]
It looks like that bug was from almost beginning of the development of Colobot: Gold Edition.

I'm pretty sure in original Colobot there was such effects like:
* Texture movement:
It looks like the water/lava have 2 layers of the same texture that moves differently.
* Surface waving:
The mesh of the lava was randomly waving. I'm not sure about water though, probably not or just a little.
* Particle and sound effects:
Lava throws some sparks and smoke into the air. You can hear also gurgling of the lava.

Comparison:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/10201763/e8d34200-67ad-11e5-940c-368574712d79.png)
![schowek06](https://cloud.githubusercontent.com/assets/4019345/10201766/ef344c2a-67ad-11e5-9e1f-761c684cd3e2.png)

**Comment by krzys-h** [comment]
I can see that the code for that still exists, probably some bug with it not being called

**Comment by krzys-h** [comment]
Particle effects are now fixed, but moving the texture seems to be a different issue.

**Comment by krzys-h** [comment]
And this one is just a typo from when we were rewriting the level parser
