### ISSUE TITLE
Compiling under MAC OS X

### ISSUE THREAD

**Issue by ptiza-v-nebe** [colobot/colobot#664]
Always stuck on this when trying to compile like in INSTALL-MacOSX.md mentioned "Undefined symbols for architecture x86_64:"

What can I do?

*Scanning dependencies of target colobot
[ 58%] Building CXX object src/CMakeFiles/colobot.dir/app/main.cpp.o
[ 58%] Linking CXX executable ../colobot
Undefined symbols for architecture x86_64:
  "___sincosf_stret", referenced from:
      Math::RotatePoint(Math::Vector const&, float, float, Math::Vector&) in libcolobotbase.a(robotmain.cpp.o)
      Math::RotatePoint(Math::Point const&, float, Math::Point const&) in libcolobotbase.a(robotmain.cpp.o)
      Math::RotatePoint(float, Math::Point const&) in libcolobotbase.a(engine.cpp.o)
      Math::RotatePoint(float, Math::Point const&) in libcolobotbase.a(old_object.cpp.o)
      Math::RotatePoint(float, Math::Point const&) in libcolobotbase.a(motionhuman.cpp.o)
      Math::RotatePoint(Math::Point const&, float, Math::Point const&) in libcolobotbase.a(map.cpp.o)
      Math::RotatePoint(float, Math::Point const&) in libcolobotbase.a(map.cpp.o)
      ...
  "___strlcpy_chk", referenced from:
      -[SDLMain application:openFile:] in libSDLmain.a(SDLMain.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [colobot] Error 1
make[1]: *** [src/CMakeFiles/colobot.dir/all] Error 2
make: *** [all] Error 2*

**Comment by ptiza-v-nebe** [comment]
Now tried the "dev" branch with SDL2. One error gone, but still this:

[ 58%] Linking CXX executable ../colobot
Undefined symbols for architecture x86_64:
  "___sincosf_stret", referenced from:
      Math::RotatePoint(Math::Point const&, float, Math::Point const&) in libcolobotbase.a(robotmain.cpp.o)
      Math::RotatePoint(float, Math::Point const&) in libcolobotbase.a(engine.cpp.o)
      Math::RotatePoint(float, Math::Point const&) in libcolobotbase.a(old_object.cpp.o)
      Math::RotatePoint(float, Math::Point const&) in libcolobotbase.a(motionhuman.cpp.o)
      Math::RotatePoint(Math::Point const&, float, Math::Point const&) in libcolobotbase.a(map.cpp.o)
      Math::RotatePoint(float, Math::Point const&) in libcolobotbase.a(map.cpp.o)
      Math::RotatePoint(Math::Point const&, float, Math::Point const&) in libcolobotbase.a(lightning.cpp.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [colobot] Error 1
make[1]: *** [src/CMakeFiles/colobot.dir/all] Error 2
make: *** [all] Error 2

**Comment by krzys-h** [comment]
Which version of OS X are you using?
I don't have a Mac personally to test, but looks like you might have to mess with SDK versions to fix this - http://stackoverflow.com/questions/19015780/sincos-stret-undefined-symbol-when-linking

**Comment by ptiza-v-nebe** [comment]
Good evening! Thank you for your answer! :)

I have tried already under Mountain Lion 10.8, Mavericks 10.9 and now Yosemite. With both Master and dev branches.

Now under Yosemite it seems to compile. I could successful build a package, but when I try to run it is immediately closing colobot.
I tried to run directly the colobot file under Colobot.App/Contents/MacOS in the package. 
Then I get this error:

[INFO]: Colobot: Gold Edition 0.1.6+alpha-git-dev~r0aa97fe starting
[INFO]: Creating CApplication
[INFO]: Data path: /Applications/Colobot.app/Contents/Resources
[INFO]: Save path: /Users/dedmoroz/Library/Application Support/colobot/
[ERROR]: Error on parsing config file: failed to open file
[WARN]: Config not found. Default values will be used!
[WARN]: Failed to update locale, possibly incorect system configuration. Will fallback to classic locale.
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: No joysticks detected
[INFO]: Creating CDevice - OpenGL 1.4
**[ERROR]: GLEW initialization failed
ERROR: Error in CDevice::Create()**

---

I tried already to add this  glewExperimental=GL_TRUE;  befor first glewInit() but it is already there.
No Idea at the moment :)

**Comment by ptiza-v-nebe** [comment]
**Something changed in the repository.**
I compiled the code again with this dependencies:
cmake sdl sdl2 sdl2_image sdl2_ttf boost glew physfs flac libsndfile libvorbis vorbis-tools gettext libicns librsvg wget

**On:**

Mac OS X Yosemite 10.10 14A389
OpenGL 4.1 APPLE-11.0.7
OpenCL 1.2 (Sep 20 2014 22:01:02)(FULL_PROFILE)
Macbook Pro Early 2011

**Now got this error:**
[ERROR]: SDL error while setting video mode:
Failed creating OpenGL pixel formatERROR: SDL error while setting video mode:
Failed creating OpenGL pixel format
Press ENTER to continue
[INFO]: Didn't run main loop. Exiting with code 4
[INFO]: Unloading files and closing device...


What is the configuration of someone of you who develop colobot and compiled it on Mac OS X?

**Comment by Schocker** [comment]
Hi there! I've successfully managed to compile Colobot under both Yosemite and El Capitan. I'll try to compile from the newest commits and will get back to you later.

**Comment by ptiza-v-nebe** [comment]
Maybe you can tell me configuration of system you have compiled on? Just fresh system with all Instructions in INSTALL-MacOSX.md? Or added something?

I can compile to, without errors, but if I start colobot I get the above error message: "Failed creating OpenGL pixel format"

**Comment by Schocker** [comment]
@ptiza-v-nebe: I've just tested with the master branch and everything went perfectly fine. The game compiled and started up without any issues. 
Here's the `brew list` output: 
```
    MacBook-Air-Adrian:build Schocker$ brew list
    boost			intltool		makedepend
    cairo			jasper			openssl
    cmake			jpeg			pango
    flac			libao			physfs
    fontconfig		libcroco		pixman
    freetype		libffi			pkg-config
    gdk-pixbuf		libicns			sdl
    gettext			libogg			sdl_image
    glew			libpng			sdl_ttf
    glib			librsvg			vorbis-tools
    gobject-introspection	libsndfile		webp
    harfbuzz		libtiff			wget
    icu4c			libvorbis		xz 

What version of OS X are you running right now? Are all updates installed?

**Comment by vieux** [comment]
Same here I can compile fine the dev branch on Yosemite.

```
$ brew list
ack			cairo			freetype		glew			icu4c			libcroco		libogg			libtiff			openssl			pkg-config		sdl2_image		unbound			xz
autoconf		cmake			gdb			glib			jasper			libevent		libpng			libvorbis		pango			readline		sdl2_ttf		vorbis-tools
awscli			flac			gdk-pixbuf		gobject-introspection	jpeg			libffi			librsvg			makeicns		physfs			sdl			sdl_image		webp
boost			fontconfig		gettext			harfbuzz		libao			libicns			libsndfile		node			pixman			sdl2			sdl_ttf			wget
```

**Comment by ptiza-v-nebe** [comment]
It works! I tryed to compile and run colobot on a parallels virtual machine. Now I installed yosemite on my host pc and downloaded fresh copy of Homebrew. Now the dev branch compile and runs fluently.

But anyway! Thank you for your help!
