### ISSUE TITLE
Text input is broken

### ISSUE THREAD

**Issue by Nohus** [colobot/colobot#667]
Text fields don't accept text (player name, program editor, cheat console, etc.) on Linux (Debian). I have tracked this down to e965414d34b7c51196bafbe5f45983d6c3a8ffc8, text input works before this commit and does not after it.

You can still paste text, remove existing text with backspace and write tabs and newlines (enter), this only affects character input.

**Comment by krzys-h** [comment]
Could you run the game with parameters -debug sys_events -loglevel trace, try typing a few characters into any text fields and post the logs here?
Also, what are your system keyboard layout settings?

**Comment by Nohus** [comment]
Ah, I tried "-loglevel trace" before but it didn't print anything interesting, glad to know about the "-debug" option.

Here are the logs: http://pastebin.com/1aTbEfMN

Polish keyboard.

**Comment by krzys-h** [comment]
Looks like we are getting text input events from SDL2 properly so it's probably something on our end. I'll take a look at that.

**Comment by Nohus** [comment]
I confirm that 1b855f5dc342f3b38e6ee8f7afd4db12bca61886 fixes this.
