### ISSUE TITLE
Keyword 'this' sometimes points to the wrong bot

### ISSUE THREAD

**Issue by melex750** [colobot/colobot#672]
~~I don't think this is a bug but 
it is not documented in the game.~~
Public functions must be defined preceding a function that is passed
to a bot with `object.factory()`...
please review the following:

``` c++
public void object::ThisIsBetter() {} // <---probably the best place for a public function.

extern void object::Bot#1Main() //-----------------------Bot #1 Main------
{
    if (this.category == WheeledGrabber)
        botfactory.factory(WingedShooter, "Bot#2Main");
}

public void object::ThisWorks()
{
    message( "" + this.category );//      this. refernces Bot #2 when called by #2  
}

public void object::Bot#2Main() //-------------------------Bot #2 Main------
{
    ThisWorks();     //------Output is WingedShooter

    ThisIsBad();     //------Output is WheeledGrabber
}

public void object::ThisIsBad()
{
    message( "" + this.category ); //    this. refernces Bot #1 when called by #2
}
```

**Comment by krzys-h** [comment]
I've noticed that already at some point and forgot to investigate futher. I think this may be a bug, but I'm not sure.

**Comment by melex750** [comment]
These may be the same bug.

Recently I had to move a class definition to above
the function that called it,  to fix the error: 
"this is not a member of this class".

I have a proposal for a fix I would like to post in a new issue.

p.s.

I'm finding these issues,  with a 20kb Code Battle program.

and keeping it small with `object.factory(WingedShooter, "//program//Shooter.txt");`

It took a while to figure out `"//folder//file.txt"`.

**Comment by melex750** [comment]
A workaround is to pass 'this' as an argument.

I found the fix for this very annoying bug.
```diff
--- a/src/CBot/CBotInstr/CBotFunction.cpp
+++ b/src/CBot/CBotInstr/CBotFunction.cpp
@@ -695,7 +695,7 @@ int CBotFunction::DoCall(CBotProgram* program, const std::list<CBotFunction*>& l
 
             if (pStk3b->GetState() == 0 && !pt->m_MasterClass.empty())
             {
-                CBotVar* pInstance = program->m_thisVar;
+                CBotVar* pInstance = pStack->GetProgram(true)->m_thisVar;
                 // make "this" known
                 CBotVar* pThis ;
                 if ( pInstance == nullptr )
```
