### ISSUE TITLE
[ERROR]: Framebuffer incomplete: 36054

### ISSUE THREAD

**Issue by GrimAnEye** [colobot/colobot#675]
I have a problem when you start colobot gold edition 0.1.6(copied from "stderr.txt"):

[INFO]: Colobot: Gold Edition 0.1.6-alpha starting
[INFO]: Creating CApplication
[INFO]: Data path: ./data
[INFO]: Save path: C:\Users\Администратор\colobot
[INFO]: Error on parsing config file: No such node (Language.Lang)
[WARN]: Failed to update locale, possibly incorect system configuration. Will fallback to classic locale.
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: No joysticks detected
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 1.4
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 4
[INFO]: Multisampling not supported
[INFO]: Auto-detecting VBO support
[INFO]: ARB VBO supported
[INFO]: Maximum texture units: 8
[INFO]: CDevice created successfully
[INFO]: Closing joystick
[ERROR]: Framebuffer incomplete: 36054
Assertion failed!

Program: D:\Program Files\Colobot Gold Edition\colobot.exe
File: C:/Users/krzys_h/Desktop/colobot-0.1.6-release/src/graphics/opengl/glframebuffer.cpp, Line 381

Expression: false

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Unhandled exception occured!
==============================
SIGABRT, abort
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version 0.1.6-alpha, but please verify that.

The game was in phase PHASE_WELCOME1 (ID=0)
Last started level was: category=exercises chap=0 rank=0
==============================

Sorry for inconvenience!

**Comment by tomaszkax86** [comment]
This should be fixed since 78e877d9a88f5053d4b9b5ad34fbebbdeda16a72. Instead of crashing, game will simply disable the feature that cannot be used for some reason.

**Comment by tomangelo2** [comment]
In this case it may be closed I think.
