### ISSUE TITLE
Provide source tarballs

### ISSUE THREAD

**Issue by bentley** [colobot/colobot#677]
#362 resulted in the colobot-music repository being deprecated and the build scripts modified to download music during build. Unfortunately, this is inadequate for some situations—for example, on the OpenBSD project’s package build machines, build scripts are run by a separate user with no network access for security reasons.

Luckily, colobot provides versioned music tarballs at http://colobot.info/files/music/. That’s great, but it means some minor hassle for packagers since the directory structure and download mirror are different from the Github autogenerated tarballs.

The following would be really convenient: a versioned static tarball for data, a versioned static tarball for ogg, and a versioned static tarball for flac, all with the same directory structure and downloadable from the same mirror (either colobot.info or as files attached to a Github release, it doesn’t really matter), such that if you do “tar xzf colobot-data-0.1.7.tar.gz && tar xzf colobot-music-whatever-0.1.7.tar.gz” everything gets extracted to the right places and CMake does the right thing.

**Comment by krzys-h** [comment]
I'd really want to use git-lfs for music files, but the free plan of 1GB/month is probably not enough for our needs..We should soon discuss it with all the admins and decide what we're going to do.
GitHub automatically generates source tarballs for releases, but unfortunately you do need to know where in the directory structure should they be unpacked.

**Comment by krzys-h** [comment]
Will be done on next release
