### ISSUE TITLE
Bitwise NOT requires a space or parentheses

### ISSUE THREAD

**Issue by melex750** [colobot/colobot#681]
```c++
     ~ 10;  //  -11
    ~(-25); //   24
```
It works only with integers.

**Comment by tomaszkax86** [comment]
So bitwise NOT actually works when written in specific way. I think it worked properly in the past. The problem might have something to do with what we did to parsing tokens for destructors in 4d7de592b4a21c563df302ad77c199133cf6c279. This needs to be fixed.

**Comment by krzys-h** [comment]
That was fixed in c9e0249008bed8c76a43cc616c39e7a8f7ae46b5
