### ISSUE TITLE
Polymorphism works in CBOT

### ISSUE THREAD

**Issue by melex750** [colobot/colobot#683]
It was already implemented, but broken, like inheritance.
SOURCE_CODE - (2 TYPOs) + 1 IF + 1 ELSE = polymorphism ?

This compiles and runs. (when it's not abbreviated)
is this considered polymorphism ??
```java
public class Shape
{
    string color;
}

public class Rectangle extends Shape { }
public class Triangle extends Shape { }
public class Circle extends Shape { }

extern void object::Poly_What??!!!( )
{
    Shape[] shapes;

    shapes[0] = new Rectangle("red", 4, 5);
    shapes[1] = new Triangle("green", 3, 4);
    shapes[2] = new Circle("blue", 2);

    Shape a_shape = new Triangle("yellow", 1, 2); // <--methods, vars. just works. fixed

    shapes[3] = a_shape;

    a_shape.What_Am_I() ; // Pointer To Triangle(....color="yellow"....

    message(""+shapes[2]); // Pointer To Circle(radius=2 ) extends Shape (color=blue )

    radar(); will not output to subclass of object anymore:  fixed.

    // none of these should compile/run, and they don't.
    Triangle t ;// = new Shape(...); //compile error "wrong type..." compiled before: fixed
 
    // t = new Shape(...); // <----------runtime error "wrong type..."  :)

    // t = new Circle(...); // <--- no compile, never did   
  
    //Rectangle r = new Triangle(...);//  ^^ same ^^

}
```
I have a mostly complete fix for this. I'll check back later.

**Comment by Otaka** [comment]
Can you make a build with all these changes, I want to test it

**Comment by melex750** [comment]
There are still problems with this issue. I will post what i have found soon.
I have no idea how to make a build, sorry. I compile the game myself on linux.

For the record: (and for anyone who reads this.)
I am only attempting to research these issues, and
my contributions should not be considered actual fixes.

**Comment by krzys-h** [comment]
> I am only attempting to research these issues, and
> my contributions should not be considered actual fixes.

But still, they may help to find an actual fix, so it would be nice if you published them.

**Comment by melex750** [comment]
I have already tested what I have with the latest pull request.
I would be glad to wait and refer to those files.

**Comment by melex750** [comment]
While it is possible to compile examples of polymorphism in CBOT
its functionality has not been fully implemented. But it could be done.

Relevant info about source code related to this issue:
https://www.dropbox.com/s/nwqtdnitvpe4phf/PolyNotes.cpp?dl=1

**Comment by CyborgMaster** [comment]
Another example of how it "almost works"

``` c++
public class Base {
	public void greet(string name) {
		message("Hi " + name);
	}
};

public class Child extends Base {
	public void greet(string name) {
		super.greet("AWESOME " + name);
	}
};

extern void test() {
	Base c;
	c = new Child();
	c.greet("jeremy");
}
```

Compiles and runs just fine, but prints out "Hi jeremy", instead of "Hi AWESOME jeremy".   So it looks like the only thing we are missing is dynamic dispatch (virtual functions in C++).  It is calling the function based on the declared variable type, instead of the type of the object.
