### ISSUE TITLE
Double click on word in editor not select this word

### ISSUE THREAD

**Issue by Olamagato** [colobot/colobot#688]
In original Colobot double click on word in editor simple select word.
In Gold Edition I can do it sometimes. 6 or 8 cliks select one word.
Regres.
Colobot GE 0.1.6 alpha

**Comment by melex750** [comment]
When I set [DELAY_DBCLICK](https://github.com/colobot/colobot/blob/dev/src/ui/controls/edit.cpp#L56) to 0.75f in source, it works perfectly.

Also, [data->y * 4](https://github.com/colobot/colobot/blob/dev/src/ui/controls/edit.cpp#L257), gives SatCom and the editor a nice boost while scrolling.
