### ISSUE TITLE
Program editor window doesn't stay maximized after closing and reopening it

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#691]

**Comment by krzys-h** [comment]
It turns out I was wrong and the window didn't stay maximized originally - should we change that or not?

**Comment by RaptorParkowsky** [comment]
I think we should change that. Window coordinators are already saving, so additional parameter that defines maximized window wouldn't be a problem.

BTW I would rather propose saving position of the main game window too (if windowed mode on). It would be much helpful while debugging the game builds (personally I hate moving game window again around the desktop into right place after each crash :) ).

**Comment by krzys-h** [comment]
> BTW I would rather propose saving position of the main game window too (if windowed mode on). It would be much helpful while debugging the game builds (personally I hate moving game window again around the desktop into right place after each crash :) ).

It's not the application that should implement such functionality.
If it doesn't work then it's either Windows' fault or SDL's fault.
