### ISSUE TITLE
Windows 10 + generic drivers = :(

### ISSUE THREAD

**Issue by baqsio** [colobot/colobot#693]
When i try to turn on the game, it show me this messagebox:
![przechwytywanie](https://cloud.githubusercontent.com/assets/16350659/11897170/9346e2ce-a58d-11e5-8c05-ffe9beaefff6.PNG)

**Comment by krzys-h** [comment]
I think this is the same one we've seen recently. Could you please attach the stderr.txt file located in the game installation directory? (you may have to run the game as admin for this file to be created)

**Comment by baqsio** [comment]
Plik w załączniku

2015-12-18 15:22 GMT+01:00 krzys_h <notifications@github.com>:

> I think this is the same one we've seen recently. Could you please attach
> the stderr.txt file located in the game installation directory? (you may
> have to run the game as admin for this file to be created)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/colobot/colobot/issues/693#issuecomment-165788883>.
>

[INFO]: Colobot: Gold Edition 0.1.6-alpha starting
[INFO]: Creating CApplication
[INFO]: Data path: ./data
[INFO]: Save path: C:\Users\Daria\colobot
[ERROR]: Error on parsing config file: failed to open file
[WARN]: Config not found. Default values will be used!
[WARN]: Failed to update locale, possibly incorect system configuration. Will fallback to classic locale.
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: No joysticks detected
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 1.1
[WARN]: GLEW reports multitexturing not supported - graphics quality will be degraded!
[INFO]: Shadow mapping not available
[INFO]: Anisotropic filtering not available
[INFO]: Multisampling not supported
[INFO]: Auto-detecting VBO support
[INFO]: VBO not supported
[INFO]: Maximum texture units: 0
[INFO]: CDevice created successfully

Unhandled exception occured!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version 0.1.6-alpha, but please verify that.

CRobotMain instance does not seem to exist
==============================

Sorry for inconvenience!
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by krzys-h** [comment]
```
[WARN]: GLEW reports multitexturing not supported - graphics quality will be degraded!
[INFO]: Shadow mapping not available
[INFO]: Anisotropic filtering not available
[INFO]: Multisampling not supported
[INFO]: Auto-detecting VBO support
[INFO]: VBO not supported
[INFO]: Maximum texture units: 0
```
@tomaszkax86 Any ideas what could be causing that?
Looks to me like a graphics drivers issue

**Comment by krzys-h** [comment]
```
[INFO]: OpenGL 1.1
```
This is a problem too - Colobot requires at least OpenGL 1.4 if I remember correctly. We should add at least a proper error message instead of crashing.

**Comment by kurg** [comment]
That is interesting. I also received the same error but only when trying to play custom TrueLevels Missions by "TrueDestroyer". I think it was because that game only runs on an old 0.1.4 dev version.
All the Missions seem to work fine on my computer.
![trueerror](https://cloud.githubusercontent.com/assets/7715144/11978118/daf4ae7a-a967-11e5-8dc6-37f40c7d07d7.png)

**Comment by tomangelo2** [comment]
TrueLevels are designed for current dev branch (it will be 0.1.7).

**Comment by kurg** [comment]
Ok, well I have made the following changes and then all missions worked fine on my Windows 10 PC Colobot version 0.1.6:  I have only done Amber missions 1,2, and 3 so far but I will finish the rest today or tomorrow.

True Levels: Amber
In Amber levels 1, 2 and 3. (So Far)
Changed all .jpg and .bmp files to .png with "Microsoft Paint"
In the line - TerrainWater image="%lvl%/oil.jpg" level=33.7 moveX=0.05 moveY=0.1 air=TO water=TO color=20;20;20;0 brightness=0.1
Removed (air=TO water=TO)

Have a wonderful day and I am looking forward to version 0.1.7!!

**Comment by kurg** [comment]
Oh, I forgot to say I replaced all .jpg and .bmp with .png in the "scene.txt" files.

**Comment by krzys-h** [comment]
We added a proper error message - the issue itself is with the drivers, not with the game. Closing.
