### ISSUE TITLE
Save log to a file

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#696]
Currently we are depending on SDL to redirect stderr to file automatically on Windows and users to do it manually when needed on other platforms. We should save the log to a file ourselves, and then put the path to that file on crash error screen.

**Comment by tomaszkax86** [comment]
We could implement something similar to what Java Logging API has. Logger can have many handlers and each handler can have its own level. This way we could set different logging level for outputting to a file or even disable it, while logging to console can stay at different level. Command line switch can be adapted to separate handlers. By default logging to a file should be disabled in release builds. On debug builds it could be "debug" level.

**Comment by krzys-h** [comment]
> By default logging to a file should be disabled in release builds

I don't agree. The main reason I want this is to get more useful crash reports than a screenshot of the crash window that usually doesn't really say anything useful (unless it's caused by an uncaught exception)

**Comment by tomaszkax86** [comment]
I meant that in release build you'd have to enable writing to log file using a switch. Release build should be generally regarded as standard release and by default shouldn't generate unnecessary files. But if it's really necessary, it can write "info" or "debug" logs by default. I just hope it doesn't slow down the game.

**Comment by krzys-h** [comment]
It does currently write to stderr (SDL on Windows auto-redirects that) and I don't see any slow down
