### ISSUE TITLE
Array initialization syntax

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#698]
Just found another hidden syntax in CBot ;)

```C++
extern void object::Nowy()
{
    int a[] = (1, 3, 3, 7);
    for(int i = 0; i < sizeof(a); i++) message(i+": "+a[i]);
}
```

I recommend changing those to { ... } like in C++.

And of course this needs documenting in SatCom

**Comment by krzys-h** [comment]
Works for multidimensional arrays too:
```C++
extern void object::Nowy()
{
    int a[][] = ((1, 2, 3), (4, 5, 6));
    for(int i = 0; i < 2; i++) {
        for(int j = 0; j < 3; j++) {
            message("a["+i+"]["+j+"] = "+a[i][j]);
        }
    }
}
```

**Comment by tomaszkax86** [comment]
Since this wasn't documented in SatCom and it might be preferable to use ```{ }```, I suggest we change it to ```{ }``` and document it as such.

**Comment by tomangelo2** [comment]
Anybody against?

**Comment by melex750** [comment]
It works like this too:
```java
public class AClass
{
    void AClass(int a)
    {
        message("AClass " + a);
    }
}

extern void object::New()
{

    AClass aClass[] = ( new AClass(1), new AClass(2) );

}
```

**Comment by krzys-h** [comment]
A little problem with {} is that the editor automatically starts an indentation block. That is sometimes useful (when you have something long like category names or class constructors) but sometimes you'll remove them manually (like in the 3 integers example)

**Comment by tomaszkax86** [comment]
Editor could be "smarter", that is it should only start indented block if ```{``` was input on a line with white space characters only. In other cases it would simply open ```{``` and do nothing else.

**Comment by krzys-h** [comment]
You cannot make it on line with whitespace only. What about this then:
```C++
if(something) {
```

**Comment by tomaszkax86** [comment]
I'm not going to argue about this kind of syntax. But you can't detect this kind of situations without real-time syntax analysis.

**Comment by tomangelo2** [comment]
In this case it could wait if user is typing in same line, or in new line. In first case, it wouldn't do anything else, but after pressing enter it could automatically make indented block.

**Comment by krzys-h** [comment]
@tomangelo :+1:
It could put both { and } and position your cursor between them - if you press enter, that makes the new block

**Comment by tomaszkax86** [comment]
Sounds reasonable. Now, can someone do it?

**Comment by krzys-h** [comment]
Done, now we only need documentation in SatCom

**Comment by DrizztDoUrden** [comment]
Maybe you should also add something like C# sugar for collections initializing? Like this:
```
int[] a = {
    [1] = 10,
    [5] = 20,
}
```
I suppose it's quite obvious what it does.

**Comment by krzys-h** [comment]
@DrizztDoUrden maybe after CBot refactoring - please create a separate issue for that

**Comment by MrSimbax** [comment]
The following code crashes the game:

    int array[2] = {1,2,3};

It should give a compilation error.

**Comment by MrSimbax** [comment]
Documentation done. https://github.com/colobot/colobot-data/commit/a793c0ba8384204b83437ee5d6a7f2547086e7a2
