### ISSUE TITLE
In code battle mode, tower does not attack enemy. 

### ISSUE THREAD

**Issue by zzx999** [colobot/colobot#700]
%subj%;
also 
in code battle mode , shielder does always errors out. Even if it's given simple task just move out of the factory and turn on shield.

**Comment by krzys-h** [comment]
I was considering making DefenseTowers attack the enemy team but that's not implemented yet.
I'm interested in what others think of this idea.

**Comment by zzx999** [comment]
what about shielder? 
maybe noob question, but how to see what errors it thwrows out? It's errors out the same on stable or dev version.

**Comment by tomangelo2** [comment]
DefenseTowers should shoot at enemies, but maybe with some delay (like charging, or something else), to make them not so OP, then enemy team could avoid being hit (to encourage to more complex programs, simple goto() will be not enough to outsmart DefenseTowers).
