### ISSUE TITLE
There would be perfect to have FastForward button in codebattles.

### ISSUE THREAD

**Issue by zzx999** [colobot/colobot#701]
Like 2x 4x 8x 16x.... Sometimes it's boring to wait for result.

**Comment by melex750** [comment]
It is already possible to change game speed with function keys F3 ... F9.
Changing game speed sometimes causes errors.
I have seen the fewest errors at speed 2x and lower.
F6 = speed 2x.

**Comment by krzys-h** [comment]
Exactly like @melex750 said, this is already available, under F3-F9 keys. Be careful with higher speeds as they may destabilize the simulation. This will probably be improved in a future, but likely not too soon.

If those options are not enough, you can open the cheat console with ~ key and type ```speed <number>``` to set speed multiplier to any value.
