### ISSUE TITLE
Defining two classes with the same name, crashes the game.

### ISSUE THREAD

**Issue by melex750** [colobot/colobot#703]
Should be a compile error, but it compiles once, and crashes the next time you click compile/OK.

Changing `false` to `true` on [line 497 CBotClass.cpp](https://github.com/colobot/colobot/blob/dev/src/CBot/CBotClass.cpp#L497)  fixes this issue.

The only place this value is tested, is just above that on [line 474](https://github.com/colobot/colobot/blob/dev/src/CBot/CBotClass.cpp#L474).

**Comment by krzys-h** [comment]
I noticed this already while writing unit tests for CBot, jusr never made an issue for it. I'll test your fix later.

**Comment by melex750** [comment]
After further testing, I found the value should be true ***only if*** there are no errors
before returning from Compile1(), moving line 479 to [line 510](https://github.com/colobot/colobot/blob/dev/src/CBot/CBotClass.cpp#L510) seems to work.
```c++
        if (pStack->IsOk())
        {
            classe->m_IsDef = true;
            return classe;
        }
```
```classe->Purge();```on line 496 leaves it false in any other case.
