### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by IlyaER** [colobot/colobot#707]
Just downloaded from here and started:
http://colobot.info/files/releases/0.1.6-alpha/colobot-gold-alpha-0.1.6-win32-portable.zip

[stderr.txt](https://github.com/colobot/colobot/files/108689/stderr.txt)

**Comment by krzys-h** [comment]
Appears to be a duplicate of #675
@tomaszkax86 please help, I know nothing about how graphics engine works and it's probably your fault ;)

Possible workaround:
Find the colobot.ini file in C:\Users\<your username>\colobot\colobot.ini and under [Setup] change MSAA, ShadowMapping and ShadowMappingQuality to 0. Those are all settings that could possibly be using the framebuffer.

**Comment by IlyaER** [comment]
Thanks! That helped.

**Comment by krzys-h** [comment]
@IlyaER If you want to help us a bit more, change ShadowMapping and ShadowMappingQuality back to 1 and let us know if it still works (leave MSAA=0)

**Comment by IlyaER** [comment]
Setting MSAA = 0, ShadowMapping = 1, ShadowMappingQuality = 1 - crashes.
Using 1, 0, 0 is ok.

**Comment by krzys-h** [comment]
@tomaszkax86 So apparently the problem is with shadows and not MSAA
