### ISSUE TITLE
Exercises: 7 Classes: 2 Remote control # 4 - Bug at "Slave4" CBOT program example

### ISSUE THREAD

**Issue by ivanovmv** [colobot/colobot#710]
"Function already exists" at Slave4 line 32.

> // Delete an order.
> synchronized void delete()
> {
>     m_order.m_type = nan;
> }

**Comment by krzys-h** [comment]
This is because hidden function delete() has been added to CBot as a cheaty way to destroy any object. Thanks for reporting this!
