### ISSUE TITLE
GOLD running with OpenGL 2.1 is really black

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#716]
That's how shorten logs look like:

```
[INFO]: Colobot: Gold Edition 0.1.6+alpha-git-HEAD~r32b480b starting
[*****] Log level changed to trace
[INFO]: Active debug modes: all
[INFO]: Creating CApplication
[INFO]: Data path: ./data
[INFO]: Save path: ./saves
[ERROR]: Error on parsing config file: failed to open file
[WARN]: Config could not be loaded. Default values will be used!
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[TRACE]: Error on parsing config file: No such node (Setup.Resolution)
[TRACE]: Error on parsing config file: No such node (Setup.Fullscreen)
[INFO]: No joysticks detected
[INFO]: Creating CDevice - OpenGL 2.1
[INFO]: OpenGL 2.1
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 8
[INFO]: Multisampling supported, max samples: 8
[INFO]: Maximum texture image units: 16
[TRACE]: Error on parsing config file: No such node (Setup.PerPixelLighting)
[INFO]: Using per-vertex lighting
[ERROR]: Shader program linking error occured!
Fragment info
-------------
(58) : error C5108: unknown semantics "FACE" specified for "gl_FrontFacing"

[INFO]: Didn't run main loop. Exiting with code 5
[INFO]: Unloading files and closing device...
```

Game closes with that window:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/12974564/2891d9ea-d0b5-11e5-924e-7c4222217ba8.png)

**Comment by tomaszkax86** [comment]
Could you tell me what is your graphics card? It seems some older NVidia cards don't support ```gl_FrontFacing``` despite the fact that it has to be supported by conforming hardware. This is therefore fault of the graphics card. I can try to write a workaround to this but right now I can't guarantee anything. You can temporarily solve the problem by commenting out few lines from the fragment shader code, like this:

```
// if (gl_FrontFacing)
    color.rgb *= mix(uni_ShadowColor, 1.0f, shadow2D(uni_ShadowTexture, gl_TexCoord[2].xyz).x);
// else
//     color.rgb *= uni_ShadowColor;
```

**Comment by RaptorParkowsky** [comment]
Well, that's right, I have Nvidia GeForce FX5200.

**Comment by RaptorParkowsky** [comment]
With recent changes it's booting normally, but it's even about 50% slower than before latest optimizations. Menu's working about ~4 fps, in the game ~2 fps. And that's how it look:

![schowek01](https://cloud.githubusercontent.com/assets/4019345/13020444/af61f40c-d1d5-11e5-9341-1c79039f539e.png)

(And that's not depending on shadow mapping enabled)

**Comment by krzys-h** [comment]
Menu running faster than the game is actually quite suprising, it's exactly the opposite on both 2.1 and (especially) 3.3 engines for me :D
What FPS does it run at normally? For me the drop is not really that big, but definitely noticeable (from ~55 FPS on GL 1.x to ~45 FPS on GL 2.2)

**Comment by RaptorParkowsky** [comment]
I checked again 0.1.6 release on OpenGL 2.1 and menu runs ~13fps, game ~5fps - definitely slower than latest dev release. And obviously look better.

**Comment by RaptorParkowsky** [comment]
Well, in recent builds it doesn't really crash. It's slow as always but almost everything is rendered black, just like in my previous screenshot. I re-labeled and renamed issue and I think it's not so urgent to keep that for 0.1.7 milestone as we still use OpenGL 1.4 as default engine.

**Comment by hexagonrecursion** [comment]
The dev branch of the game no longer supports OpenGL 2.1. See ec21faf15c9d117cc8caf479d0f718f01481f3f8. Is this reproducible in OpenGL 3.3?
