### ISSUE TITLE
Appearance customization standard presets

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#724]
There's some things that I think needs to be changed in appearance menu for aesthetical purposes.

In head selection/customization:
- [x] Current second head (and of course it's button) should be in fact the fourth (just like the face## textures say).
- [x] Changing the face type should change it's hair color to it's normal/texture values. Currently it looks awful when you change the face but the hair color stay unchanged and doesn't really fit.

In suit customization:
- [ ] The standard suit color should stay of course white, but the strip color I think could be "rebranded" from standard Colobot's orange to our TerranovaTeam's brand color - green (R=0, G=255, B=0).

**Comment by krzys-h** [comment]
> The standard suit color should stay of course white, but the strip color I think could be "rebranded" from standard Colobot's orange to our TerranovaTeam's brand color - green (R=0, G=255, B=0).

I do not agree with this change.

1. TerranovaTeam brand color is actually #00E80A not #00FF00. This is a very slight difference, but it's actually noticeable if you compare the two.
2. The original astronaut with orange strips is the official one used on screenshots etc. Changing it feels a bit like changing a logo, and that (as you probably already know :stuck_out_tongue:) is not really good.
3. I tried changing it and it just feels wrong to me somehow. I know nothing about art, but white + green feels like too big of a contract. White + orange just matches a lot better.
4. It's also my avatar that I got really used to :stuck_out_tongue_closed_eyes:

**Comment by RaptorParkowsky** [comment]
You don't really like changes, don't you?

Ok, what about blue stripes then? 00c0ffff aka [R=0;G=192;B=255;A=255]

Almost all screenshots on colobot.info are from original Colobot. And orange was default for this version of the game. But now we have GOLD, which is still under early, almost like pre-develpoment. It's not the beta, where all such kind of changes aren't going to happen because already developed GDD. So there's still a lot changes to do and we shouldn't think about them like "they changes too much".

Especially in this situation where default appearance of the Astronaut isn't really connected to the game's plot or, well, the Polish National Football Team. The final decision about that depends on the player's mind anyway.

**Comment by krzys-h** [comment]
> You don't really like changes, don't you?

Well... you are right, I don't :stuck_out_tongue_closed_eyes:
But on the other hand, you really like unneeded changes that take time we could spend actually working on the game
