### ISSUE TITLE
All color changing buttons are white

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#726]
Well, that's I believe the only one thing that @tomaszkax86 broken by rewriting shadow mapping. :) 

![schowek01](https://cloud.githubusercontent.com/assets/4019345/13601169/4f81364e-e52e-11e5-852e-5309c99534c1.png)
![schowek02](https://cloud.githubusercontent.com/assets/4019345/13601172/5332eb7a-e52e-11e5-8a52-e013a2930c8f.png)
![schowek03](https://cloud.githubusercontent.com/assets/4019345/13601176/582b8fec-e52e-11e5-8e74-0dbaa8378478.png)

But finally I have a reason to enabling shadow mapping on my old Nvidia GeForce FX5200 with only 4 texture units on OpenGL 1.4! That's a thing! :D

**Comment by krzys-h** [comment]
I can confirm this is fixed :+1:
