### ISSUE TITLE
Comma operator in "for loop"

### ISSUE THREAD

**Issue by melex750** [colobot/colobot#727]
This works in-game:
```c++
extern void object::Comma()
{
	for(int a=0, b=0, c=a+b; a<4; a++, b++, c=a+b)
	{
		message("a: "+a+"    b: "+b+"    c:"+c);
	}
}
```

**Comment by krzys-h** [comment]
I see no reason why it wouldn't ;) I'm not sure it is documented anywhere though.

**Comment by MrSimbax** [comment]
Comma is not an operator in CBOT, it doesn't return anything.

**Comment by krzys-h** [comment]
I know it is not actually an "operator" like in C/C++ (that may change at some point) but you can use it to execute multiple instructions in a for loop.

**Comment by MrSimbax** [comment]
Yes, I noticed ;) I just wanted to point out the misconception in the title of this issue.
