### ISSUE TITLE
Mission 1-3 goto() bug

### ISSUE THREAD

**Issue by Smok94** [colobot/colobot#732]
Try code:
`object o = radar(BlackBox);
goto(o.position);`
Returns error: Location is occupied, so robot can't get to blackbox.

**Comment by tomangelo2** [comment]
Couldn't reproduce that, robot goes to Blackbox like it should.
Do you have dev or release build?

**Comment by krzys-h** [comment]
goto() is known to be sometimes unable to find a path even if it's clearly there. Moving the bot around usually helps. We don't know what causes that yet.

**Comment by Smok94** [comment]
Version master 0.1.6 (more stable). It happens even i paste this code to my Wheel Grabber right after mission start. It happens for Tracked Grabber to. goto() is very high level function in my opinion, but sometimes get stuck or choses path in the way we don't want. It would be nice to see this function lower level components as Cbot functions, so we would be able to easily customize "goto".

**Comment by tomangelo2** [comment]
goto() alghoritm will be rewritten in future.

**Comment by melex750** [comment]
I think goto() finds GoalArea object and thinks it's occupied by BlackBox.

similar to:
int types[] = {Converter, Titanium};
object[] obj = radarall(types); // will return the same object twice. (Two Titaniums)

**Comment by Smok94** [comment]
My research so far:
Tried too restart mission many times. I happens every time. Tried to download again and overwrite game files (thought maybe mission file is corrupted). Tried to download and run 32-bit portable version (currently using 64 portable). No effect. If i pick up and drop BlackBox i place before program starts everything works right. Tried to launch program standing in front of BlackBox (before was picked up) - still nothing. Tried to launch program when robot stands behind BlackBox (between box and transmitting station) and it worked(!).

**Comment by Smok94** [comment]
Trying to reach ExchangeStation and GoalArea with goto aslo makes problem. I think it's may be something about "z" position of objects.

**Comment by RaptorParkowsky** [comment]
I just tested this with our older master compilations and I think it's actually something wrong with our official compilation of that unfortunate 0.1.5 & 0.1.6 releases or maybe even with whole current master branch! Latest dev builds and, uh, the 0.1.4 works fine with goto() that was a little corrected by @krzys-h for 0.1.4 release back then as long as I remember, but somehow 0.1.5 & 0.1.6 is almost completely disaster. In the dev branch still it's buggy but not as much unplayable that couldn't find a Black Box in mission 1.3.

I think it's time to verify our final compiling methods or master branch, it's looking mysterious...

**Comment by RaptorParkowsky** [comment]
It's working in latest pre-0.1.7 dev builds so I think this issue can by related to this milestone and officially closed. I hope 0.1.7 master will not repeat the same mistakes again :) .

**Comment by tomangelo2** [comment]
To check that someone have to build that as a Release build, then test it. Release builds have -O3 flag, that might do some optimizations making goto() alghoritm less reliable.

**Comment by krzys-h** [comment]
I did test that some time ago, goto() is indeed a bit more reliable on release builds because it calculates faster so it sometimes manages to finish before the command times out

**Comment by RaptorParkowsky** [comment]
@krzys-h I don't get that. How goto() in release builds is more reliable when it refuses to goto'ing to position of the objects more often than in dev builds? I personally prefer to wait some more time for calculating precise way to objects than wait a second and often get ridiculus message that object is inaccessible from very beginning of the program. Stability > speed.

**Comment by krzys-h** [comment]
Stability SHOULDN'T differ between debug and release, the speed (and therefore allowed complexity of the path before it assumes there is no valid one) does, and the speed is BETTER in release builds. This is confirmed by testing I did some time ago.

**Comment by RaptorParkowsky** [comment]
Ok, so why it stops the program instead of trying it's best to find the way in such obvious cases like this? IMO it only makes it less reliable and you can't even use this for example in Diversity contests.

**Comment by krzys-h** [comment]
Like I said previously, I have no idea why it fails in such obvious cases. I only know why debug vs release build matters in more complex paths.

**Comment by krzys-h** [comment]
I did some testing yesterday and found a commit which caused this

# bad: [88c6818cfdd64cca6c2633942ba02a0c63907413] Fix code style issues
# good: [98124cd8f6d7fe200de8f4bcc34505a2f111dca6] Removed polish README
# good: [1be66b40c39b90b4cf71946089cd5ee1c6cf2b45] Update translation files
# good: [8922bb5e848be9dae6a272fa5a68057682c2661d] Renamed CGLDevice to CGL14Device
# good: [397e3124246a67ddb9b7f16b1fecdda6abd3f3cd] Fix RestoreState for subclass instance vars
# bad: [81aae35565b969a1c5ba5c50b4af99405fdbda5c] Updated translation files after 4a14a44f3f07ee103161fbec2bcaa4bf5e6e2a84
# good: [b9d4d57e335bee1f2eefde2ec53428948449d868] Syntax sugar: Accessing members of returned objects (#808)
# good: [e3b3d7c9aaa60535c63ac75ed0620793b69fd533] Enable debug info for MSVC
# bad: [84c98546dfef7ed6e48aa9dd7cd094a211657201] Merge pull request #819 from melex750/dev
# bad: [859cec774a85e45141be3d32fcf788709cd8d13d] Added comment explaining container choice
# bad: [88227a3647e88508d817af236b81aeb4d5e522d0] Allow multiple objects with exactly the same distance to be returned by `radarall`
# first bad commit: [88227a3647e88508d817af236b81aeb4d5e522d0] Allow multiple objects with exactly the same distance to be returned by `radarall`

**Comment by krzys-h** [comment]
No idea what actually caused it to fail after this commit, I'll look into that later

**Comment by krzys-h** [comment]
It seems to be related to CTaskGoto::SearchTarget. When using std::map, the function returns:
```ID=37 BlackBox```
but when using std::multimap, it returns:
```ID=35 GoalArea```

**Comment by immibis** [comment]
I always wondered how `goto` knew which object to line up with...
