### ISSUE TITLE
Program stops for no reason(?)

### ISSUE THREAD

**Issue by Smok94** [colobot/colobot#733]
Function for TrackedGrabber bot made by my custom IA made in mission 1-3. Robot have to bring black box into spaceship and "takeoff()" it. Program throws error after few seconds: Error in movement order. When program is restarted with PowerCell on works good.
````
void object::wyjedzZFabryki(){
//it seems like robot skips loop below after while, thats why crashes(?)
while(this.energyLevel==0){ //this loop is for waiting untill robot gets PowerCell
wait(0.1);
}
wait(1);
move(-5);
}

public void object::Tracker(){
wyjedzZFabryki();
object bb = radar(BlackBox);
errmode(0);
object statek = radar(SpaceShip);
point p1 = space(statek.position,1,5,0.5);
while(distance(this.position,bb.position) > 2){
float angle = direction(bb.position);
if(angle > 5){
motor(-1,1);
}
else if(angle < -5){
motor(1,-1);
}
else{
motor(1,1);
}
}
grab();
goto(p1);
drop();
while(statek.takeoff()!=0){
message("Aboard SpaceShip astronaut!",DisplayInfo);
wait(5);
}
}

//Why so overcomplicated? Check here: https://github.com/colobot/colobot/issues/732

**Comment by tomangelo2** [comment]
It's not game bug, it's this line
```
while(this.energyLevel==0){ //this loop is for waiting untill robot gets PowerCell
```
You need to replace it with
```
while(this.energyCell.energyLevel==0){ //this loop is for waiting untill robot gets PowerCell
```
because bots don't have energyLevel variable, it belong to energyCell.
Also, before that you must check if energyCell is mounted in robot.
So final version of this line is:
```
while(this.energyCell == null || this.energyCell.energyLevel==0){ //this loop is for waiting untill robot gets PowerCell
```

**Comment by krzys-h** [comment]
```C++
while(this.energyLevel==0)
```

This code is wrong. You are checking the energy level of the robot itself, but he doesn't actually store energy - you need to check the robot's battery instead.

The correct way to do what you want is:

```C++
while(this.energyCell != null) // checks if robot has a battery inserted
```

Or if you want to get the actual energy level of the battery:

```C++
if(this.energyCell != null) {
    message("My energy level is "+this.energyCell.energyLevel);
} else {
    message("I have no battery inserted");
}
```

**Comment by Smok94** [comment]
Replaced with:
`while(this.energyCell == null || this.energyCell.energyLevel==0){`
then
`while(this.energyCell == null){`
but nothing changed, sill have error.
(in my language version it seys "Błąd polecenia ruchu")

**Comment by krzys-h** [comment]
I have no idea what could be causing it then, it seems to work fine for me. Make sure you are not hitting the robot behind it and that this error doesn't come from any other piece of code.

**Comment by Smok94** [comment]
Found it!
This happens becouse function void object::wyjedzZFabryki() don't have public prefix.
