### ISSUE TITLE
Document Target2 category

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#734]

**Comment by MrSimbax** [comment]
![3807028-0520411863-da54c](https://cloud.githubusercontent.com/assets/2318282/13882621/887afb92-ed26-11e5-9787-c5b420076777.jpg)

**Comment by krzys-h** [comment]
Yeah, I know, sorry :stuck_out_tongue_winking_eye:

**Comment by tomangelo2** [comment]
I'm not sure if it's really necessary to do it in 0.1.7, it's not so critically important.

**Comment by krzys-h** [comment]
I'm not saying it's critically important, but documentation is something that can be done when the code for the release is already finished and being tested

**Comment by MrSimbax** [comment]
Hakuna matata! It's already done, I'm just fighting with some technical issues (argh!).

**Comment by MrSimbax** [comment]
Done https://github.com/colobot/colobot-data/commit/367a7f8bba0e43c301a36bcc03df776a5ed0d963

**Comment by RaptorParkowsky** [comment]
But you guys totally forgot about to mention Target1 object... D:

**Comment by MrSimbax** [comment]
Shhhhhh, god damn it Raptor, it was supposed to be a secret :/

**Comment by MrSimbax** [comment]
Can't close from submodule? Well, that's a shame... :C

**Comment by krzys-h** [comment]
It autocloses only when that commit gets merged to master
