### ISSUE TITLE
Astronaut's idle animation are not interpolated

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#742]
Animation of the Astroaut's arms and legs appear to be glitchy. They appear to move from keyframe to keyframe without smooth, interpolated transition like in original COLOBOT.

This is possibly the only one example of keyframed animation in this game. The rest of animations are just hardcoded procedures as far as I know. Probably that's why only this animation is looking glitchy.

**Comment by tomangelo2** [comment]
Well, if we want to change model format and move animations to model files, then is there any sense to dig with animation code, just to remove this code in next release? Especially if it's not critical issue, it doesn't cause crash, it doesn't make the game unplayable. It could be useful in previous releases, but right before 0.1.9?

**Comment by RaptorParkowsky** [comment]
I think this could be not exactly related to this particular animation code, but in the code of "playing" such animations in the implementation of OpenGL or something. As far as I understand, the hardcoded animation code consists only on keyframes with their timing and positions of all meshes of the model in this case.

But I'm not a programmer and this is only my theory about that. Well, probably easier would be completely remake all Astronaut's animations with new hi-poly model, but this will be probably after 0.3.# milestone or even in early Beta stage though.

**Comment by krzys-h** [comment]
There is no such thing as "animation playing code". The animations are just a bunch of SetPartPosition calls.
