### ISSUE TITLE
Bigbrother for AI programs execution

### ISSUE THREAD

**Issue by Smok94** [colobot/colobot#746]
My proposition is a place, that is not a robot, where we put and execute our managing base AI, in programming battles and missions, without risk of loss because main robot got destroyed. Could have a possibility to send programs to robots order their execution.

**Comment by krzys-h** [comment]
Something like this was already suggested, but we don't know what that place could be to fit nicely into Colobot theme

**Comment by krzys-h** [comment]
Duplicate of #478

**Comment by Smok94** [comment]
I think it can be the spaceship, as it can be like big antenna with supercomputer inside. For missions without spaceship it can be orbital command center (satelite).
