### ISSUE TITLE
CBot function for bots construction 

### ISSUE THREAD

**Issue by trapwalker** [colobot/colobot#75]
This feature makes possible significantly improve automation in Colobot world.

**Comment by RhFortuna** [comment]
> I've found interesting way to do this. Let's add this function as member of class object, like so:
> 
> ```
> object item = radar(BotFactory);
> item.factory(WingedShooter, "script.txt");
> 

It didn't work for me. What is the correct folder for script.txt?
Do I need to read each line of the file with readln?

**Comment by melex750** [comment]
The string accepts one of three types of data;
1. Name of public function: ```"FunctionName"```
2. CBOT code: ```"extern void object::TestProg() { message(\"hello world\"); }"```
3. A filename:
for files folder:
```"/files/script.txt"```
for 'public' program folder:
```"/program/script.txt"```
for 'private' program folder:
```"/savegame/<PLAYER_NAME>/program/script.txt"```

**Comment by RhFortuna** [comment]
Thank you, melex750, it works!

I was trying this
`item.factory(WingedGrabber, "script.txt");`
With a script.txt file in the /file/ folder. But WingedGrabber was being created with an empty file.

**Comment by cbot-coder** [comment]
I posted what I do for this on Reddit.

By the way, is there a place where people share their code and tips on automation?
