### ISSUE TITLE
Game crashes when loading user level gamesave.

### ISSUE THREAD

**Issue by Mrocza** [colobot/colobot#765]
![issue 1](https://cloud.githubusercontent.com/assets/1828157/14383858/fc188e58-fd97-11e5-9089-2d40e464da7e.png)

I was attempting to load a game on the following level downloaded from the forums:
https://colobot.info/forum/showthread.php?tid=700

**Comment by krzys-h** [comment]
Looks like issue #614, except I added an assert() for this since it was originally reported. Could you check if you can reproduce it on another level? You necessarily need to have a CBot program running on save.
I will try to reproduce it later, but it would be nice if you could upload your save file just in case.

**Comment by Mrocza** [comment]
Unfortunately, I cannot seem to get the same crash.

It does crash on this save:[gamesave.zip](https://github.com/colobot/colobot/files/210311/Gamesave.zip) (True Levels: On Amber - 1: Out there)

**Comment by melex750** [comment]
That save doesn't crash for me but I had a similar issue:

I got a segfault repeatedly, when starting a new game on Amber - 1(V1J),
**until** I moved all scripts from ```savegame/<playername>/``` like ```c0********.txt```.

These were left over from previous versions of that level pack and other userlevels.
I saved them so I can figure out which one(s) did it. (There are dozens of them.)

* I've had stuff like this happen with my own userlevel after making changes to it.

I also wouldn't expect saves from previous level versions to be compatible,
especially when the author said he updated the AI.

**Comment by melex750** [comment]
I finally reproduced with that saved game on a 32 bit machine.

It can also be reproduced at the start of Amber.1 level with this command:
```produce(position, orientation, AlienAnt, "%lvl%/ANT1.TXT");```
Then save and reload.

* The scene file "data.sav" in the above gamesave.zip was missing```script1="%lvl%/WASP1.TXT"```
and```script1="%lvl%/ANT1.TXT"```on some```CreateObject```lines after```run=1```.

Here's a new **[data.sav](https://www.dropbox.com/s/3gte6123mm3mqbq/data.sav?dl=1)** for that save.
The userlevel (**[True Levels 1j.zip](https://www.dropbox.com/s/ojiapq4nhpabttx/True%20Levels%201J.zip?dl=1)**)

This fixes the issue.
```diff
--- a/src/script/scriptfunc.cpp
+++ b/src/script/scriptfunc.cpp
@@ -1393,6 +1393,7 @@ bool CScriptFunctions::rProduce(CBotVar* var, CBotVar* result, int& exception, v
             CProgramStorageObject* programStorage = dynamic_cast<CProgramStorageObject*>(object);
             Program* program = programStorage->AddProgram();
             programStorage->ReadProgram(program, name2.c_str());
+            program->readOnly = true;
             program->filename = name;
             dynamic_cast<CProgrammableObject*>(object)->RunProgram(program);
         }
```

**Comment by krzys-h** [comment]
Thanks! I will check and commit this fix soon.

**Comment by krzys-h** [comment]
I can confirm both the reproduction steps and the supplied patch. Commiting this now, thanks again!
