### ISSUE TITLE
UI is "colored" while fogstart value is negative in scene file.

### ISSUE THREAD

**Issue by DavivaD** [colobot/colobot#766]
OpenGL 1.4 only!
![e2uwme0](https://cloud.githubusercontent.com/assets/15150065/14571812/97d10218-034b-11e6-85a4-a4ee84f6a6a1.png)

**Comment by tomangelo2** [comment]
Maybe I'm not so good at math, but 0.9 doesn't look for me like negative value.
It looks a bit different (mainly buttons), but not as much in my case.
![minus](https://cloud.githubusercontent.com/assets/4140449/14574054/74ce6fd6-0359-11e6-8ebf-ed0ea2b6d9a5.png)
![plus](https://cloud.githubusercontent.com/assets/4140449/14574055/74d24962-0359-11e6-90f8-b69a8ec2feb9.png)

**Comment by CHmSID** [comment]
I can confirm on the latest dev build:
![screenshot from 2016-04-15 23 04 50](https://cloud.githubusercontent.com/assets/6818394/14576136/94f23176-035e-11e6-9333-278df95dd95b.png)

It appears that negative values make the fog also affect the GUI. Both air= and water=.
The smaller the number the more fog there is between the interface and the player.

I think clamping the value to 0 upon level loading will solve the issue?
