### ISSUE TITLE
Radar returns objects of the incorrect type

### ISSUE THREAD

**Issue by IanSimcock** [colobot/colobot#767]
I was working on "Code battles - vs computer" code and found that it was working fine up to the point that radar(EnergyCell) started returning the BotFactory I'd just built.

It was doing this in version 1.6 and is still doing it in 1.7 as well.

As a test I tried Free Game, On Sarri, where I built a BotFactory, built a robor (WingedGrabber) and added some code that was just -
extern void object::New()
{
	object x = radar(EnergyCell);
	message("Category Found: "+ x.category);
}
This code finds the BotFactory as well, despite the row of EnergyCells behind it.

Oh, and while I'm here, I have say that I'm so glad you guys are working re-releasing and this game. I bought a copy back in the day and have enjoyed playing it again.

**Comment by melex750** [comment]
```EnergyCell```is a constant for```grab();```and```drop();```commands, to change the bots own battery.

```PowerCell``` is used with ```radar()```.

```EnergyCell```has the same numerical value as```BotFactory```.

**Comment by krzys-h** [comment]
Like, @melex750 said, EnergyCell is not a valid object category. You want to use PowerCell instead.

**Comment by RaptorParkowsky** [comment]
In the past I also often was confused about what's the difference between EnergyCell and PowerCell. I know this would break completely the backward compatibility, but wouldn't it be better if you change EnergyCell name into something less confusing, like EnergySlot or something?

**Comment by MrSimbax** [comment]
We could add another constant equal to EnergyCell but with less confusing name and change its mentions everywhere in the help files (at least documentation), but of course write about the old (deprecated then) EnergyCell somewhere in the docs. This way we wouldn't break backward compatibility.

**Comment by krzys-h** [comment]
But then we also don't fix the problem of confusing them.

**Comment by MrSimbax** [comment]
It partially does. However, I won't be discussing if it's an idea worth implementing.

**Comment by tomaszkax86** [comment]
It would be a lot easier if we had strongly typed enums instead of int constants. Something to discuss during CBot refactoring.
