### ISSUE TITLE
Mouse wheel shouldn't zoom in/out selected object, while scrolling programs list or minimap

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#769]

**Comment by RaptorParkowsky** [comment]
I would accept that proposal.

**Comment by krzys-h** [comment]
Honestly, this is more like a bug than a proposal :P

**Comment by RaptorParkowsky** [comment]
Oh yes? I totally forgot that this feature was working in original Colobot.

**Comment by krzys-h** [comment]
Bug != difference from original Colobot...
