### ISSUE TITLE
It is possible to set anti-aliasing to x32

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#774]
Recently I found this issue on wykop.pl:
![zrzut ekranu3](https://cloud.githubusercontent.com/assets/4019345/14941573/9ddcf6ce-0fa0-11e6-97e5-8215e1de2577.png)

And even in the recent Linux build:
![zrzut ekranu1](https://cloud.githubusercontent.com/assets/4019345/14941560/2d7a47c4-0fa0-11e6-838d-d5be9e3edac7.png)

My GPU: GeForce GTX 750 Ti & Nvidia driver version: 352.63

**Comment by RaptorParkowsky** [comment]
It also saves such value to colobot.ini.

**Comment by tomangelo2** [comment]
If it's supported by hardware, then it's not a problem IMHO. In my case max value is x8.

**Comment by krzys-h** [comment]
The max value is specifed by hardware capabilities. Do we really want to limit this manually?

**Comment by RaptorParkowsky** [comment]
So there's more than max x16 for MSAA? I'm confused...

**Comment by MrSimbax** [comment]
I don't see any problem here too.

**Comment by RaptorParkowsky** [comment]
Ok then, that's my bad. Close!
![You didn't see anything](http://i.imgur.com/UuKovnZ.gif)
