### ISSUE TITLE
Disable Astronaut's glasses rendering in FPP camera mode

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#775]
I don't really think they need to be visible all the time in FPP camera mode. This doesn't work in the gaming imersion.

Moreover, they're causing some strange render issues, when you choose transparent variant. Just look at that and find what's wrong with this screenshot (I doesn't photoshoped it in GIMP, honestly):
![zrzut ekranu2](https://cloud.githubusercontent.com/assets/4019345/14941608/9e55526c-0fa1-11e6-99c1-e22d07017df5.png)

**Comment by MatiRg** [comment]
I can do it
