### ISSUE TITLE
Documentation for the first mission

### ISSUE THREAD

**Issue by VictorDenisov** [colobot/colobot#784]
The documentation for the first mission says that only you can build buildings.
Since it's not true any more should the documentation be altered?

**Comment by RaptorParkowsky** [comment]
It will be altered when BuilderBots will be implemented. For now building using Grabbers is only placeholder.

**Comment by VictorDenisov** [comment]
I see. Looking forward to it. Btw, the changes you are making to the game are super cool. Awesome!

**Comment by VictorDenisov** [comment]
Are you going to add this BuilderBot to the standard missions? I would say it's pretty neat that I can program the whole mission using only bots.

**Comment by RaptorParkowsky** [comment]
Probably yes, because all missions requires refactoring and redesign. Of course there still will be some levels that require astronaut to do something (just like mission 3.1, 3.2...) but most levels should be able to pass by programming only.

**Comment by hexagonrecursion** [comment]
I have found two mentions of bots being incapable of building:

[levels/missions/chapter001/chaptertitle.txt :](https://github.com/colobot/colobot-data/blob/1759e5bd31bf0cadaf44723f7852423fe6912df1/levels/missions/chapter002/level001/help/soluce.E.txt#L4)

> remember that only you can build

[levels/missions/chapter001/level002/help/help.E.txt](https://github.com/colobot/colobot-data/blob/ba2a2414daedcb1b561ac1bdafb2061a56f84ac5/levels/missions/chapter001/level002/help/help.E.txt#L9)

> Note that only \l;you\u object\human; can accomplish the task of building; no bot can be substituted

I could not find any mention of building in chapter001/level001 Leaving Earth/Equipment.

Both are *technically true*: even though the game has builder bots, they are only available in the "new game plus" mode, but both the places I found are in the regular game mode.
