### ISSUE TITLE
Segmentation fault after closing code editor window

### ISSUE THREAD

**Issue by someniatko** [colobot/colobot#785]
I used that https://aur.archlinux.org/packages/colobot-gold package, which delivers colobot version 0.1.7b

If I go to any level / challenge, then click "Plus" button, then "Edit" {...} button, which opens the code editor and then close that code editor, game crashes with the following message:

```
Unhandled exception occured!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version 0.1.7b-alpha, but please verify that.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=challenges chap=4 rank=2
==============================

Sorry for inconvenience!
```

Then it asks wheter I wish to save the game, and in case I select "Yes" and then relaunch the game, after loading the save, it crashes again.

**Comment by Erihel** [comment]
This issue is on old version and does not contain too much information. I guess it can be closed as it could not be reproduced.

**Comment by someniatko** [comment]
@Erihel yeah, no problem
