### ISSUE TITLE
Allow ctrl + backspace in the editor.

### ISSUE THREAD

**Issue by VictorDenisov** [colobot/colobot#787]
Current editors allow ctrl + arrow - move one word left or right, ctrl + del, ctrl + backspace, delete one word or backspace one word.

It would be convenient to have this feature in colobot.

**Comment by RaptorParkowsky** [comment]
Definetely. :+1:

**Comment by MatiRg** [comment]
I think I have something similar

**Comment by MatiRg** [comment]
I think I can do it
