### ISSUE TITLE
Fix (very) minor spelling error

### ISSUE THREAD

**Issue by tim43784** [colobot/colobot#794]
Missing 'n' in (2nd) give[n] in: (colobot-)data/levels/exercises/chapter001/level007/help/help.E.txt.  
  
See attached word-diff: [help.E.txt.word-diff.txt](https://github.com/colobot/colobot/files/333361/help.E.txt.word-diff.txt)

**Comment by OctoNezd** [comment]
[https://github.com/colobot/colobot-data/pull/26](url)
Here is pull request with fix.

**Comment by OctoNezd** [comment]
Here is pull req with fix [https://github.com/colobot/colobot-data/pull/26](url)
