### ISSUE TITLE
Strange screen ratio

### ISSUE THREAD

**Issue by OctoNezd** [colobot/colobot#795]
![default](https://cloud.githubusercontent.com/assets/15308404/16372225/693b87ba-3c6d-11e6-91a5-9abc7fe35acf.png)
(1366x768 is 16:9)

**Comment by krzys-h** [comment]
Aspect ratio of 1366x768 is actually 683:384. See http://superuser.com/questions/946086/why-does-1366x768-resolution-exist

**Comment by OctoNezd** [comment]
I dont know what to say about it. It is the most strangest thing that I heard
