### ISSUE TITLE
Add support for sockets

### ISSUE THREAD

**Issue by OctoNezd** [colobot/colobot#796]
Why? It would help in making support for _many_ languages.

**Comment by Erihel** [comment]
Do you mean network support in CBOT?

**Comment by OctoNezd** [comment]
Not just network support - sockets.

**Comment by immibis** [comment]
What's the point besides being able to escape outside the simulation? Which is a bad thing BTW.

**Comment by hexagonrecursion** [comment]
Unfortunately the term "sockets" in this context is ambiguous:
1. It could be interpreted as a request to add a mechanism for bot-to-bot communication
2. It could be interpreted as a request to allow CBot to access the TCP and UDP sockets provided by most operating systems
3. It could be interpreted as a request to create an interface that allows the player to control the bots from an external process via some kind of interprocess communication
4. There may be other possible interpretations I have not thought of

I think this issue should be closed. It may be reopened if @OctoNezd clarifies his request. If someone else wants to propose some kind of "socket", I think using a different issue is preferable to hijacking this one.
