### ISSUE TITLE
Appearance menu models are way too high

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#802]
This is just one critical bug I found on newest release builds. Newly run game can't enter to Astronaut's appearance menu and shows this.

![schowek01](https://cloud.githubusercontent.com/assets/4019345/16731196/1bd60616-4777-11e6-9e7d-e584b9b9b5ba.png)

Similar thing can be seen in the logs:
`[INFO]: Loading level: levels/other/perso000.txt`
`[ERROR]: An error occurred while trying to load apperance scene`
`[ERROR]: Failed to open file: levels/other/perso000.txt`

Moreover the file that contains Astronaut's appearance data isn't created even after I load any level, etc.

**Comment by krzys-h** [comment]
I don't think this is critical, apperance menu is not a critical part of the game. It should be fixed ASAP though.

**Comment by RaptorParkowsky** [comment]
That's why I said it's critical... ;)

**Comment by krzys-h** [comment]
"Critical" would be something like the crash in 0.1.7 that would require an immediate patch release. This one is just important. ;)

**Comment by RaptorParkowsky** [comment]
So 0.1.8 will have broken appearance customization menu?

**Comment by RaptorParkowsky** [comment]
Now you can enter to appearance menu, but Astronaut's models are way too high in the UI.
![schowek01](https://cloud.githubusercontent.com/assets/4019345/19784224/3f894046-9c95-11e6-9f63-707d11afbf81.png)
![schowek02](https://cloud.githubusercontent.com/assets/4019345/19784233/45c58906-9c95-11e6-8845-18d99ef9e3b9.png)
