### ISSUE TITLE
Crash auto recovery seems to have removed the history of my missions.

### ISSUE THREAD

**Issue by VictorDenisov** [colobot/colobot#812]
After several crashes I might have agreed to save after a crash and then recovered when I was prompted at the startup. I successfully completed the mission, but then I discovered that the history of the missions I passed is gone.

**Comment by VictorDenisov** [comment]
commit: 407d8554669951be794788d37b268fb54bb67aec1

**Comment by lisa50469** [comment]
I had this happen today.  9/11/2016.  Linux version.  Found out the 'break' key doesn't exist on my keyboard, so I could not use the cheat codes to do 'allmissions'

**Comment by tomangelo2** [comment]
Console in Gold is available under ` key.

**Comment by Ceeee** [comment]
This happened to me too, exactly as described. Game crash in 0.1.8 (Win) in the first level with spiders shooting at them. Then recovery, and with the solved level I'm back to Level 1 now.

**Comment by attila123** [comment]
This also happened to me after the crash I described in #1027 .

**Comment by attila123** [comment]
The correct cheat is 'allmission' (not 'allmissions').
