### ISSUE TITLE
Append to file

### ISSUE THREAD

**Issue by CyborgMaster** [colobot/colobot#813]
I would love to have another file open mode for appending.   That way I could make a log file seeing as how the on screen messages only show 4 at a time and there's no way to look back.  Makes it hard to trace complex programs.  

Something like 

``` cpp
file handle();
handle.open("log", "a");
handle.writeln("message");
handle.close();
```

**Comment by MatiRg** [comment]
This would be great, and it should be rather easy to do.

**Comment by MatiRg** [comment]
I think I can do it.

**Comment by krzys-h** [comment]
Documentation update needed, ping @MrSimbax

**Comment by tomangelo2** [comment]
Documentation updated in https://github.com/colobot/colobot-data/commit/27d3674c6809b4c466e7cc81a7942a94c5280698
