### ISSUE TITLE
Proposals for CBOT appearance. Protecting public functions, hotkeys rearrangement, import class.h

### ISSUE THREAD

**Issue by AlexMakII** [colobot/colobot#825]
Initially wanted to add as comment to #478, but got too many text, so...
And sorry for lot of text, dont know if it should be stacked in one issue, feel free saying that I'm wrong.

1. About keeping public functions used by many bots. Can I propose PIP boy analogue. While astronaut exists in any mission (except code battles as I understand), portable PC obviously having transmiting/receiving hardware (receiving mission details from Huston), so it's usage as public code repository should fit game theme very well. In code battles, where astronaut is not available it can be replaced by small box (something like blackbox)
2. BTW I think that little rearrange of Fn hotkeys can be useful
2.1 F1 for instructions and in-level communications (log of messages - as idea example).
2.2 F2 for documentations.
2.3 F3 for code storage, also can be used for common base controlling stuff.
2.4 However, F3-F9 already are speed hotkeys. Don't you think that it got too many buttons, What if they were limited to F5-F8 (0.5, 1.0, 1.2, 2.0) and any other speed changes made by some -/+ buttons? So, you'll need just edit limitations, further.
3. Import code from files. I didn't find mention of that feature and consider it as missed. I think import construction can be helpful in two ways:
3.1 As programming conception it serves the main game goal - learn to code. Import is used almost in every language and almost everywhere it's very useful. That's main idea for those who just learn programming with colobot.
3.2 For the one who already know programming - import feature will save time on creating complex AI systems. And help better organize code without messing with public code.

Additionally to 1.
As of bot/building that runs Master AI (bigbrother bot from related issue). I dont think that spaceship should be used for this, while it can't be destroyed in acceptable amount of time and can't be involved into every mission (e.g. by its huge size and idea). Keeping your main bot is a mini goal that appears once you start doing complex systems and very realistic (doesn't involve deus-ex machine). In my case I made a priority system, where main bot most of time tracks orders, but can do common stuff if no other builders free/alive. However, as I mentioned above main bot can be replaced by controlling box (or torn off astronaut's hand with portable PC on it - unfortunately it will be another dramatic theme then =(  ).

**Comment by MrSimbax** [comment]
I remember 2. mentioned somewhere, but I can't find it.
3. already exists, it's one of the older issues: #238 
Please, split 1. and 2. to separate issues.

**Comment by AlexMakII** [comment]
Just to clarify some:
1. I'll move 1. to another issue, or 2. should be moved too?
2. Do I understand right, that next time better create separate issues for multiple proposals?

**Comment by MrSimbax** [comment]
I'd move both to new issues, to leave these comments out of the way. I'll then close this issue and mark it as invalid or smth.

Yeah, separate issues are far better. It's a lot easier to follow and discuss one thing at a time, also, when it's done or denied, it can be safely closed (a little more motivation for fixing it), and not kept opened. Closed issue shows progress in milestones. It's also easier to talk about them and assign them to specific person. Some issues are enough complicated when kept separetely, I can image a huge mess if they were joined together.

**Comment by AlexMakII** [comment]
Ok, thx.

**Comment by AlexMakII** [comment]
I've added two separate issues for 1 and 2 respectively, and this one can be closed.

**Comment by MrSimbax** [comment]
Thank you :)
