### ISSUE TITLE
Keeping public functions into astronauts portable PC.

### ISSUE THREAD

**Issue by alexmakii** [colobot/colobot#826]
My 2 cents to #478.

About keeping public functions used by many bots. Can I propose PIP boy analogue. While astronaut exists in any mission (except code battles as I understand), portable PC obviously having transmitting/receiving hardware (receiving mission details from Huston), so it's usage as public code repository should fit game theme very well. In code battles, where astronaut is not available it can be replaced by small box (something like blackbox), a lil baby to be saved from other-specie-bad-guys.

As of bot/building that runs Master AI (bigbrother bot from related issue). I don't think that spaceship/satellite should be used for this, while it can't be destroyed in acceptable amount of time and can't be involved into every mission (e.g. by its huge size and idea). Keeping your main bot is a mini goal that appears once you start doing complex systems and it's still realistic enough (doesn't involve deus-ex machine). 
e.g. Haveing the same trouble, I've made a priority system, where main bot most of time tracks orders, but can do common stuff if no other builders free/alive. So it stay out of dangerous situations most of time.
However, as I mentioned above, main bot can be replaced by controlling box (or torn off astronaut's hand with portable PC on it - unfortunately it will be another dramatic theme then =( ).
So, my main idea is that keeping a bot Master as in-game object - diversify gameplay.

**Comment by melex750** [comment]
Concept art:
![](https://www.dropbox.com/s/vdpaqdx0c72uyvl/Computer.png?dl=1)

**Comment by OctoNezd** [comment]
Maybe add to little box functions like build? I mean, bot grabs it, and builds using it. And then buildbot creation is not needed

**Comment by CyborgMaster** [comment]
One of the problems that may arise from a system like this is that all code battles will turn into "protect the public function box" games because any system complex enough to run a code battle will depend heavily on shared code and will be crippled if they are removed.

**Comment by Smok94** [comment]
If its destructible it can change gameplay dramatically. I think there should be indestructible entity for every side for this purpose and we can make it look like its stored on astronaut PC for plot reasons. But we can leave level creators to decide if player have access to this entity or he have to store this functions in destructible bot/entity. I have idea that black box could be that kind of destructible storage entity.
