### ISSUE TITLE
F# hotkeys rearrange. Minimize speed hotkeys number.

### ISSUE THREAD

**Issue by alexmakii** [colobot/colobot#827]
Right now speed controlling hotkeys take 7/12 of Fn's available. Don't you think that it got too many buttons, What if they were limited to F5-F8 (0.5, 1.0, 1.5, 2.0) and any other speed changes to be done by some -/+ buttons? After that, you'll need only to edit limitations, every time you need to add/remove new speeds. And no more "Now F10 controls speed too" required.

I think that little rearrange of Fn hotkeys can be useful in further.
- F1 for instructions and in-level communications (e.g. log of messages).
- F2 for documentations.
- F3 for code storage (relates to #826), also can be used for common base controlling stuff (e.g. building orders).
- F5-F8 for speed changes

**Comment by RaptorParkowsky** [comment]
For simulation speed there could be only F5 and F6 buttons as -/+ with some standard speeds. For more speed options there's allready cheat command.

**Comment by tomangelo2** [comment]
Or F5 -> slower, F6 -> standard speed, F7 -> faster.

**Comment by tomangelo2** [comment]
From d63ed86 there are only 3 speed control buttons, now F6 slows game down, F8 speed it up, F7 reset it to default value. Maybe also there would be separate buttons/textbox/something in Debug menu?
