### ISSUE TITLE
Damaged archive of the latest build?

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#829]
I was trying to download latest stable build of the application (from [Jenkins](http://compiled.colobot.info/job/colobot/job/colobot/branch/dev/) - [windows-debug.zip](http://compiled.colobot.info/job/colobot/job/colobot/branch/dev/lastSuccessfulBuild/artifact/windows-debug.zip)), and every time I was getting a damaged archive...
Here are few MD5 check sums for it:
- 5e0eb2b33b44c14e6461f889fa4ec62a
- ae3c8013b0564adc9977bbe05e0b91d7
- c51e77b702e453dbce717f016a7c3696

(yes, they are different)
Which MD5 is correct? BTW it isn't published at the download page - it would be great to have MD5 check sum there for verification.
Same problem happens with data.zip - MD5 checksums:
- 1097d87b7f4bb61fd573f2c64eb04454
- d443bd5cb0ed62ab088cad4593a840db
- d25799789dc96408b087b7574a6505da

Does same problem happen for everyone?

**Comment by krzys-h** [comment]
It could be that proxy on my old server is derping up, I keep forgetting to ask @zielmicha to update it to the new one. Try downloading from http://jenkins.krzysh.pl/ instead.

**Comment by Anton-V-K** [comment]
I've tried to download via the new link, and got similarly damaged archives.
Here are MD5 check sums:
fb4b55bbe527a38a1880d626e03344cf *data.zip
d47ef503df7263b877dd1d4af3be85d5 *linux-debug.zip
6eace55d606ce0bf99bd8b551ffab374 *windows-debug.zip
