### ISSUE TITLE
Crash lost completed missions.  No BREAK key to use the cheat codes.

### ISSUE THREAD

**Issue by lisa50469** [colobot/colobot#833]
Linux Ubuntu all updates.  Using Colobot from the PPA.
One of the crashes I had lost all the missions I had completed, so in frustration, I was going to use the cheats to do allmissions.  But my laptop keyboard has no 'break' key, so I'm unable to get into the screen to enter the cheat code.

**Comment by krzys-h** [comment]
The cheat console has been moved under the ~ since not all keybords have a BREAK key nowadays
