### ISSUE TITLE
Using the program clone button while the editor is open causes the game to get stuck in infinite pause

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#837]

**Comment by MatiRg** [comment]
I will look at it.

**Comment by MatiRg** [comment]
I can clone Program from UI and froom Editor it dont cause any issues

**Comment by MatiRg** [comment]
I still cant reproduce this.I dont have any Linux distro installed so I can test it on Linux.
I use Windows 7 32 bit + MSYS2.

**Comment by krzys-h** [comment]
Did some more testing just now, it seems to happen only if the copied program has errors
