### ISSUE TITLE
goto() path in debug console broken

### ISSUE THREAD

**Issue by paulmotey** [colobot/colobot#841]
Line 4160 and 4161 of engine.cpp in:
void CEngine::UpdateGroundSpotTextures()
 cause crash when goto() path testing.
4160       max.x = min.x + 254.0f + 1.0f; // FIXME motey
 4161       max.y = min.y + 254.0f + 1.0f;
old code over runs a buffer
       max.x = min.x + 254.0f + 2.0f;
        max.y = min.y + 254.0f + 2.0f;
This screen shot shows the convoluted way in which goto() works.
![screenshot from 2016-10-07 17-17-58](https://cloud.githubusercontent.com/assets/14113360/19207290/0ee5f596-8cb5-11e6-9a25-c8db2b4bcabc.png)
In this particular case it created thousands of paths before it selected one.

After changing the line 4160 and 4161 it works and is accessible with "F11" key and all debug functions work quite well.

**Comment by krzys-h** [comment]
Oh yeah, some people reported it, I noticed this only once and couldn't reproduce it since then. I will apply this patch, thanks.
