### ISSUE TITLE
Astronaut's dying scenes are cut

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#848]
It looks like EndMissionTake quits the level before the dying scene ends.

**Comment by piotrwalkusz1** [comment]
Because:
```
scene_conditions.cpp:148

        if (this->type == OBJECT_HUMAN)
            return INFO_LOSTq;
        else
            return INFO_LOST;
```

If human dies we have quick lost, if robot dies we have normal lost (2 secounds lasting). I propose to reverse it (death of human causes normal lost and death of robot causes quick lost) and maybe we should set "quick lost" to 2 seconds and "normal lost" to 4 or 6 seconds?
