### ISSUE TITLE
Particles near lava lake seem to crash the game

### ISSUE THREAD

**Issue by Ceeee** [colobot/colobot#850]
Level 6-2 Volcano-Analysis flying a shooter towards the lake to kill the ants on the island. On approach the game always crashes. Not a custom build but the Windows installer version of 0.1.8.

Tried different screen modes (windowed/full screen), different resolution, flight with 3rd person camera and, 1st person view - situation unchanged.

Unhandled exception occurred!
________________________________________
Type: std::runtime_error
Message: Tried to access invalid particle channel (invalid ID)
________________________________________

This is usually caused by a bug. Please report this on http://github.com/colobot
/colobot/issues
including information on what you were doing before this happened and all the in
formation below.
________________________________________
You seem to be running a custom compilation of version 0.1.8-alpha, but please v
erify that.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=6 rank=2
________________________________________

Sorry for inconvenience!

**Comment by RaptorParkowsky** [comment]
I can confirm that for official release version 0.1.8-alpha. But the current debug pre-0.1.9-alpha works fine. Possibly another nasty defference between debug and release compilation flags.

**Comment by tomangelo2** [comment]
> Possibly another nasty defference between debug and release compilation flags.
Or it was just already fixed in dev branch https://github.com/colobot/colobot/issues/806
If current version works fine, then I'll close it.

**Comment by krzys-h** [comment]
It was indeed fixed in #806
