### ISSUE TITLE
Can't stop programs / program list broken after loading savegame

### ISSUE THREAD

**Issue by Ceeee** [colobot/colobot#851]
The following has happened quite a few time now in 0.1.8 (Win/Install):

When I save a game while a bot is running a (looped?) programme, I cannot stop the bot's program execution anymore once the game is loaded again from that save game file. Also the list of Houston programs is emptied (code gone, only empty function "shells" in there).

Is this potentially linked to [https://github.com/colobot/colobot/issues/797](url) ? It looks the same as in the screenshot given there and the description matches my problem. The difference is that there was no crash involved here. The mission on which I encountered the problem was started from the menu and never crashed in itself. However there were other missions before that one that crashed and might have introduced some instability into the mission chain?

**Comment by RaptorParkowsky** [comment]
Is there any difference instead just no-crashing the game? Why making new issue for that. This is just unnecessary duplication of #797 . So closing.

**Comment by Ceeee** [comment]
No there is no additional difference beside the _one difference_ I mentioned clearly. And that was essential, since #797 is labelled "Robot programs list break **after restored crashed game**" Here there was neither a restore nor a crash, so I considered #797 to be imprecise and not wide enough. Plus I commented there, as you remarked correctly but that was for a crash -without- restore. As you can imagine not everybody is familiar with what happens under the hood, so it is not up to me to judge whether these differences are relevant or not. No need for telling your helpers off rudely. Discourages participation, you know!
