### ISSUE TITLE
Private/protected keyword for methods is not implemented

### ISSUE THREAD

**Issue by MariuszPL55** [colobot/colobot#854]
I don't know if I do something wrong, but if I write a simple class:

`public class Test
{
    private void DoSomething()
    {
        // TODO: Do something.
    }
}`

I receive that error: "No type declaration" it make no sense..

**Comment by krzys-h** [comment]
I think access qualifiers on methods may not be fully implemented yet. They are working fine on fields.

@melex750 and @CyborgMaster should know better as they contributed most of the inheritance implementation.

**Comment by melex750** [comment]
Currently, **private** and **protected** are for fields only and all methods are public.

The simplest way to implement this is to add the C++ syntax for access specifiers...
```c++
public class AClass {
    public:
    // public members here

    private:
    // private members here
    int a = 1;
    void privMethod() {
        // do stuff
    }

    protected:
    //...
}
```
But also keep the current syntax to be compatible with existing CBOT programs.

**Comment by krzys-h** [comment]
I think I would rather use a Java-like syntax because it's less confusing for beginners. Using "public" before method name is already supported, making it also do "protected" and "private" should be easy enough. I'm not sure how hard would it be to add it function calling code though.

**Comment by MariuszPL55** [comment]
I think adding both of these languages to Colobot will be a great idea! So people could program bots in Cbot as always, and also could do it in C++ and Java. I'd rather to program in C++ than in Cbot. Next great feature is possibility to separate classes into files that main program could use it.
