### ISSUE TITLE
Destructor not always called when returning this from function

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#859]
I just noticed some very weird behavior of destructors. Just to make sure my latest changes didn't break anything, I tested this on the master branch.

Try this code:
```C++
public class TestClass {
	void TestClass() {
		message("constructor");
	}
	void test() {
		message("test");
	}
	void ~TestClass() {
		message("destructor");
	}
}

extern void object::New()
{
	TestClass c();
	c.test();
}
```

It will work exactly as expected: the output will be "constructor", "test", "destructor"

Now, try:
```C++
public class TestClass {
	void TestClass() {
		message("constructor");
	}
	TestClass test() {
		message("test");
		return this;
	}
	void ~TestClass() {
		message("destructor");
	}
}

extern void object::New()
{
	TestClass c();
	c.test();
}
```

The output is "contructor", "test". Now, run this program again: the output will be "destructor", "contructor", "test" :open_mouth:

@melex750

**Comment by melex750** [comment]
Yeah that bug has been around for a long time. It does that because the stack isn't deleted when the program stops and the last instruction has left c on the stack.

return; or wait(); will clear the stack result.

I was never sure how to handle it.
This at the end of CBotProgram::Run() might be ok:
```if ( ok ) m_stack->SetVar(nullptr);```

See this too:
```c++
int Test() {
    128;
}
extern void object::New()
{
    message(""+Test());
}
```

**Comment by krzys-h** [comment]
If that is the case, I think changing `if (!ok && !m_stack->IsOk())` to `if (ok || (!ok && !m_stack->IsOk()))` towards the end of the Run() function should be enough, right? I will test that later.

**Comment by melex750** [comment]
I think maybe this instead.
```if ((!ok && !m_stack->IsOk()) || (ok && m_stack->IsOk()))```

**Comment by krzys-h** [comment]
Knowing how messy the CBOT code is I wouldn't assume that we won't get a situation where ok == true and m_stack->IsOk() == false. ok == true always means that the program has ended execution and Run() will not be called again.

**Comment by melex750** [comment]
Right. I wasn't sure if the stack should be preserved in that case for debugging or CBotUT or ???.
