### ISSUE TITLE
0.1.9  won't start on win7 ent 64bit

### ISSUE THREAD

**Issue by fistach** [colobot/colobot#860]
During startup it only shows "SDL error while setting video mode: Invalid window".

**Comment by tomangelo2** [comment]
What's your GPU? Are you sure you have newest video card driver?

**Comment by fistach** [comment]
I have Intel HD Graphics 520 and latest drivers.

**Comment by RaptorParkowsky** [comment]
Well, that's strange. I have Intel HD 510, Win8.1-Pro, newest drivers and when I disable my dedicated NVIDIA GeForce GTX 750 Ti and boot system using Intel, everything works fine.

**Comment by Anton-V-K** [comment]
The app runs good on Windows 7 Home Premium 64-bit with Intel HD Graphics 3000.

**Comment by krzys-h** [comment]
More likely to be a GPU driver fault than ours, closing

**Comment by mikkhalich** [comment]
To fix the error, try setting the desktop color depth to 32 bits
