### ISSUE TITLE
MagnifyDamage counter on UraniumOre

### ISSUE THREAD

**Issue by PracticeBot13** [colobot/colobot#862]
1st mission on Saari cannot be completed because of UraniumOre being destroyed by enemy fire.

This is also a problem on the 2nd mission of my Userlevel Planet "Bloodia".

Unless the MagnifyDamage counter could be made compatible with all objects icluding UraniumOre, both these levels will be nearly imposible to complete.

**Comment by OctoNezd** [comment]
There were an issue about that, but I can't find it

**Comment by krzys-h** [comment]
#777
