### ISSUE TITLE
Compilation error on macOS 10.12.1 (16B2555) 

### ISSUE THREAD

**Issue by LZaruba** [colobot/colobot#865]
Hi, following the instructions from INSTALL-MacOSX up to the step "make" I run into compilation error that is attached.
Brew is updated+upgraded to current version.

Do you please have any suggestions on how to compile the game (or download current .dmg file)?

Thanks for your good work!
Lukas

[compilationError.txt](https://github.com/colobot/colobot/files/613904/compilationError.txt)

**Comment by krzys-h** [comment]
This is likely the same issue that was already patched on latest dev in 3c71354b42057cb1e7b57fbdbc27c1905c56c968

**Comment by LZaruba** [comment]
The issue is verified on master as well as on dev.

Current git state when the log was created is:
**git status**: On branch dev
**git rev-parse HEAD**: b8d88c97b0aa3cc877be02416eadd0185daa5bcb

**Comment by krzys-h** [comment]
Does the compilation log change on dev in any way? That error mesage looks exactly like the one I mentioned

```
[ 37%] Building CXX object src/CMakeFiles/colobotbase.dir/ui/controls/edit.cpp.o
In file included from /Users/lukas/projects/colobot/src/ui/controls/edit.cpp:21:
/Users/lukas/projects/colobot/src/ui/controls/edit.h:260:46: error: implicit
      instantiation of undefined template
      'std::__1::array<Ui::HyperHistory, 50>'
    std::array<HyperHistory, EDITHISTORYMAX> m_history;
                                             ^
```

**Comment by LZaruba** [comment]
It was my mistake with git, I branched dev locally from master HEAD instead of checking out the origin/dev.
With origin/dev on 7190c8518e1814685bce91f336d2bda5f1b6514a I was able to compile and run the game.
Sorry for wasting your time.

There is an issue with building of the DMG package though. I will open new ticket for that.
