### ISSUE TITLE
object.factory() does not report an error if the object is already busy

### ISSUE THREAD

**Issue by Neospiro** [colobot/colobot#871]
Hi,

I'm writing a code battle program against ants and I have found a problem with "<botfactory>.factory(int type, string program)" return. You have to call it twice, and the second call will return true only if called during the end of cooldown.

I found a temp fix to have the correct behaviour : 

```
bool fixfactory( object botfac, int type, string program){
  return !bf.busy() and bf.factory(type, program) and bf.busy());
}
```

**Comment by krzys-h** [comment]
What are you expecting `factory()` to return? The returned value is not even a boolean, it's an integer that contains an error code (if any, 0 otherwise) and works only with `errmode(0)`. The actual problem may be that `factory()` does not generate an error if called while the object is busy.

**Comment by Neospiro** [comment]
So how that piece of code compiled and worked randomly ?? :D
