### ISSUE TITLE
Cursor allow to select insects by default, also turning viewfinder off on everything for Shooter bots

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#900]
It causes ability to take control over every insect. For Shooters it also turn viewfinder off when pointing on any object, plants, ores, practicebots, making shooting a bit harder, because you need to aim next to your target and then point to it.
![issue1](https://cloud.githubusercontent.com/assets/4140449/22384437/ac0a716e-e4ce-11e6-8ea5-03b71ec25e92.png)

**Comment by krzys-h** [comment]
I must've totally messed up 6a382830a95a36a2e643193729433ddba266c420 :stuck_out_tongue:
