### ISSUE TITLE
Aliens missing on minimap

### ISSUE THREAD

**Issue by DavivaD** [colobot/colobot#901]
Everything about this bug has been written on this topic: https://colobot.info/forum/showthread.php?tid=888

![colobot 2017-01-29 21-23-39](https://cloud.githubusercontent.com/assets/15150065/22407608/f4942be0-e669-11e6-89b1-0c27b750015d.png)

**Comment by tomangelo2** [comment]
Probably related with latest fixes for #900, it was working before this issue was closed.

**Comment by krzys-h** [comment]
I feel like this right now:
![gif](http://skillprogramming.com/images/pictuers/bug_line_415_to_420.gif)
