### ISSUE TITLE
Minimap doesn't detect some Ants

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#909]
![obraz](https://cloud.githubusercontent.com/assets/4140449/22955704/e7daf45e-f31d-11e6-9528-83a9e4f0d511.png)

Found when searching for #908, some AlienAnts weren't visible on minimap, although they were visible for radar in its UI. If it helps somehow, offensive ants were visible, these who decided to stay away from rocket were invisible. As you can see on attached screenshot, Wasps are visible on minimap, when Ants aren't visible at all.

**Comment by RaptorParkowsky** [comment]
Aliens that stay away from rocket (or SpaceShip if I know what you actually mean by "rocket") have nothing to do with this issue.

I've noticed that in recent dev build of the game any Alien that is already spawned on the level before building the RadarStation isn't shown on the minimap. Only newly hatched Aliens are visible.

The same situation exists when you use "invradar" cheat.

**Comment by DavivaD** [comment]
Is not it a accidentally duplicate of #901 ?
Minimap detects only flying (not landed) wasps.

**Comment by tomangelo2** [comment]
Right, I forgot that.
