### ISSUE TITLE
Command "delete(this.id);" crashes the game.

### ISSUE THREAD

**Issue by Quartofel** [colobot/colobot#925]
Just like the title, nothing else to add.

**Comment by immibis** [comment]
With this fix, `delete` with explosion type 5 (which is the animation used for waypoints when you drive over them) and 6 (Squash, normally only used for certain plants) get stuck trying to re-trigger the animation every tick, because these animations don't destroy the object immediately.

**Comment by melex750** [comment]
@immibis, I think I had that problem with animations when I was working on a userlevel.
Can you provide a test case or see if the changes in #1346 solve your issue?
