### ISSUE TITLE
QuickSave/QuickLoad

### ISSUE THREAD

**Issue by DavivaD** [colobot/colobot#929]
source: https://colobot.info/forum/showthread.php?tid=832

A lot of games have this feature.

It may look like KSP:
**F5** to QuickSave
Hold **F9** to load last QuickSave

**Comment by tomangelo2** [comment]
F5 is currently used for 1.5x speed, but I think it shouldn't be a problem, as there is already proposal of rearrange F keys (#827)
So IMHO it would looks like this:
F5 - Quick Save
F6 - slower (0.5x * current speed)
F7 - reset (1.0x)
F8 - faster (2.0x * current speed)
F9 - Quick Load

**Comment by OctoNezd** [comment]
Maybe add some menu for game speed, which would be called by pressing F2?

**Comment by tomangelo2** [comment]
So QuickLoad and QuickSave are already implemented, so this might be closed.
