### ISSUE TITLE
NuclearCell vs. NuclearPowerCell

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#932]
`radar(NuclearCell)` is accepted by the "compiler", though the documentation mentions `NuclearPowerCell`.
I guess, the constants were changed, though this introduces backward incompatibility into programs (just a minor issue).

And probably such constants renaming has introduced side-effects when handling nuclear power cells in the application: the radar under some conditions isn't able to find the cell.
Here is a sample code (adopted from the default method to collect titanium ore):
```
extern void object::CollectUranium()
{
	// 1) Variable definition.
	object  item;            // info. about objects
	
	//while (true)             // repeat forever
	{
		// 2) Go to the ore and grab it.
		item = radar(UraniumOre);// look for ore
		goto(item.position, 5);     // go to the position
		grab();                  // grab it
		
		// 3) Go to the conversion facility and drop it.
		item = radar(NuclearPlant);
		goto(item.position, 5);     // go to the position
		drop();                  // drop the ore
		move(-2.5);              // step back 2.5 m
		
		// 4) Wait until converted and grab it
		do
		{
			wait(1);              // wait for cube
			item = radar(NuclearCell, 2, 45, 0, 5); //< never returns an object
		}
		while ( item == null );
		
		goto(item.position);
		grab();                   // take it
		
		// 5) Go to free space and drop it
		goto(space(position));    // go to free space
		drop();
	
	}
}
```
The problem (with the version 0.19): the bot waits for the nuclear cell infinitely...

**Comment by melex750** [comment]
I found that misspelling in these files only.
```
/data/help/cbot/po/ru.po
/data/help/object/po/ru.po
/data/help-po/cbot/R/cbot/category.txt
/data/help-po/object/R/object/atomic.txt
```

**Comment by krzys-h** [comment]
The Russian translation seems to be just wrong. What @melex750 wrote is absolutely correct explanation of the second issue.
