### ISSUE TITLE
Documentation update for file.open()

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#936]
The fix #192 changed the directory where files are loaded from (and saved to).
However these changes aren't there in `dev` branch (I guess, they were moved elsewhere).
I did a quick test (in Code battles with 0.1.9 on Windows 7) and it isn't clear for me from where files are read...
I tried putting a test file into:

1. `savegame`
2. `savegame/files`
3. `savegame/Player`
4. `savegame/Player/files`

Every time I got the error like "Cannot open file".

The sample script:
```
	file hFile();
	hFile.open("test.txt", "r");
	string firmware = "";
	while(not hFile.eof())
	{
		firmware += hFile.readln() + "\n";
	}
	hFile.close();
```

After some experiments I've finally encountered the directory `files` at the same level as `savegame`, and relative paths like `../savegame/AntonK/program/HuntFromAir.txt` work fine. Great! :)
Well, the documentation needs some update...

**Comment by krzys-h** [comment]
@Anton-V-K The files are saved in files subdirectory of game save directory, not under <save dir>/savegame/files
Save directory is C:\Users\<username>\colobot (for Windows), ~/.local/share/clolobot (for Linux) or ./saves (on Debug builds)
