### ISSUE TITLE
progfunc: Unknown function

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#937]
The compiler doesn't accept notation like ([(c)](https://colobot.info/forum/showthread.php?tid=630&pid=5974#pid5974))
```
object it = radar(BotFactory);
it.factory(WingedShooter, progfunc("Shooter")); //<-- Unknown function
```
in Code battle mode with 0.1.9 (Windows 7).
I guess, `progfunc` is obsolete since it isn't required any longer to reference a function. I wasn't able to find related documentation in SatCom, so the keyword is only recognized by the editor...

**Comment by krzys-h** [comment]
The progfunc() syntax was deprecated before the final release of the 0.1.6 release that introduced Code Battles, and earlier .factory() was not even properly documented, therefore no mention of that anywhere in the docs. If you want to make a program that calls a public function, just use the function name itself like `it.factory(WingedShooter, "Shooter");`
