### ISSUE TITLE
Strange animation at speed x3.0 and faster

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#939]
The main wheeled grabber (in Code battles mode) has queer animation of its wheels at x3.0 and faster: each wheel is randomly rotating around own vertical axis (and the grabber often wobbles when moving, but that could be caused by the landscape - map "Code battle - vs aliens").
At x4.0 or faster wheels usually disappear, which doesn't stop the grabber though :) Reducing the simulation speed doesn't bring them back...
And at x3.0 speed (and faster) the building plan isn't deterministic: the buildings may be placed at other locations if compared to simulation at lower speed (`flatspace` is used in the script), but this is probably another issue...
Version 0.1.9 (Windows 7 64-bit).

**Comment by RaptorParkowsky** [comment]
Changeable simulation speed is a kind of unstable cheat at this time. Probably will require some physics/particle rewriting in the engine to make it more stable to simulation accuracy. That's why it's better to not experiment with this setting while normal usage of the game.

**Comment by krzys-h** [comment]
The animations being buggy at fast speeds are a known issue and almost impossible to fix considering how animations in Colobot are coded. CBOT not being reproducible, especially at higher speeds is something I'm aware of and wanted to fix for a long time, but I'll make a separate issue for it.

**Comment by krzys-h** [comment]
#1164
