### ISSUE TITLE
Texture loading fails in "Appearance" customisation

### ISSUE THREAD

**Issue by OdyX** [colobot/colobot#94]
When one enters the game and clicks "Appearance", the initial "head" appears correctly, but after any change (color, glasses, …), the head is displayed "white". Same if one clicks to customize the suit, that is also white (but the backpack isn't).

![colobot_appearance_textures_broken](https://f.cloud.github.com/assets/417403/16258/e93fdc18-481f-11e2-8d3f-b1125dd87b68.png)

**Comment by krzys-h** [comment]
I've just tested and it's broken again after f30592bf56143677d0302c06a0a6bc21dc2e179c
