### ISSUE TITLE
Modify scene parameters with CBOT

### ISSUE THREAD

**Issue by DavivaD** [colobot/colobot#946]
These functions make LevelController more usefull.
Proposition:
```
scenecolorparam(PARAM, TYPE, RRR, GGG, BBB); - sets scene color parameter (eg. VechicleColor)
sceneintparam(PARAM, TYPE, NUMBER); - sets scene (int?) parameter (eg. DeepView)
scenedisplayparam(PARAM, TYPE, "IMAGE"); - sets scene image parameter (eg. ForegroundName)
```
These functions can be stacked up.
Or Easier:
```
sceneparam(PARAM, "VALUE");
```
Sets scene parameter with 'VALUE' (example: setsceneparam(Background, "up=0;0;0;0 down=0;0;0;0");

**Comment by krzys-h** [comment]
It's not that easy. It's not possible to hook CBOT directly into level loader, and some things are not even changeable while level is running. If we want to do anything like this, we will need to design proper CBOT APIs for that.
