### ISSUE TITLE
No error message while fire(); value is too high

### ISSUE THREAD

**Issue by DavivaD** [colobot/colobot#949]
Video is Showing what is the problem...
Video:
https://youtu.be/lJLuymfFR5Q

Code:
```
extern void object::Nowy()
{
	object item;
	point KillBot (150, 0);
	turn(180);
	wait(10);
	fire(30);
	item=radar(PowerStation);
	goto(item.position);
	while(energyCell.energyLevel < 1) wait(0.01);
	goto(KillBot);
	item=radar(PowerStation);
	goto(item.position);
	goto(KillBot);
	item=radar(TrackedShooter, 0, 360, 0, 1000, FilterEnemy);
	turn(direction(item.position));
	fire(30);
}
```

**Comment by tomaszkax86** [comment]
I think there's a code that checks how much energy fire() would use and it won't let you execute it if it would use all of the bot's energy. It's similar to when you try to manually aim and fire and if the energy level is too low, you won't be able to shoot. You can try to shoot short bursts in a loop instead.

**Comment by tomangelo2** [comment]
With errmode(0); instruction fire(30); returns code 161, and this means "not enough energy" https://github.com/colobot/colobot/blob/dev/src/common/error.h#L63

**Comment by DavivaD** [comment]
With fire(5); works. Maybe some warning return?

**Comment by tomangelo2** [comment]
Probably because battery has enough energy to fire for 5 seconds. If you want to fire until battery will be drained you can write
```
while(fire(1) != 161);
```
Of course you need errmode(0);, otherwise it will just stop a program.
Maybe we should add some warning message for errmode(1);?
