### ISSUE TITLE
Crash after choosing programming help in robot program menu (Ubuntu)

### ISSUE THREAD

**Issue by Qbicz** [colobot/colobot#952]
Today Colobot crashed with this message during first mission on the Moon.
To reproduce:
- open objectives (F1)
- close objectives
- choose robot, open any program
- click "programming help".
Reproduced after launching the game again.

Ubuntu 16.04 LTS, installed Colobot from Ubuntu Software Center.
Version: Gold Edition 0.1.6-alpha 

> 
> Unhandled exception occured!
>
> SIGSEGV, segmentation fault
> 
> You seem to be running a custom compilation of version 0.1.6-alpha, but please verify that.
> 
> The game was in phase PHASE_SIMUL (ID=7)
> Last started level was: category=missions chap=2 rank=1

**Comment by krzys-h** [comment]
0.1.6 is reaaaaallly old, could you please retest on the latest version? I'm pretty sure we used to have some SatCom crash at that point, I'm not sure which one now, maybe #708. You can find in a PPA here - https://launchpad.net/~odyx/+archive/ubuntu/colobot

**Comment by Qbicz** [comment]
Ok, now I see 0.1.8-alpha release on github and 0.1.10 in launchpad ;)

Issue no longer occurs in latest release. Can be closed.

**Comment by krzys-h** [comment]
Oh, I completely forgot that I have to mark the releases separately on GitHub too. Thanks for pointing this out. I have a script that makes tags automatically since two releases and it seems GitHub doesn't pick that up automatically.
