### ISSUE TITLE
CEdit marigin is broken

### ISSUE THREAD

**Issue by muzscaly** [colobot/colobot#973]
Marigin overlaps the SatCom UI:
![colobot 2017-06-12 12-00-20-78](https://user-images.githubusercontent.com/15150065/27029147-638a6a30-4f67-11e7-925a-3229feb25c55.png)

**Comment by krzys-h** [comment]
It's not the highlights, it's the marigin values I broke in 08d87fa9757a05b66325b9ea77123d098143ddbd

**Comment by X64E** [comment]
@MrSimbax

Fixed at https://github.com/colobot/colobot/pull/1464

Issue must be colosed.
