### ISSUE TITLE
Custom levels bug when using colobot on pendrive

### ISSUE THREAD

**Issue by qbus2002** [colobot/colobot#975]
![image](https://user-images.githubusercontent.com/12773343/27168641-e568d5f0-51a6-11e7-98c1-e6154f9b48e5.png)
![image](https://user-images.githubusercontent.com/12773343/27168735-4d0609d0-51a7-11e7-8c03-49f756ee1d0b.png)
![image](https://user-images.githubusercontent.com/12773343/27168741-527996c0-51a7-11e7-8cc7-89262ad2ae24.png)

It happens on every computer and every pendrive that I have.
Here's the link for maps that I tried --> https://colobot.info/forum/showthread.php?tid=735
there are no problems when I'm playing from internal hard drive
If somebody tells me how to open developer console then I will give logs from console

Btw. I re downloaded colobot and the map pack and I have still same problem.
btw. nr2. I'm using colobot 0.1.10 Alpha
I found a solution for this I changed laungage to polish

**Comment by krzys-h** [comment]
This is a bug in the levels, not in the game. The levels have only Polish titles defined, and you are supposed to either always provide English titles too as a fallback for other languages or not do translations at all (use just Title instead of Title.P).

**Comment by hghk** [comment]
"אתם יכולים להגיד לי איך עושים בקולובוט "מותאם אישית

**Comment by tomaszkax86** [comment]
If you are asking how to make a custom Colobot level, there's an example here:
https://github.com/MrSimbax/colobot-alludo
You can use it as a template for your own levels.
