### ISSUE TITLE
"Show if the ground is flat" not working

### ISSUE THREAD

**Issue by qbuss** [colobot/colobot#976]
![image](https://user-images.githubusercontent.com/12773343/27169206-2357892c-51a9-11e7-81e8-94d0200fcc05.png)
as I said in title Master Alpha 0.1.10
Btw. nr1. When I change my grahics settings it started working
btw. nr2. When I changed my graphics settings back to normal the broblem goes away
btw. nr3. when I reinstalled game and leaved "default" setting the problem comes back
btw. nr4. i have Intel® HD Graphics 630

**Comment by RaptorParkowsky** [comment]
What graphic settings did you changed exactly?

**Comment by qbus2002** [comment]
I will check it tommorow but I clicked on the "normal" preset

**Comment by pestoffne** [comment]
Consider colobot gold v0.1.12-alpha

I reproduce the same issue on Ubuntu 20.04 with
VGA compatible controller: `Intel Corporation 4 Series Chipset Integrated Graphics Controller`.

It is not reproducable at all on Ubuntu 20.04 with
VGA compatible controller: `NVIDIA Corporation GK208B [GeForce GT 730]`

"Show is the ground is flat" does not color the ground with `default` settings, but works properly with `normal` and `highest` graphic settings. Sometimes it reproduces with `lowest`, sometimes it works properly with `lowest` with the same colobot.ini file in the same level with game rebooted after each settings change.

There are any ideas how to catch this bug?

**Comment by tomangelo2** [comment]
Recently there was a suggestion it may be caused by specific texture filtering setting. If anyone encounters this issue - please try other texture filtering settings and see if this is the case.
