### ISSUE TITLE
Why is it here?

### ISSUE THREAD

**Issue by qbus2002** [colobot/colobot#979]
![image](https://user-images.githubusercontent.com/12773343/27321541-dc1f30aa-559a-11e7-964b-924ee21f2b20.png)
First mission on earth
It disappears on other missions on earth

I'm also laughing at this beacose after I found the jetpack my game crashed without giving me an error xD

**Comment by DavivaD** [comment]
Good question.
I'm also wondering what's point of this....

**Comment by qbus2002** [comment]
I have a bigger question WHY IS'T IT HERE?
![image](https://user-images.githubusercontent.com/12773343/27322363-3062b3f0-559e-11e7-931b-41bbabe3aa76.png)
first and 2nd mission on earth
btw. you can get up here easy if you use the cliff on left side

**Comment by hghk** [comment]
אתם יכולים לשלוח לי  את  קולובוט למייל mqznlbwgn@gmail.com

**Comment by krzys-h** [comment]
That thing is clearly the place where they plan to put the SpaceShip...
