### ISSUE TITLE
load save -> crash

### ISSUE THREAD

**Issue by XzuRukneg** [colobot/colobot#984]
Crash when loading saved games:
[COLO-SAVE.bug.tar.gz](https://github.com/colobot/colobot/files/1100706/COLO-SAVE.bug.tar.gz)

>  Unhandled exception occurred!
> 
> SIGSEGV, segmentation fault
> 
> You are running official 0.1.9-alpha build.
> 
> The game was in phase PHASE_SIMUL (ID=7)
> Last started level was: category=missions chap=9 rank=4

Here two not loadable save files.

**Comment by tomangelo2** [comment]
Currently up-to-date version is 0.1.10, which contain few fixes for such crashes. Your saves are opening correctly under current release. If it's possible update your game and let us known if it doesn't fix that. https://colobot.info/download-colobot-gold/

**Comment by XzuRukneg** [comment]
I'll love to! But I've don't find GNU/linux version for now (using ubuntu).
Where can I found package please? (the 'officials links' gives .1.9-alpha.deb)

**Comment by krzys-h** [comment]
https://launchpad.net/~odyx/+archive/ubuntu/colobot

**Comment by XzuRukneg** [comment]
https://launchpad.net/~odyx/+archive/ubuntu/colobot ->That's the version I got.
Unfortunately, not avaible for 16.04LTS.
http://www.zimagez.com/zimage/capturedcran2017-06-2618-10-25.php

**Comment by melex750** [comment]
This is the same bug as #933 and #765. Fixed after 0.1.9 .
Unfortunately those saved games are broken. (I wasn't able to fix them.)

With those saves, using current dev:
I get assert failed on Xubuntu 16.04.2 LTS **64-bit**.
```
src/object/implementation/programmable_impl.cpp:158: virtual bool CProgrammableObjectImpl::ReadStack(FILE*):
Assertion `op < static_cast<int>(dynamic_cast<CProgramStorageObject*>(m_object)->GetProgramCount())' failed.
```
They fail quietly on Xubuntu 14.04.5 LTS **32-bit**,  with some cbot programs missing and others restarted.

Currently cbot.run file format is compiler/library dependent.
The contents of cbot.run looks like those saves may be from a 64-bit system.

**Comment by krzys-h** [comment]
You can just remove the cbot.sav file and the save will load but all cbot programs will be restarted.

@OdyX what versions are we supporting in the PPA? Isn't 16.04 the last LTS release?

**Comment by XzuRukneg** [comment]
Thanks, remove the cbot.run file solve the problem.

**Comment by XzuRukneg** [comment]
@OdyX what versions are we supporting in the PPA? Isn't 16.04 the last LTS release?
Can we have last version for 16.04 please?
![colo-ppa](https://user-images.githubusercontent.com/4454843/31641623-2af0c240-b2e6-11e7-9097-211528c41cb6.png)
