### ISSUE TITLE
Math near border values return wrong results.

### ISSUE THREAD

**Issue by Arano-kai** [colobot/colobot#993]
Ver: 0.1.9
OS: Debian (stretch)
Issue:
```
i = abs(-2147483606); // -2147483648
i = -2147483600 * 1; // -2147483648
i = 2147483600 * 1; // -2147483648
i = 2147483646 * 1; // -2147483648
i = 2147483646 * -1; // -2147483648
i = 2147483000 * -1; // -2147483008
i = 2147483000 * 1; // 2147483008
```

**Comment by tomaszkax86** [comment]
Looks like these operations are performed on `float` rather than `int`, hence it loses precision after 7 decimal places. This definitely needs to be checked.

**Comment by MrSimbax** [comment]
That's right, I tested it once. http://colobot.info/SatComOnline/master/cbot/expr

**Comment by MrSimbax** [comment]
Looks like all of those examples are fixed except
```
i = abs(-2147483606); // -2147483648
```

**Comment by melex750** [comment]
Oops, I forgot about that, the other math functions also need attention. I'll have a look this evening.

**Comment by hexagonrecursion** [comment]
This issue has been fixed and should be closed.
