### ISSUE TITLE
Change font names to more user-friendly

### ISSUE THREAD

**Issue by bayerchemistry** [colobot/colobot#995]
I suppose that Colobot uses only 2 fonts: sans for menu and satcom and monospace for cbot. Point is to change "dvu_sans.ttf" into just "sans.ttf" and "dvu_sans_mono.ttf" to "monospace.ttf". This solution makes modding/testing fonts easier.

**Comment by tomangelo2** [comment]
Even better would be possibility to change fonts via in-game options menu, or maybe in colobot.ini file if current UI code wouldn't allow that.

**Comment by DavivaD** [comment]
I don't like that feature about changing fonts from INI file as @tomangelo2 proposed. But rather like @bayerchemistry proposed. Beacuse this is not looking good comparing with mods support.

**Comment by tomangelo2** [comment]
Changing fonts from .ini file would be rather temporary solution if current UI code wouldn't allow us to change fonts while in game. I also prefer changing fonts via Options menu.

**Comment by RaptorParkowsky** [comment]
@DavivaD That's a good point. But I think we can avoid this by splitting font settings to another ini configuration file and place it to data/fonts with all required fonts. Then modders could make their own mods with modified fonts in some places in the game. Syntax of the file:
`[Font]`
`UIFont=font_name_0`
`CBOTFont=font_name_1`
`SatComFont=font_name_2`
`etc`

**Comment by tomangelo2** [comment]
Fonts are now configurable by fonts/fonts.ini file since #1031 , this issue should be closed. Potentially new issue with configuring default fonts in UI could be opened.
